### ISSUE TITLE
rex::getServer() und rex::getProperty('server') geben "default" zurück

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yrewrite#100]
https://github.com/redaxo/redaxo/issues/640

**Comment by gharlan** [comment]
Ich schlage vor, dass wir die Werte nicht mehr überschreiben. Sehe nicht, wofür das (aktuell noch) notwendig sein sollte.
@dergel Wie siehst du das?

**Comment by cukabeka** [comment]
könnte man das nicht evtl als einstellung auswählbar machen?
