### ISSUE TITLE
Custom Urls am Ende mit Suffix oder ohne

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#101]
Bisher wird die Custom Url immer ohne dem Suffix gespeichert. Fügt man am Ende der Custom Url das Suffix "/" ein, kommt eine Warnung.

Klingt erst einmal verkehrt, könnte aber auch so gewollt sein. Wie seht ihr das @dergel, @gharlan 
Siehe auch https://github.com/tbaddade/redaxo_url/issues/2

**Comment by tbaddade** [comment]
Gibt es eine Methode um die aktuelle Url auf CustomUrl zu prüfen?

**Comment by tbaddade** [comment]
@dergel, @gharlan klopf klopf

**Comment by alexplusde** [comment]
Wer ist da?

**Comment by tbaddade** [comment]
> I am the one who knocks

**Comment by alexplusde** [comment]
https://www.youtube.com/watch?v=2tmc8rJgxUI&t=60

**Comment by alexplusde** [comment]
Okay, jetzt weiß ich, was @tbaddade meint. Da läuft wirklich was verkehrt:

mit /
![image](https://cloud.githubusercontent.com/assets/3855487/17178702/bf90b76e-5416-11e6-893b-589a6452546f.png)

ohne /
![image](https://cloud.githubusercontent.com/assets/3855487/17178768/04e08a38-5417-11e6-8a78-69b6baaad4ad.png)


Standard (ist immer mit /)
![image](https://cloud.githubusercontent.com/assets/3855487/17178718/d9c565b2-5416-11e6-827d-c8ec16817ba2.png)

Generell sollte es in meinen Augen so sein, dass die URL ohne Suffix-Slash von Haus aus weiterleitet auf die URL mit Suffix-Slash.

**Comment by alexplusde** [comment]
Das ist wirklich ein Problem, das Feature wird damit doch komplett unbrauchbar.

**Comment by gharlan** [comment]
> Generell sollte es in meinen Augen so sein, dass die URL ohne Suffix-Slash von Haus aus weiterleitet auf die URL mit Suffix-Slash.

Das ist bereits so.
Oder genauer: Wenn eine URL nicht existiert, wird in der Scheme-Klasse abgefragt, ob es denn Alternativ-Kandidaten gibt. Falls ja, werden die geprüft, ob es auch wirklich existierende URLs sind, und wenn ja, wird dahin umgeleitet.
Die Standard-Scheme-Klasse prüft immer, ob die URL schon mit dem Standard-Suffix endet, und wenn nein, liefert sie als mögliche Alternative die URL mit angehängtem Suffix:
https://github.com/yakamara/redaxo_yrewrite/blob/02a9f319fa3cf90633f8e00b78afde1c1663f4c8/lib/scheme.php#L104-L117

Das Verhalten lässt sich also bei Bedarf über eine eigene Scheme-Klasse anpassen.

**Comment by tbaddade** [comment]
Wäre es nicht sinnvoller, dass der User die Url immer mit dem gesetzten Suffix notieren muss.

Der Admin legt die Urls mit dem **/** als Suffix fest. Der Redakteur notiert jetzt eine Url mit **.html**. Das ist zwar nicht verkehrt aber auch nicht das, was der Admin (ggf. auch vorher in Meetings gemeinsam besprochen und vereinbart wurde) zuvor festlegte.

**Comment by phoebusryan** [comment]
Könnt ihr das Issue bitte wieder öffnen, damit es nicht untergeht? Ich habe gerade das gleiche Problem wie @nilsology in https://github.com/tbaddade/redaxo_url/issues/2
