### ISSUE TITLE
Fehler bei Weiterleitung - Zieldomain hat "//" am Ende

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#104]
**Version**

|  | Version |
| --------- | ----- |
| `core` | `5.1` |
| `yrewrite` | `2.0.1` |

**Domains:**
es ist nur eine Domain eingetragen: `www.domain.de`

**Alias Domains:**
Domain: `domain.de`
Alias: `www.domain.de`

| Aufruf | Ziel | Status |
| --------- | ----- | ----- |
| `www.domain.de`| `www.domain.de`| richtig |
| `domain.de`| `www.domain.de//`| **falsch** |
| `domain.de/sub/`| `www.domain.de//sub/`| **falsch** |

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yrewrite/commit/1ca97ef98ba5653c2dcd95a870fcd8b62696d8ea

ist nun drin
