### ISSUE TITLE
Sonderzeichen in Description

### ISSUE THREAD

**Issue by loesungsmittel** [yakamara/redaxo_yrewrite#105]
Wir würden gerne Sonderzeichen wie Häkchen in der Description unter SEO-Daten nutzen. Leider wird z.B.

`&#10004;`

im Frontend HTML-kodiert zu

` &amp;#10004;`

und wenn wir den Haken als Zeichen einfügen gibt er nur ein Fragezeichen aus, hat also Zeichensatzprobleme.

**Comment by loesungsmittel** [comment]
Gibts hier schon neues? Ich kenn mich leider so tief in Redaxo nicht aus um es selber machen zu können.

**Comment by staabm** [comment]
Welche resaxo version? Verwendet dein frontend utf8?

**Comment by dergel** [comment]
wie kommt das html kodierte Zeichen da rein ? Wenn du das Zeichen direkt einträgst sollte es klappen ? oder verstehe ich etwas falsch ? 

aktuellste redaxo 5 und aktuellste yrewrite version

**Comment by dergel** [comment]
@loesungsmittel kannst du nochmal schauen? Du müsst das Sonderzeichen unkodiert, also das Zeichen selbst einsetzen, dann sollte es gehen.
Bitte nochmal eine Info ob es immernoch Probleme gibt

**Comment by loesungsmittel** [comment]
Entschuldige die späte Reaktion. Seit der Version 5.1 klappt es bestens.
