### ISSUE TITLE
"ErrorException" wenn Sprache gelöscht wurde

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#106]
Wenn ich einer Domain mehr als eine Sprache zuweise und diese Sprache dann unter System lösche wird beim Aufruf von yrewrite folgende Fehlermeldung ausgegeben:

```
"ErrorException" /Applications/MAMP/htdocs/rex5basic2/redaxo/src/addons/yrewrite/pages/domains.php on line 148
Fatal error: Call to a member function getName() on null
```

LG
Oliver

**Comment by gharlan** [comment]
Das Problem scheint mir nicht mehr zu bestehen.
