### ISSUE TITLE
Kyrillische / Grieschische Zeichen

### ISSUE THREAD

**Issue by tgoellner** [yakamara/redaxo_yrewrite#109]
Kyrillische Buchstaben (oder griechische) werden nicht korrekt umgewandelt - ich hab das lokal gefixt, indem ich der Datei /lib/scheme.php noch eine Variable $maps spendiert habe, die dann alle Ersetzungsangaben beinhaltet ('geklaut' von [urlify](https://github.com/jbroadway/urlify/blob/master/URLify.php#L20)):

Dann können die Zeilen [127-131](https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/scheme.php#L127) durch diese ersetzt werden:

<code>
foreach($this->maps as $code => $replace) $string = str_replace(array_keys($replace), array_values($replace), $string);
<code>

**Comment by staabm** [comment]
Ggf sollten wir direkt urlify einbinden?

**Comment by gharlan** [comment]
Wir wollen wahrscheinlich auch UTF8-URLs ermöglichen. 
Und eventuell eine Konvention einführen, wo man Sprachersetzungen ablegen kann.
Und man kann ja auch recht leicht eine eigene Schema-Klasse erstellen, und dort die Normalisierung anpassen.
Bin mir nicht sicher, ob wir solche festen Listen aufnehmen sollten.

**Comment by dergel** [comment]
Ich würde ungerne solche Listen fest reinnehmen. UTF8_URLs sind ja möglich. Aber wir Gregor sagt - gerne als Liste die man z.B. im Data-Ordner ablegen kann. Idee wie ?

**Comment by alexplusde** [comment]
Falls mal eine Liste gesucht wird.
https://github.com/starlord/seo42/blob/master/langpresets.inc.php

Am sinnvollsten fände ich es, die Liste als Sprachen-Meta anzulegen, denn da gehören sie ja eigentlich auch hin.

**Comment by dergel** [comment]
sowas in der art war angedacht. optional und kann man dann im dataordner ablegen und wird genommen, falls vorhanden

**Comment by dergel** [comment]
weil man nun eigen schemata anlegen kann, ist jeder frei wie er/sie/es das haben möchte

**Comment by alexplusde** [comment]
Weil ich über https://github.com/tbaddade/redaxo_url/issues/184 wieder hier draufgestoßen bin: Warum nicht standardmäßig utf8-urls ermöglichen? Ein eigenes Schema möchte ich nicht anlegen.

In der Doku finde ich nichts zu eigenen Schemen - ich bin mir nicht mal sicher, ob ich ein eigenes Schema will, sondern denke, ich möchte nur die Art der Normalisierung überschreiben.

**Comment by tbaddade** [comment]
> In der Doku finde ich nichts zu eigenen Schemen - ich bin mir nicht mal sicher, ob ich ein eigenes Schema will, sondern denke, ich möchte nur die Art der Normalisierung überschreiben.

Du kannst alles belassen und nur das normalize überschreiben. 

In der boot.php des Project AddOns
```
// register a custom yrewrite scheme
rex_yrewrite::setScheme(new Project\Scheme());
```

Diese Code als `Scheme.php` abspeichern und in das `lib` Verzeichnis des Projekt Addons legen.
```php
<?php
namespace Project;

class Scheme extends \rex_yrewrite_scheme
{
    /**
     * @param string $string
     * @param int    $clang
     *
     * @return string
     */
    public function normalize($string, $clang = 1)
    {
        $string = str_replace(
            ['Ä',  'Ö',  'Ü',  'ä',  'ö',  'ü',  'ß',  'À', 'à', 'Á', 'á', 'ç', 'È', 'è', 'É', 'é', 'ë', 'Ì', 'ì', 'Í', 'í', 'Ï', 'ï', 'Ò', 'ò', 'Ó', 'ó', 'ô', 'Ù', 'ù', 'Ú', 'ú', 'Č', 'č', 'Ł', 'ł', 'ž', '/', '®', '©', '™'],
            ['Ae', 'Oe', 'Ue', 'ae', 'oe', 'ue', 'ss', 'A', 'a', 'A', 'a', 'c', 'E', 'e', 'E', 'e', 'e', 'I', 'i', 'I', 'i', 'I', 'i', 'O', 'o', 'O', 'o', 'o', 'U', 'u', 'U', 'u', 'C', 'c', 'L', 'l', 'z', '-', '',  '',  ''],
            $string
        );
        $string = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $string);
        $string = preg_replace('/[^\w -]+/', '', $string);
        $string = strtolower(trim($string));
        $string = urlencode($string);
        $string = preg_replace('/[+-]+/', '-', $string);
        return $string;
    }
}
```

Jetzt die Methode nach deinen Wünschen anpassen.

**Comment by alexplusde** [comment]
via @gharlan ausgegraben - hier wird's grob erklärt: https://github.com/yakamara/redaxo_yrewrite/issues/170

**Comment by skerbis** [comment]
@alexplusde yrewrite scheme sollte das eigentlich schon machen
