### ISSUE TITLE
Eigene htaccess-Regeln definieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#113]
Wie ist das aktuell, wenn ein neuer YRewrite-Release erscheint und die htaccess geupdatet werden muss: Gehen dann Änderungen an der htaccess verloren? Wird eine automatische Sicherung angelget, wie bei SEO42 früher?

Konkret möchte ich eine Regel für ein MediaManager-Effekt anlegen, der Dateien mit dem passenden Header-Effekt forciert herunterlädt und der beim Update oder bei Änderungen nicht wieder verschwindet.

Da - wie in meinem Beispiel - `/imagetypes/download/attachment.pdf` einfach nicht schön aussieht, wäre es sinnvoll, wenn von Haus aus auch ein Rewrite für `/media/<imagetype>/<filename>` existiert. Schließlich ist es ja nicht mehr der "Image Manager", sondern der "Media Manager".

**Comment by gharlan** [comment]
Die htaccess wird nicht aktualisiert, geht also nicht verloren, aber es werden auch keine Änderungen eingespielt.
Sondern man muss das Aktualisieren der htaccess selbst anstoßen, wenn man das möchte (wie bei der Erstinstallation). Dann wird sie aber komplett überschrieben.

**Comment by phoebusryan** [comment]
Custom-htaccess Rules würde ich irgendwo in die yrewrite-Config schreiben, damit diese dann übernommen werden. Wäre doch was.

Bzgl. den Image-Rules gibts ja mehrere:

`RewriteRule ^files[0-9]*/imagetypes/([^/]*)/([^/]*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]`

`RewriteRule ^images/([^/]*)/([^/]*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]`

`RewriteRule ^imagetypes/([^/]*)/([^/]*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2`

Grundsätzlich kannst du auch Nummer 2 statt 3 nehmen. Dieser funktioniert für dich ganz sicher auch.

**Comment by alexplusde** [comment]
`files/imagetypes/download/attachment.pdf` ... ob man das wirklich will?

**Comment by alexplusde** [comment]
> Sondern man muss das Aktualisieren der htaccess selbst anstoßen, wenn man das möchte (wie bei der Erstinstallation). Dann wird sie aber komplett überschrieben.

@gharlan wenn die alte .htaccess in den data-Ordner gesichert würde mit timestamp, hätte man noch einen Fallback, falls man aus Versehen die .htaccess updatet und versehentlich eigene Regeln überschreibt.

**Comment by gharlan** [comment]
Ja, klingt nicht verkehrt. Oben war auch nur eine Beschreibung des Ist-Zustands, beinhaltete keine Meinung von mir, ob es so bleiben soll, oder nicht. ;)

**Comment by dergel** [comment]
sich in die htaccess regeln reinhaeöngen können.
https://github.com/yakamara/redaxo_yrewrite/issues/122
