### ISSUE TITLE
Option "Offline-Artikel auf Fehlerseite weiterleiten"

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#116]
Am besten pro Domain einstellbar.

**Comment by fietstouring** [comment]
+1

**Comment by dergel** [comment]
Was passiert im Moment ? .. Ob Offline auch wirklich offline ist entscheidet der Entwickler. Aber ließe sich auch fest einbrennen.

**Comment by alexplusde** [comment]
Im Moment wird fleißig das Addon "accessdenied" verwendet, das jedoch einen 3. Status hinzufügt.

Der Entwickler muss immer von sich aus aktiv werden, um "offline = nicht erreichbar von außen ohne Login" als Funktionalität herzustellen. Bei Youtube heißt sowas "nicht gelistet" oder in anderen Systemen "versteckt" - was offline ist, ist eigentlich unstrittig.
