### ISSUE TITLE
Validierung der Domain Eingabe

### ISSUE THREAD

**Issue by ceekay82** [yakamara/redaxo_yrewrite#120]
Unter dem Reiter Domains wäre es beim Hinzufügen oder Ändern eines Eintrags schön, die eingegebene Domain zu validieren, so dass sie ohne http:// oder https:// eingetragen wird. Ansonsten funktioneren evtl. Weiterleitungen nicht.

**Comment by gharlan** [comment]
Wie in skype erläuter, ist das Absicht, dass man es so eintragen kann, und stattdessen müssen wir halt die Weiterleitungen korrigieren.

**Comment by gharlan** [comment]
Daher mache ich hier doch wieder zu, und #119 stattdessen wieder auf. ;)

**Comment by tbaddade** [comment]
Bin mir nicht sicher, aber ich meine das betraf noch andere Stellen.
