### ISSUE TITLE
Individual-Weiterleitungen je Artikel

### ISSUE THREAD

**Issue by alexwenz** [yakamara/redaxo_yrewrite#124]
Wie eben in Slack besprochen bestünde zumindest auf meiner Seite der Wunsch für Weiterleitungen, die man im Artikel definieren kann. Z.B. Kategorie-Startartikel auf eine Unterkategorie.

Gerne genutzt von mir in Rex4 war die "URL-Page" aus dem SEO42-Addon (siehe Bild)

![urlpage](https://cloud.githubusercontent.com/assets/5278794/17590551/6fb098b6-5fda-11e6-95fd-4de81b24b44d.jpg)

**Comment by tyrant88** [comment]
Ein Push von mir, weil z.B. unsere Kunden mit "externe URL" ihre eigenen Social Links pflegen

**Comment by alexplusde** [comment]
@lus Ob hier erst der Chef persönlich in die Falle treten muss? ;D

+1 von mir.

**Comment by omphteliba** [comment]
Diesen Wunsch würde ich unterstützen!

**Comment by dergel** [comment]
Auf jeden Fall ist sowas sinnvoll - ich nurnoch nicht geantwortet, weil ich nciht weiss, ob das nicht besser im structure addon, also im core, eingebaut werden müsste.. aber sowas in der Art wird kommen..

**Comment by netzproductions** [comment]
Könnte ich gut einsetzen!

+1 von mir

**Comment by alexplusde** [comment]
Wie schaut's aus, wer hat Bock? :D

**Comment by dpf-dd** [comment]
Ich schließe mich an! Ein absolut benötigtes Feature, aber es mangelt an Kenntnisse mich bei der Umsetzung zu beteiligen :(

**Comment by skerbis** [comment]
Lässt sich doch sicher mit einem REWRITE-Scheme regeln - oder?

**Comment by marcohanke** [comment]
Gerade eben kam im Slack wieder der Wunsch nach der o.g. Funktion auf.

**Comment by dpf-dd** [comment]
Es soll sich bitte niemand genötigt fühlen, aber ich muss das nach 1 Jahr mal wieder pushen... :)

**Comment by dergel** [comment]
Ist auf dem Schirm und eher ein REDAXO Core Thema wo sich dann wiederum das rewrite addon dranhaengt

**Comment by tbaddade** [comment]
Da wir das AddOn selbst nie einsetzten, kann uns jemand kurz erklären, was die folgenden Punkte genau machten:

- interne Ersetzung
- interne Ersetzung inkl. Sprache
- Root Kategorie entfernen (wurde hier nur Root entfernt oder alle Elternkategorien?)
- Sprachumschalter

Zusätzliche Idee:
- Weiterleitung auf erste Online-Kindkategorie

**Comment by tyrant88** [comment]
"Root Kategorie entfernen" hat wirklich nur die unterste Ebene entfernt. Das brauchte man, wenn man seine verschiedenen Menus in Kategorien hatte, diese aber nicht in der URL auftauchen sollten ( z.B. statt "hauptmenu/kat1/typ2/ding1" nur "/kat2/typ2/ding1" und "menu_unten/impressum" wird nur "/impressum").
Das kann man aber mittlerweile mit dem yrewrite_scheme-AddOn machen. Da kann man einfach eine Liste von Kategorien angeben, die entfernt werden.

**Comment by alexwenz** [comment]
**1. interne Ersetzung:** 
hier konnte man einen Artikel auswählen, auf den weitergeleitet wird. Damit konnte man z.B. eine Kategorie, die einen leeren Startartikel hatte, auf einen bestimmten Unterartikel verweisen. Dies wurde dann auch in der Navi direkt in der URL hinterlegt. ("/kategorie/" wurde zu "/kategorie/unterartikel/".

(ist heute mit yrewrite_scheme global möglich, d.h. wenn leerer Startartikel, dann ersten Unterartikel anzeigen. Aber eben nur global)

**2. interne Ersetzung inkl. Sprache**
siehe 1. inkl. automatischer Sprachwechsel

*3. Sprachumschalter*
einfache Möglichkeit, in die Hauptnavigation einen Sprachwechsel zu integrieren: Kategorie anlegen, in den Startartikel gehen und die gewünschte Sprache wählen in die gewechselt werden soll. Hier wurde dann immer der aktuelle Artikel in der jeweilig anderen Sprache verlinkt.

**Comment by tbaddade** [comment]
Danke für eure Erklärungen

> 3. Sprachumschalter
> einfache Möglichkeit, in die Hauptnavigation einen Sprachwechsel zu integrieren: Kategorie anlegen, in den Startartikel gehen und die gewünschte Sprache wählen in die gewechselt werden soll. Hier wurde dann immer der aktuelle Artikel in der jeweilig anderen Sprache verlinkt.

Ich habs mehrfach gelesen und nicht verstanden :)
Hast du als Kategorie deutsch/english/italiano angelegt und dann mit der jeweiligen Sprache verknüpft? 
Ist diese Option noch interessant für Redaxo 5?

**Comment by alexwenz** [comment]
> Ich habs mehrfach gelesen und nicht verstanden :)
Habe ich mich maximalkompliziert ausgedrückt ? ;-)

> Hast du als Kategorie deutsch/english/italiano angelegt und dann mit der jeweiligen Sprache verknüpft?

So ungefähr. Habe es damals nur bei zweisprachigen Webseiten eingesetzt. D.h. in der deutschen Struktur habe ich "EN" als Hauptelement eingesetzt und in der englischen "DE" und dann jeweils die Option genutzt. 

Ich meine mich zu erinnern, dass ich die Funktion bei noch einer Gelegenheit verwendet habe. Was es genau war, habe ich leider nicht mehr auf dem Schirm...

> Ist diese Option noch interessant für Redaxo 5?
Das ist natürlich eine gute Frage. Ich würde mal sagen, würde es manchmal die Sache sicherlich erleichtern. D.h. wenn es eine kleine Erweiterung ist, wäre es ein "Nice to have"

**Comment by skerbis** [comment]
> Sprachumschalter 
Leitet nur die url um

**Comment by dergel** [comment]
zunächst:
* Custom URL
* Externe URL
* Interne URL (Linkmap)
