### ISSUE TITLE
content.yrewrite_url.php - lange Urls brechen nicht um

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#130]
Es würde reichen um die Variable `$autoUrl` ein `<pre>` zu notieren, was aber dem Template dann nicht als `notice` übergeben werden darf, da `<pre>` nicht in einem `<p>` vorkommen darf.

**Comment by dergel** [comment]
lieber als text-overflow: ellipses;
sonst muss an der yform wieder was gefummelt werden.

**Comment by tbaddade** [comment]
> lieber als text-overflow: ellipses;

finde ich nicht gut, da man die Url nicht mehr als Ganzes erkennen wird. Ich hatte schon einiges getestet und das Beste war eben dieses `<pre>` einzusetzen. Damit wird die Url einfach dort umgebrochen wo es grad nötig ist.

**Comment by staabm** [comment]
geht das nicht mit sowas https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/ ?

**Comment by tbaddade** [comment]
Genau das macht das `<pre>` [in Kombi mit BS3](https://github.com/twbs/bootstrap-sass/blob/446b41a5af0f20f139a6d33ded2a62101c3bd5a1/assets/stylesheets/bootstrap/_code.scss#L41-L52)
Sicherlich kann man das auch anders auszeichnen, aber das wäre die einfachste Variante gewesen.
