### ISSUE TITLE
Artikel-Meta: Darstellungsfehler "Benutzerdefinierte URL"

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#131]
Sollte entweder umbrechen, oder anderweitig gekürzt werden.

![image](https://cloud.githubusercontent.com/assets/3855487/18052594/888dab10-6dfb-11e6-84bf-d642e7574cff.png)

`text-overflow: ellipses;`
http://caniuse.com/#feat=text-overflow

**Comment by tbaddade** [comment]
Dublette https://github.com/yakamara/redaxo_yrewrite/issues/130
