### ISSUE TITLE
Weiterleitungen funktionieren nicht

### ISSUE THREAD

**Issue by bega011** [yakamara/redaxo_yrewrite#134]
Egal ob zu internen Artikeln, Dateien oder externen Artikeln. 
Habe noch keine www-Domain aber http (da in Entwicklungsphase), YRewrite 2.1 und Redaxo 5.2.0. Auch mehrmals die .htaccess gesetzt

**Comment by tbaddade** [comment]
Kann ich bestätigen.

**Comment by gharlan** [comment]
Funktionieren zurzeit leider nur, wenn die Domain mit Schema (http/https) eingetragen wurde.
Und wenn man die Domain entsprechend ändert, muss man leider auch nochmal in alle Weiterleitungen rein, und nochmal auf speichern klicken.

Beides werde ich korrigieren.
