### ISSUE TITLE
Zwei Domains, Gleiche Webseite

### ISSUE THREAD

**Issue by ex-q** [yakamara/redaxo_yrewrite#137]
Scheinbar ist es nicht möglich die gleiche Webseite (gleicher Mountpoint und Startartikel) auf zwei verschiedenen Domains laufen zu lassen. Eine der beiden Angelegten Seiten wird immer automatisch zur Hauptdomain erhoben, alle Links verweisen dann auf diese. Verhalten tritt auf sobald bei zwei angelegten Domains der selbe Mountpoint gewählt wird. (Hinweis: Domain-Weiterleitung ist in diesem Fall nicht erwünscht)

Oder liege ich falsch? Danke!

**Comment by gharlan** [comment]
Du liegst richtig. Kann mir gerade auch nicht wirklich ein Szenario vorstellen, wo das wirklich Sinn macht. Stichwort Duplicate Content und so.

Einzige Möglichkeit (mit yrewrite): Gar keine Domain anlegen. Dann wird jeweils die aktuelle Domain in den URLs behalten.
Nachteil: Damit fallen manche Features in yrewrite weg (zum Beispiel Aliase und Weiterleitungen).

**Comment by ex-q** [comment]
Ah super, das hilft mir jetzt zumindest in diesem Fall, dane!

Sinnvoll wäre eine Funktion aber sicherlich dennoch, use Case wäre z.B.:
_Seite existiert für verschiedene Länder (DE, AT, CH), nur das Impressum und andere Kleinigkeiten unterscheiden sich. Kunden sollen wenn sie beispielsweise in der Schweiz Links weitergeben oder bookmarken immer die Schweizer URL beibehalten_

Mit Deiner Lösung ist das möglich, eventuell weitere im selben Redaxo verwaltete Seiten mit anderem Inhalt wären dann aber nicht mehr abbildbar. Normal verwenden wir immer www.domain.de, www.domain.at etc. als Rootfolder.

Duplicate content würde über canonical urls oder gefixt werden.

**Comment by alexplusde** [comment]
Wäre es da nicht möglich, die Länder über Sprachen (clangs) abzubilden, und im Template REX_ARTICLE[clang=1] auszugeben? und nur in besagten Ausnahmefällen dann den Inhalt der regulären Sprache über REX_ARTICLE[] auszugeben?

**Comment by alexplusde** [comment]
Alternativ könntest du den XOutputFilter verwenden und im Template / Modul Platzhalter definieren, die dann pro Sprache ersetzt werden.
