### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#138]
> AddOn yrewrite konnte aus folgendem Grund nicht installiert werden:
> Das PlugIn yform/manager (Version 2.0) entspricht nicht der geforderten Versionsbedingung ^1.0!

Alle Addons aus via Installer installiert...

**Comment by gseilheimer** [comment]
Fehlerhafte Mindestanforderung in package.yml für _yform/manager_

requires:
    redaxo: '^5.2'
    packages:
        structure: '^2.0'
        yform/manager: '^2.0'

**Comment by alexplusde** [comment]
+1

**Comment by ynamite** [comment]
+1

**Comment by isospin** [comment]
+1

**Comment by phoebusryan** [comment]
+1

**Comment by skerbis** [comment]
+1

**Comment by alexplusde** [comment]
@dergel @gharlan @staabm habt ihr das auf dem Schirm?

**Comment by gharlan** [comment]
Wir haben es auf dem ☂️, und eine neue Version kommt auch demnächst.

**Comment by dergel** [comment]
done
