### ISSUE TITLE
Möglichkeit, die Meta Felder zu erweitern oder zu ersetzen

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yrewrite#140]
Schön wäre es, wenn es eine Möglichkeit gäbe, die Meta-Felder von Yrewrite zu deaktivieren und sie mit Feldern des Meta-Addons zu ersetzen bzw. flexibel Felder hinzufügen zu können, wenn man jetzt eigene Felder einfügen möchte, gibt es Doppelungen im Backend und man muss zwischen zwei Eingabebereichen (Meta- und Yrewrite Felder) hin- und herschalten.

**Comment by skerbis** [comment]
Eigentlich ist es weniger eine yrewerite-Sache sondern eher für das Metadaten-Addon. - denke ich

**Comment by DanielWeitenauer** [comment]
Die SEO-Felder sind momentan fest verdrahtet, um z.B. die Sitemap-Werte erstellen zu können. Um flexibler zu sein, müsste es möglich sein, die Backend-Felder von Yrewrite zu deaktivieren, bzw. auszublenden, damit keine doppelten Felder auftauchen.
Außerdem wäre es nötig, eigene Meta-Felder irgendwie bei Yrewrite anzumelden.

**Comment by skerbis** [comment]
Ich sehe das etwas anders. Das Metainfo-Addon ist aus meiner Sicht das Addon, dass die Seitenleiste liefern sollte in die sich ggf. andere Addons, wie yrewrite reinhängen können. Man legt dann im Metainfo-Addon fest, welche Metas in der Seitenleiste sitzen sollen und welche optional im Reiter liegen sollen. Yrewrite müsste dementsprechend auf das Metainfo-Addon aufbauen.

**Comment by DanielWeitenauer** [comment]
Eigentlich sehen wir es gleich, nur unser Lösungsansatz ist unterschiedlich.

**Comment by DanielWeitenauer** [comment]
Ich habe mal was angelegt: #141

**Comment by skerbis** [comment]
Wäre super, wenn das übernommen wird.

**Comment by thielpeter** [comment]
+1

**Comment by dergel** [comment]
wurde übernommen.. danke :)

**Comment by alexplusde** [comment]
Wie werden diese nun erweitert? @DanielWeitenauer

**Comment by DanielWeitenauer** [comment]
@alexplusde Es ist die denkbar simpelste Variante: in rex_yrewrite_seo sind alle Feldnamen als statische Variable deklariert. Soll ein anderes Feld benutzt werden, weist man einen Namen eines existierenden Metafeldes zu: https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/yrewrite/seo.php#L24-L47
Das sollte vor dem ersten Aufruf geschehen. 
Um die Standard-UI von Yrewrite auszublenden gibt es zwei neue Nutzerrechte und Einstellungen in den Yrewrite-Settings. 
Den Rest muss ich erstmal ausprobieren, der PR ist ja schon fast drei Jahre alt ;)
