### ISSUE TITLE
Hinweis hinzufügen, das bei multiplen Domains eine 404 Seite definiert werden muß

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yrewrite#142]
Wenn mehrere Domains anlegt werden, muß jeweils eine 404 Seite definiert werden, ansonsten arbeitet das Addon nicht korrekt. Es gibt allerdings keinen Hinweis darauf und man fischt unter Umständen länger im trüben...

**Comment by wende60** [comment]
Hatte das gleiche Problem: ohne eine Start oder 404 Seite legt yrewrite keine config.php an, erzeugt aber auch keine Fehlermeldung beim Anlegen der Domain. Die Tabs "Alias" oder "Weiterleitung" zeigen dann immer den Hinweis an, das zuerst eine Domain angelegt werden muss. Das ist sehr verwirrend und fehleranfällig...

**Comment by dergel** [comment]
das ist mittlerweile Pflicht, kann also so nciht mehr passieren
