### ISSUE TITLE
Zusätzliches Feld "Standard-Template"

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#143]
Damit für verschiedene Domains das jeweils richtige Template gewählt wird.

**Comment by skerbis** [comment]
Na ja. Die Domains sind doch meist schon über Kategorien in der Struktur getrennt. Die Templates kann man also bereits auf die Domains einschränken. Oder sehe ich das falsch? (hmmm es sei denn, gleicher Mountpoint bei verschiedenen Sprachen)

**Comment by dergel** [comment]
stimme. Habe nicht daran gedacht
