### ISSUE TITLE
Yrewrite lässt sich nicht installieren

### ISSUE THREAD

**Issue by Kalle01** [yakamara/redaxo_yrewrite#144]
Fehlermeldung:
AddOn yrewrite konnte aus folgendem Grund nicht installiert werden:
Das PlugIn yform/manager (Version 2.0) entspricht nicht der geforderten Versionsbedingung ^1.0-beta1!

Sorry für diese banale Meldung

Gruß Kalle

**Comment by dergel** [comment]
Hi.. und du hast Form aktualisiert ? Weil YRewrite die aktuelle YForm braucht.

**Comment by gharlan** [comment]
Andersrum, er hat ja yform 2.0, er muss yrewrite aktualisieren auf 2.2.1: https://github.com/yakamara/redaxo_yrewrite/commit/772e64ad63bde5c8f286a733f9b58db59184e3b9

**Comment by Kalle01** [comment]
Genau wie Gregor schreibt und auch schon korrigiert hat,
Danke Gruß Kalle
