### ISSUE TITLE
Link zur Website - Domain-Dropdown

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#145]
Wenn mehr als eine Domain über YRewrite verwaltet wird, sollte es die Möglichkeit geben, auch beim Link zur Website im Header diese Websites auszuwählen.+

**Comment by dergel** [comment]
finde ich gut .. auch wenn wir meistens alle domains in die oberste ebene legen und da überblick sowieso da ist ..

**Comment by alexplusde** [comment]
Überblick schon... mir geht's eher darum, dass man auch direkt auf die Startseite klicken kann.

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/69487247-93ed4c00-0e56-11ea-8ff4-abadf22c9d82.png)

Ich habe das core-Fragment entsprechend überschrieben. Wenn nur eine Domain eingerichtet ist, kommt man direkt zur Website, andernfalls öffnet sich ein Bootstrap-Dropdown. Das ist die einfachste Möglichkeit imho, das umzusetzen - für 15+ Domains vielleicht ungeeignet, aber sicher auch nicht der übliche Fall.
