### ISSUE TITLE
Navigation Factory: oberste (Breadcrumb-)Ebene verkehrt

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#147]
Szenario:
YRewrite ist aktiviert, Kategorien-Struktur:
```
root
-domain1.tld
  - Home
  - Cat 2 
  - Cat 3
-domain2.tld
  - Home
  - Cat 2
  - Cat 3
```

d.h. mount_id und home_id der Domain liegen nicht in derselben Kategorie, sondern home liegt unterhalb des Mountpoints. Dadurch verlinkt die 1. Breadcrumb-Ebene auf `domain2.tld/home/` statt auf `domain2.tld/` und auch die Haupt-Navigation gibt den kompletten Baum ab root aus.

**Comment by dergel** [comment]
ist das immer noch so ? ..

**Comment by alexplusde** [comment]
Ja.

**Comment by tbaddade** [comment]
Der Startartikel der Domain in YRewrite liegt auch auf den Home Artikeln?

**Comment by alexplusde** [comment]
Der Startartikel ist eine Kategorie unterhalb des Mountpoints.

**Comment by alexplusde** [comment]
**Ausgabe ist**

```
<ul class="rex-breadcrumb">
<li class="rex-lvl1"><a href="/mountpoint-artikel/">Mountpoint-Artikel</a></li>
<li class="rex-lvl2"><a href="/kategorie1/">Kategorie1</a></li>
<li class="rex-lvl3"><a href="/kategorie1/subkategorie1/">Subkategorie1</a></li>
</ul>
```

**Ausgabe soll**

```
<ul class="rex-breadcrumb">
<li class="rex-lvl1"><a href="/">Home-Artikel</a></li>
<li class="rex-lvl2"><a href="/kategorie1/">Kategorie1</a></li>
<li class="rex-lvl3"><a href="/kategorie1/subkategorie1/">Subkategorie1</a></li>
</ul>
```

**Comment by tbaddade** [comment]
Könntest du deinen Code zum ausgeben der Breadcrumb posten?

**Comment by alexplusde** [comment]
```


                            <?php
                            $breadcrumbs = rex_navigation::factory();
                            echo $breadcrumbs->showBreadcrumb(false, false, 67);
                          ?>
                        </div>
```

**Comment by tbaddade** [comment]
Für mich liegt der Fehler im Core, da die Breadcrumb Methode die Filter und Callbacks ignoriert.

Laut Doku müsste das funktionieren

```
$breadcrumb = rex_navigation::factory();
$breadcrumb->addFilter('id', rex_yrewrite::getCurrentDomain()->getMountId(), '!=', '');
echo $breadcrumb->getBreadcrumb(false, false, 67);
```

**Comment by alexplusde** [comment]
Ich habe es soeben ausprobiert. Es funktioniert nicht.

**Comment by tbaddade** [comment]
Kann auch nicht 

> da die Breadcrumb Methode die Filter und Callbacks ignoriert.

**Comment by gharlan** [comment]
Trotzdem würde damit aber doch auch nicht Alex gewünschtes Verhalten eintreten, das an Stelle des Mountpoints der Home-Artikel erscheinen würde, oder?

**Comment by alexplusde** [comment]
Korrekt.

**Comment by alxndr-w** [comment]
Ich habe das für mich bereits selbst anders gelöst.
