### ISSUE TITLE
Custom URL einschränken

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yrewrite#148]
Ich würde anregen, die Custom URLs über ein User-Recht bzw. Rollen_recht einschränkbar zu machen. Ein "normaler" Redakteur sollte m.M.n. keine Custom-URLs eingeben dürfen, ein Admin oder ein "besserer" Redakteur schon. 

Ausserdem würde ich das Feld unter die SEO Daten schieben.
Aktualisierungshäufigkeit ist m.M.n. obsolet.

**Comment by gharlan** [comment]
Die Permission dafür gibt es inzwischen.
