### ISSUE TITLE
Neben %T und %SN ein %L

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yrewrite#150]
Habe hier gesehen, dass es nur die beiden Möglichkeiten Titel und Servername gibt. https://github.com/yakamara/redaxo_yrewrite/blob/5195f48a0d5a607782455dfe4d92e257e92fc97d/lib/seo.php#L22
Wenn ich mehrere unabhängige Domains mit unabhängigem Content bediene, wäre toll, wenn ich einen "lokalen" Servernamen definieren könnte. Entweder gespeist aus dem Namen des SiteStartarticle oder aber definiert in den Domaineinstellungen. #

**Comment by alexplusde** [comment]
Nimm doch String Table / XOutputFilter und schreibe einen Platzhalter rein. Oder direkt reinschreiben, wenn's nicht mehrsprachig ist.

**Comment by Himra** [comment]
Hab das selbe Problem
https://github.com/yakamara/redaxo_yrewrite/blob/5195f48a0d5a607782455dfe4d92e257e92fc97d/lib/seo.php#L78-L80

und es wie folgt gelöst:

```php
$title = $title_scheme;
$title = str_replace('%T', $ytitle, $title);
$title = str_replace('%SN', rex::getServerName(), $title);
// Name des Mountpoint der Domain
$title = str_replace('%MN', rex_article::get(rex_yrewrite::getCurrentDomain()->getMountId())->getName(), $title);
```
Vielleicht gibt es ja noch eine einfachere Variante:

Was mir noch fehlt ist das er mir beim Startartikel das %T nicht mehr mit anzeigt denn %T %MN sind beim Startartikel gleich
Vielleicht kann man dies ja in die seo.php noch einfügen.

Gruß und Dank
Himra

**Comment by Himra** [comment]
Jetzt mit Startartikel Kürzung

```php
// Name des Mountpoint der Domain
$title = str_replace('%MN', rex_article::get(rex_yrewrite::getCurrentDomain()->getMountId())->getName(), $title);
if ($this->article->getValue('id') == rex_yrewrite::getCurrentDomain()->getMountId()) {
	$title = rex_article::get(rex_yrewrite::getCurrentDomain()->getMountId())->getName();
}
```
nicht schön aber für mich funktioniert´s

Gruß und Dank
Himra

**Comment by alexplusde** [comment]
Was heißt Startartikel-Kürzung?

**Comment by Himra** [comment]
Wenn man den Startartikel einer Domain aufruft und es so erweitert wie ich oben beschrieben hab, dann steht bei %T und %MN das gleiche. Das sieht irgenwie doof aus.
Deshalb suche ich mir heraus wenn der Startartikel kommt dann streiche ich das %T und ein eventuelles trennzeichen un kürze somit den Title des Startartikels

Gruß und Dank
Himra

**Comment by Himra** [comment]
eine kleine Verbesserung aber noch nicht perfekt

```php
$title = $title_scheme;
$title = str_replace('%T', $ytitle, $title);
$title = str_replace('%SN', rex::getServerName(), $title);
if ($this->article->getValue('name') == $mp_name and preg_match ('/%MN/',$title)) {
	$title = $mp_name;
}
$title = str_replace('%MN', $mp_name, $title);
```

**Comment by dergel** [comment]
wollt ihr das bei den Tricks ablegen ? https://github.com/FriendsOfREDAXO/tricks
innerhalb von yrewrite sehe ich das nicht.
