### ISSUE TITLE
yrewrite_info_tipps_text - rex::getServer()

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yrewrite#151]
In den Tipps fehlt noch, wie man die Infos aus

rex::getServer()
rex::getServerName()

in den Templates im Kontext von yrewrite dennoch erhält. Oder wäre es nicht möglich, die in yRewrite gemachten Einstellungen zur Base-URL bzw Server-Name stattdessen zurückzugeben? Bzw könnte im Hilfetext evtl ein alternativer Ansatz untergebracht werden.

**Comment by cukabeka** [comment]
Übrigens auch für Yform wäre das sehr nützlich. Wenn ich z.B. ###REX_SERVER### in Email-Templates verwenden kann und dabei die jeweils korrekte yrewrite-Angabe bekomme, erspart das viel Arbeit. 

Falls das nicht global passieren soll, wäre eine entsprechende Einstellung (was soll yrewrite für getServer() etc einsetzen?) dufte!

**Comment by dergel** [comment]
Versteh ich das richtig ? .. MIt den jetzt vorhandenen getFullUrlByArticleId( Methoden und den Varianten davon sollte zu lösen sein ? .. Ansonsten kann man nun auch in den E-Mail Templates PHP verwenden, d.h. kann man im Notfall auch entsprechende Dinge nutzen.
