### ISSUE TITLE
Meta-Description als Plaintext ausgeben

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#152]
Hin und wieder gibt es Fälle, in denen wir HTML (Links, Absätze, Fett-Schnitt) in der Artikel-Beschreibung verwenden - insb. bei Seiten, die in Kombination mit dem URL-Addon generiert werden. Hier wäre es gut, wenn YRewrite vorsorglich die Titel und Beschreibungsfelder mit plaintext, strip_tags o.ä. behandelt.

@tbaddade ich wollte das Issue erst bei dir aufmachen, sehe aber, dass es eig. YRewrite insgesamt betrifft. Evtl. betrifft es auch beide?

**Comment by dergel** [comment]
klingt sinnvoll.. kommt rein.
