### ISSUE TITLE
Pathlist-Cache löschen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#158]
Wenn man bspw. Änderungen in Adminer an einer Tabelle mit URLs macht, werden diese nicht automatisch übernommen.

Siehe auch:
https://github.com/redaxo/redaxo/issues/1071#issuecomment-282696474

ping @tbaddade wegen des URL-Addons

**Comment by dergel** [comment]
das ist leider so.. bei allen cache gesichten. die können sich erst refreshen wenn eine art event ausgelöst wurde, und dazu zählt die eigenständige datenbankänderung nicht.

wenn das individuelle cache löschen im core ist, wird das auch von yrewrite eingebaut.

**Comment by alexplusde** [comment]
Stimmt. Sollte auf jeden Fall zumindest erklärt werden. Kümmere mich darum.
