### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yrewrite#159]
Hier eine vollständige nginx config für YRewrite. Schützt auch gleich /redaxo/src, /redaxo/cache und /redaxo/addons 

Es werden auch gleich Dateien, die mit einem . beginnen vorm Aufruf geschützt.

Ich denke, das könnte man eingeklappt irgendwo in der Setup-Page einbauen, nicht jeder hat Apache und nginx ist mittlerweile sehr verbreitet. (32% Marktanteil)

```ruby
		charset utf-8;

		# OPTIONAL von HTTP auf HTTPS weiterleiten, Kommentare entfernen falls nötig
		#if ($https !~ "on"){
		#	set $rule_8 1;
		#}
		#if ($rule_8 = "1"){
		#	rewrite ^(.*)$ https://$server_name$request_uri permanent;
		#}

		rewrite ^/sitemap\.xml$ /index.php?rex_yrewrite_func=sitemap last;
		rewrite ^/robots\.txt$ /index.php?rex_yrewrite_func=robots last;
		rewrite ^/download[s]?/([^/]*) /index.php?download_utility=download&file=$1 last;
		rewrite ^/media[0-9]*/imagetypes/([^/]*)/([^/]*) /index.php?rex_media_type=$1&rex_media_file=$2&$args ;
		rewrite ^/images/([^/]*)/([^/]*) /index.php?rex_media_type=$1&rex_media_file=$2&$args ;
		rewrite ^/imagetypes/([^/]*)/([^/]*) /index.php?rex_media_type=$1&rex_media_file=$2 ;
		if ($uri !~ "^redaxo/.*"){
			set $rule_6 4$rule_6;
		}
		if ($uri !~ "^media/.*"){
			set $rule_6 5$rule_6;
		}

		if (!-e $request_filename){
			rewrite "^(.*)$" /index.php?$query_string last;
		}

		#!!! WICHTIG !!! Zugriff auf alle Dateien mit . verbieten (könnte ja eine alte .htpasswd enthalten sein)
		location ~ /\. { deny  all; }

		# Zugriff auf diese Verzeichnisse verbieten
		location ^~ /redaxo/src { deny  all; }
		location ^~ /redaxo/data { deny  all; }
		location ^~ /redaxo/bin { deny  all; }
		location ^~ /redaxo/cache { deny  all; }
```

**Comment by Hirbod** [comment]
```ruby
location ~ /\.(ttf|eot|woff|woff2)$ {
	add_header Access-Control-Allow-Origin *;
	expires 604800s;
}
```

Könnte auch noch praktisch sein.

**Comment by Hirbod** [comment]
Hinweis: Ich hab das nicht in einer Multi-Domain Umgebung getestet, sondern nur für eine Single-Site. Damit funktioniert obige config fehlerfrei.

**Comment by fietstouring** [comment]
# REWRITE RULE FOR JS/CSS VERSIONING aus der YRewrite htaccess
ist da nicht dabei, oder?

**Comment by Hirbod** [comment]
Wenn du mir das aus der htaccess kopierst, kann ich es vermutlich für dich konvertieren

**Comment by fietstouring** [comment]
`RewriteRule ^(.*)\.\d{10}\.(css|js)$ %{ENV:BASE}/$1.$2 [L]`

**Comment by Hirbod** [comment]
Ungetestet:

rewrite ^/(.*)\.\d{10}\.(css|js)$ /$base$1.$2 last;

**Comment by fietstouring** [comment]
Hast Du Erfahrung mit Plesk? Dort wird mir eine Fehlermeldung bez. der Teile mit geschwungenen Klammern ausgegeben in dem Feld "Additional headers"...

**Comment by Hirbod** [comment]
Die Config ist gerade für Plesk gemacht.

**Comment by fietstouring** [comment]
Teste die config gerade lokal in MAMP.
Redaxo sagt **"The folder redaxo/bin is insecure. Please protect this folder."**

**Comment by Hirbod** [comment]
location ^~ /redaxo/bin { deny  all; }

das muss dazu. Die config ist alt, da gab es das bin verzeichnis noch nicht

**Comment by Hirbod** [comment]
Musst die Cookies danach noch leeren, weil der Wert der Sicherung dort gespeichert wird.

**Comment by fietstouring** [comment]
2018/06/06 15:56:05 [emerg] 44743#0: unknown "base" variable

**Comment by fietstouring** [comment]
also einfach so gehts:
`rewrite "^/(.*)\.\d{10}\.(css|js)$" /$1.$2 last;`

**Comment by tbaddade** [comment]
> REWRITE RULE FOR JS/CSS VERSIONING aus der YRewrite htaccess

> RewriteRule ^(.*)\.\d{10}\.(css|js)$ %{ENV:BASE}/$1.$2 [L]

Diese Zeile gibt es nicht in yrewrite. Die müsste woanders herkommen

**Comment by fietstouring** [comment]
das stimmt... sorry ;-)
ist für Url-fingerprinting/css-versioning

**Comment by dergel** [comment]
jemand da, der das in die DOku schreiben kann ?

**Comment by Hirbod** [comment]
Achtung noch, bei manchen Servern (je nach Setting) mit dem Einsatz von "Let's Encrypt" kann die Zeile

`location ~ /\. { deny  all; }`

Probleme machen, da Let's Encrypt eine ".well-known" virtuell anlegt. Hier bitte beobachten, falls plötzlich kein Zertifikat angelegt werden kann (betrifft nur ISP-Systeme, wie z.B Plesk, wo das im Doc-Root generiert wird)

**Comment by gharlan** [comment]
Ist seit einer Weile in der Doku enthalten.
