### ISSUE TITLE
Den automatisch generierten SEO-Titel mittels placeholder-Attribut anzeigen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#160]
Damit der Kunde weiß, was ausgegeben wird, wenn dieses Feld leer bleibt.

![image](https://cloud.githubusercontent.com/assets/3855487/23462400/fe9842d4-fe8d-11e6-8ac8-c747ffa1d67e.png)

**Comment by dergel** [comment]
sehr coole idee ..

**Comment by alexplusde** [comment]
Danke!
