### ISSUE TITLE
Weiterleitung - wird nicht auf internen Artikel umgeleitet

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#162]
Wollte das Modul "Weiterleitung" sparen und eine Kategorie auf die unterste Kindkategorie weiterleiten. Klappt nur nicht.

| **Daten zum testen** | |
| - | - |
| aufgerufene Url: | `kategorie` - muss ohne Slash eingetragen werden | 
| Art der Weiterleitung: | `303` |
| Weiterleitung an: | `article` |
| Artikel: | irgendeinen Artikel |

**Was passiert:**
Wenn man jetzt die Kategorie in der Navi anklickt, gelangt man direkt zum Artikel. Es findet keine Weiterleitung statt. Grund wird sein, dass die Url mit `/`endet, aber die obige Weiterleitung ohne Slash eingetragen ist.

**Comment by gharlan** [comment]
Die Weiterleitungen sind nun mal nicht dafür gedacht. 
Sie sind gedacht, um **nicht existente** URLs auf existente umzuleiten.
Sie greifen daher auch als letztes. Also wenn zu einer URL kein definiertes Verhalten gefunden wurde, wir zum Schluss noch geschaut, ob es denn eine Weiterleitung dafür gibt.

Sehe das daher nicht als Bug an. Sondern einfach nur als fehlendes Feature #124.
