### ISSUE TITLE
Nicht admin redaxo user Startartikel der Domain edtieren lassen können

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yrewrite#163]
wär super wenn man user die möglichkeit geben könnte selbst den Startartikel der domain ändern zu können. hatte schon öfter webseiten wo sich immer wiedermal der starseitenartikel ändert - bei einer aktuellen seite sogar monatlich.

**Comment by tbaddade** [comment]
Der Artikel ist doch weiterhin editierbar.

**Comment by steri-rex** [comment]
ja das stimmt schon aber es geht nicht um den inhalt des startartikels an sich - sondern wirklich dass ein andere artikel als starseite definiert werden können soll

**Comment by dergel** [comment]
ist nicht so gewollt. das soll dann ein Admin machen. Ein Redakteur sollte ein solches Recht nicht bekommen und als Option sehe ich das auch nicht ..
