### ISSUE TITLE
Systemlog voller Notices

### ISSUE THREAD

**Issue by Hirbod** [yakamara/redaxo_yrewrite#164]
<img width="1126" alt="bildschirmfoto 2017-03-19 um 14 38 58" src="https://cloud.githubusercontent.com/assets/504909/24081331/d8a56638-0cb1-11e7-8e94-d05589a27187.png">

Kommt auch, wenn ich den Cache lösche, direkt danach.

**Comment by gharlan** [comment]
Ist das nicht die Notice aus #156?

**Comment by Hirbod** [comment]
Vermutlich ein und derselbe Fehler. Ich bekomme es jedoch auch im Backend, wenn ich z.B. den Cache lösche oder eine Rootkategorie entferne, nicht nur in der Sitemap.xml
