### ISSUE TITLE
 Beim kopieren eines Artikels wird das PathFile nicht neu generiert

### ISSUE THREAD

**Issue by palber** [yakamara/redaxo_yrewrite#167]
Sehr ähnliche Problematik wie Issue #57 

Allerdings wird dies ohne zusätzliche ExtensionPoints im Core in den Methoden
rex_article_service::copyArticle
rex_article_service::moveArticle
nicht zu lösen sein.

Bin offen für andere Lösungsvorschläge. Mache dann gerne einen PR

**Comment by skerbis** [comment]
https://redaxo.org/forum/viewtopic.php?f=43&t=22127&p=123030#p123030

**Comment by tbaddade** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/190
