### ISSUE TITLE
Chinesische oder russische URLs nicht möglich

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#170]
Folgenden Webseite möchte ich nach Redaxo 5 umziehen:
https://www.kaltenbach.com/zh/%E4%BA%A7%E5%93%81/%E8%AE%BE%E5%A4%87/%E5%96%B7%E6%BC%86%E8%AE%BE%E5%A4%87/
Die URL enthält Chinesische Zeichen. Die Russische Übersetzung ist im Gang. Wenn aber nur diese Zeichen in der URL sind wird aus obiger URL durch YRewrite foglende: https://www.kaltenbach.com/zh////.

**Comment by gharlan** [comment]
yrewrite kann es von Haus aus zwar noch nicht, aber es ist sehr einfach über eine eigene Schema-Klasse möglich, wo man die Normalisierung der Url-Parts für die entsprechenden Sprachen anpasst.
Haben wir hier zum Beispiel im Einsatz: https://www.zeppelin-systems.com/zh-cn/泽普林固体物料技术/关于我们.html

Im Projekt/Theme-Addon diese Klasse anlegen:
```
<?php

class project_yrewrite_scheme extends rex_yrewrite_scheme
{
    public function normalize($string, $clang = 1)
    {
        if (13 == $clang) {
            // hier ggf. eigene Anpassungen am String
            // $string = str_replace(...);
            // oder ansonsten halt einfach so zurückgeben, wie er ist

            return $string;
        }

        return parent::normalize($string);
    }
}
```

Und dann in der boot.php registrieren:
```php
rex_yrewrite::setScheme(new project_yrewrite_scheme());
```

**Comment by TobiasKrais** [comment]
Danke für den Workaround. Wäre toll wenn das künftig konfigurierbar wäre wie es in SEO42 war.

**Comment by TobiasKrais** [comment]
Im D2U Helper Addon gibt es ab Version 1.2.5 eine Einstellungsmöglichkeit um für jede Sprache zwischen dem Standard Schema von YRewrite und einem URL Encode Schema zu wechseln.

**Comment by dergel** [comment]
das wird nicht konfigurierbar sein, kann aber gerne in die Doku aufgenommen werden. haben ja nun eine Dokuseite. @alexplusde @skerbis was für Euch ? ;) ..

**Comment by alexplusde** [comment]
Ich kanns nicht dokumentieren, ich brauche mehr Praxis-Beispiele und muss es mir genauer anschauen. Z.B., wie man virtuelle Kategorien erzeugt oder umgekehrt, Kategorie-Artikel in den root packt.

**Comment by dergel** [comment]
ok .. mir ging es vor allem um das Beispiel wenn man UTF-8 URLs verwenden will. dieses Schema hätte ich in der Doku einfach als Beispiel unten dran gehängt.. wenn die doku noch wächst, dann baue ich es vielleicht auch gleich so um wie bei yform..

**Comment by alexplusde** [comment]
@dergel Doku-Ausbau: ich denke, das wird passieren. 
Ich werde auch auf Slack dazu animieren, weitere Beispiele anderer zur Verfügung zu stellen. Der @aeberhard hat die Doku von YForm ja als eigenes Plugin zu FOR migriert und meines Wissens ein wenig optimiert.

**Comment by TobiasKrais** [comment]
Schaut euch den Commit von mir oben an: https://github.com/TobiasKrais/d2u_helper/commit/a9a0272e07cc6634015d61140150fc0ba2fdb412. Dort findet ihr Beispielcode.

Im D2U Helper Addon kann in den Einstellungen das URL Schema pro Sprache eingestellt werden und so auch das URL Encoding.

@dergel: du schreibst, dass das nicht konfigurierbar ist. Wie mein D2U Helper Addon zeigt, ist es konfigurierbar. Wenn du dir das SEO42 Addon in Redaxo 4 anschaust: dort wurde eine Konfigurationsmöglichkeit in den Einstellungen in Perfektion angeboten. So etwas würde ich mir direkt in den YRewrite Einstellungen wünschen.

**Comment by alexplusde** [comment]
@TobiasKrais kannst du nen Screenshot mitschicken, wie das aussieht? Das macht's konkreter.

**Comment by TobiasKrais** [comment]
Gerne. Hier erst mal ein Screenshot wie es im SEO42 gelöst war:
![seo42](https://user-images.githubusercontent.com/4131072/35481464-4c3c35ee-0424-11e8-93b9-3616dd7c403d.png)

Dann hier wie ich das im D2U Helper Addon gelöst habe:
![d2u helper](https://user-images.githubusercontent.com/4131072/35481465-59772868-0424-11e8-9059-82780d677f39.png)

**Comment by dergel** [comment]
haben wir ja mittlerweile dokumentiert
