### ISSUE TITLE
Endlosschleife bei Verwendung mit YCOM

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yrewrite#171]
nach dem update von ycom (2.0) und yform (yform 2.2) auf die aktuellste version passiert folgender endlos-redirect:

https://domain.de/loginbereich/?rex_ycom_auth_ref=%2Floginbereich%2F%3Frex_ycom_auth_ref%3D%25252Floginbereich%25252F%25253Frex_ycom_auth_ref%25253D%252525252Floginbereich%252525252F%252525253Frex_ycom_auth_ref%252525253D%2525252525252Floginbereich%2525252525252F%2525252525253Frex_ycom_auth_ref%2525252525253D%25252525252525252Floginbereich%25252525252525252F%25252525252525253Frex_ycom_auth_ref%25252525252525253D%252525252525252525252Floginbereich%252525252525252525252F%252525252525252525253Frex_ycom_auth_ref%252525252525252525253D%2525252525252525252525252Floginbereich%2525252525252525252525252F%2525252525252525252525253Frex_ycom_auth_ref%2525252525252525252525253D%25252525252525252525252525252Floginbereich%25252525252525252525252525252F%25252525252525252525252525253Frex_ycom_auth_ref%25252525252525252525252525253D%252525252525252525252525252525252Floginbereich%252525252525252525252525252525252F%252525252525252525252525252525253Frex_ycom_auth_ref%252525252525252525252525252525253D%2525252525252525252525252525252525252Floginbereich%2525252525252525252525252525252525252F%2525252525252525252525252525252525253Frex_ycom_auth_ref%2525252525252525252525252525252525253D%25252525252525252525252525252525252525252Floginbereich%25252525252525252525252525252525252525252F%25252525252525252525252525252525252525253Frex_ycom_auth_ref%25252525252525252525252525252525252525253D%252525252525252525252525252525252525252525252Floginbereich%252525252525252525252525252525252525252525252F%252525252525252525252525252525252525252525253Frex_ycom_auth_ref%252525252525252525252525252525252525252525253D%2525252525252525252525252525252525252525252525252Floginbereich%2525252525252525252525252525252525252525252525252F%2525252525252525252525252525252525252525252525253Frex_ycom_auth_ref%2525252525252525252525252525252525252525252525253D%25252525252525252525252525252525252525252525252525252Floginbereich%25252525252525252525252525252525252525252525252525252F%252525252525252525252525252525252525252525

yrewrite: 2.2.1

Sobald ein Mountpoint für eine Domain gesetzt wird, der nicht "root" ist, kommt die Endlosschleife. Mit YCOM 1 lief noch alles rund.
Diskussion dazu auch auf Slack: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1493821548178952?thread_ts=1493819269.331481&cid=C1BAXLN2F

**Comment by cukabeka** [comment]
ich konnte das problem nach etlichen versuchen übrigens in den griff bekommen, indem ich die userrechte für die seite angepasst habe. also ganz einfach auf der rechten seite alle gruppen entfernt und zugriff für alle ermöglicht..

**Comment by dergel** [comment]
ich frage mal bloed.. ist das auch mit den beta versionen so ? ycom 2.1b und yform 2.3b ?
