### ISSUE TITLE
Beim Anlegen eines Artikels Fatal error in  rex_yrewrite_scheme::appendCategory()

### ISSUE THREAD

**Issue by orbdex** [yakamara/redaxo_yrewrite#172]
Hallo,

in unserer Umgebung (Redaxo 5.3.0 - PHP 5.6.30) bekomme ich komischerweise in einer Kategorie beim Anlegen eines neuen Artikels eine Fehlermeldung durch das yrewrite (2.2.1) AddOn. Ich versuche dabei den Artikel auf der 4. Ebene anzulegen.

Die Fehlermeldung lautet:
Argument 2 passed to rex_yrewrite_scheme::appendCategory() must be an instance of rex_category, null given, called in [...]redaxo\src\addons\yrewrite\lib\yrewrite.php on line 492

System-Log meldet:
redaxo\src\addons\yrewrite\lib\scheme.php LIne 55

Der Artikel wird jedoch sauber angelegt. Template-Zuweisung, etc. sind soweit auch sauber. 

Eine Idee was das sein kann? Bekomme es nicht an anderer Stelle reproduziert gerade.
Danke für jeden Tipp...!

Gruß

**Comment by gharlan** [comment]
Da das Ticket recht alt ist (und somit auch die yrewrite-Version, auf die es sich bezieht), schließe ich es jetzt einfach mal. Falls das Problem doch aktuell noch besteht, gerne nochmal melden.
