### ISSUE TITLE
Benutzerdefinierte URL mit Hashtag

### ISSUE THREAD

**Issue by gegerino** [yakamara/redaxo_yrewrite#176]
Hallo,

kann ich Benutzerdefinierte URLs auch mit Hashtags anlegen?
Habe folgendes Szenario:
Ich habe ein Modul, welches mir Atrikel in Tabs einbindet.
Jetzt würde ich gerne die einzelnen Tabs, welche durch Hashtags aufrufbar sind in die Sitemap.xml integrieren, dazu müsste ich den entsprechenden Artikeln ja eine benutzerdefinerte URL mit Hasttag verpassen. (www.domain.de/menuepunkt/#tab).
Hier bekomme ich aber die Fehlermeldung: Die URL ist nicht korrekt. Schreibweise beachten. Nur "a-z/0-9 -", kein / am Anfang und am Ende.

Wie kann ich das Problem denn lösen?

Vielen Dank für eure Hilfe.

Gruß Gegerino

**Comment by dergel** [comment]
nein, das ist nicht möglich. die urls werden den artikeln zugewiesen und die sitemap gibt dann ausschliesslich diese urls aus. Diverse Anker Varianten sollten, soweit ich weiss, sowieso nicht in die sitemap mit rein, da diese ausschliesslich URL enthalten soll.
