### ISSUE TITLE
sitemap.xml - XML-Verarbeitungsfehler

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yrewrite#177]
Im Browser kommt bei Aufruf der sitemap.xml diese Fehlermeldung
```
XML-Verarbeitungsfehler: XML- oder Text-Deklaration nicht am Beginn der Entität
Adresse: https://www.domain.de/sitemap.xml
Zeile Nr. 2, Spalte 1:<?xml version="1.0" encoding="UTF-8"?>
^
```
der code der xml sieht aber eigentlich gut aus:
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://www.domain.de/</loc>
<lastmod>2017-06-12T10:45:09+02:00</lastmod>
<changefreq>weekly</changefreq>
<priority>1.0</priority>
</url>

<url>
<loc>https://www.domain.de/aktuell/</loc>
<lastmod>2017-05-18T16:48:02+02:00</lastmod>
<changefreq>weekly</changefreq>
<priority>1.0</priority>
</url>
```
könnte das problem die erste leere zeile sein?
wo könnte ich diese entfernen?

**Comment by staabm** [comment]
vorm <?xml darf keine leerzeile sein.

die könnte durch jedes template/modul/php-klasse/includete-php-datei kommen die vorm `<?` am anfang nach dem `?>`  am Ende ne leerzeile/nen leerzeichen enthält

**Comment by dergel** [comment]
das wird wohl so sein, kann den fehler nicht reproduzieren
