### ISSUE TITLE
Multidomainumgebung: Handling von Artikeln in Domains über die man nicht in Redaxo eingeloggt ist unpraktikabel

### ISSUE THREAD

**Issue by alexwenz** [yakamara/redaxo_yrewrite#179]
Aus Slack kopiert:
.. aktuell habe ich eine Seite mit mehreren Domains, die über yrewrite laufen. Die Redakteure loggen sich über eine "Hauptdomain" ein. Wenn sie nun Artikel bearbeiten, die nicht zur "Hauptdomain" gehören, können Sie offline gestellte Artikel nicht über "Artikel anzeigen" prüfen und die URLs bei geänderten Artikelnamen werden nicht neu umschrieben ... Es ist mir bewusst, dass das Frontend nur auf die Login-Domain reagiert. So richtig praktikabel ist es aber nicht, oder?

**Comment by alxndr-w** [comment]
Das Problem wurde mitunter durch die Addons `maintenance` und `accessdenied` entschärft. https://github.com/FriendsOfREDAXO/accessdenied 

@alexwenz genügt dir das als Lösung mittlerweile?

**Comment by gharlan** [comment]
Zu der Thematik gibt es hier eine laufende Diskussion, deshalb schließe ich hier: #226
