### ISSUE TITLE
Andere Navigation für andere Domain? Redaxo5

### ISSUE THREAD

**Issue by simonsinus** [yakamara/redaxo_yrewrite#181]
Hallo möchte eine Multidomain Seite mit zwei verschiedenen Seiten erstellen.
Ich kann die Navigation für die zweite (2.seite.de) , die andere erstellen:

```
<?php 

$nav = rex_navigation::factory();
$nav->show(30, 1, TRUE, TRUE);

?>
```

Jedoch beinhaltet diese Navigation jetzt die Domain, der ersten (1.seite.de) Seite.
Kann man da was tun?

**Comment by skerbis** [comment]
@simonsinus wie ist Deine Struktur aufgebaut? ... Ist die 2. Seite eine Kategorie der 1. Seite? 
Wenn ja solltest du diese in der 1. Seite offline stellen. 
Die ideale Lösung ist, wenn du in der Struktur die Seiten innerhalb einer eigenen Hauptkategorie anlegst. Jede Domain muss dann auch in rewrite angelegt werden. 


**Etwa so:** 

- Domain1
  - Unterseiten .. 
- Domain 2 
 - Unterseiten

so kommen sich die Domains nicht in die Quere

**Comment by simonsinus** [comment]
OK, das habe ich jetzt so gemacht, die Domains werden erfolgreich unterschieden,
wie bekomme ich dann noch die Unterordner in der URL weg?

www.webseite1.de/**webseite1**/home/
www.webseite2.de/**webseite2**/home/

**Comment by tbaddade** [comment]
@simonsinus Du musst den Mountpoint in YRewrite für jede Domain noch richtig setzen
