### ISSUE TITLE
"Startsprache nicht in URL" - Checkbox hat keine Auswirkung

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#182]
Egal ob ich es anhake, oder nicht.

Redaxo 5.3, aktuelles yrewrite, Installation in Unterordner.

**Comment by dergel** [comment]
hmmm sehr komisch .. kann den fehler nachvollziehen aber ist nicht so leicht zu finden. wenn du den cache nochmal löscht, passt es..

**Comment by dergel** [comment]
ich habe alles mögliche getestet und kann den Fehler nicht mehr reproduzieren. ich schätze durch die getätigten Änderungen gibt es dieses Problem nicht mehr. Wenn doch - gerne nochmal öffnen

**Comment by alexplusde** [comment]
Ok
