### ISSUE TITLE
Mountpoint-Kategorien und 404

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#183]
Wenn ich eine Domain `domain.de` habe und eine Kategorie `domain.de` in der Struktur, dann kann ich 
`domain.de/domainde/` aufrufen, statt dass ich zum Fehlerartikel geleitet werde.

**Comment by alexplusde** [comment]
Dies ist dann der Fall, wenn die Startseite sich in einer Kategorie unterhalb des Mountpoints befindet, die Fehlerseite jedoch parallel zum Mount-Artikel liegt.

**Comment by alexplusde** [comment]
Ich bitte um einen Fix, denn YRewrite lässt dadurch den Aufruf eines Artikels zu, der nicht zulässig ist. Ich weiß leider nicht, wo ich ansetzen muss, sonst würde ich es selbst machen.

Die Prüfung müsste aussehen:
* Wenn der Mount-Artikel aufgerufen wird und 
* der Mount-Artikel nicht der Start-Artikel der Domain ist,
* dann auf den Start-Artikel der Domain weiterleiten...

**Comment by tbaddade** [comment]
Wie kommt man denn im Frontend zu dieser Url `domain.de/domainde/` ?

> Dies ist dann der Fall, wenn die Startseite sich in einer Kategorie unterhalb des Mountpoints befindet, die Fehlerseite jedoch parallel zum Mount-Artikel liegt.

Das macht nichts. Die Url hieße dann `domain.de/fehlerseite/` und nicht `domain.de/domainde/fehlerseite/`

**Comment by alexplusde** [comment]
> Das macht nichts. Die Url hieße dann domain.de/fehlerseite/ und nicht domain.de/domainde/fehlerseite/

Darum geht es nicht. Wir haben bspw. die Seite im Google-Index gefunden und in nicht näher nachzuvollziehenden Fällen

**Comment by tbaddade** [comment]
Das könnte durch die Sitemap passiert sein. Bevor die Seite online geht, könntest du im Mountpointartikel in der Sidebar das Feld "Indizierung und Sitemap" anpassen.

Da der Artikel bereits im Index ist, würde ich jetzt eine Weiterleitung in yrewrite selbst einrichten.
