### ISSUE TITLE
Schemes in Hilfe aufnehmen?

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#184]
Da immer wieder Fragen zu den Schemes auftauchen (Forum, Slack, Issues), 
habe ich hier mal was gesammelt:
https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_yrewrite_url_schemes.md

**Comment by dergel** [comment]
ich habe das einfachmal mit reingenommen, wenn ok. @alexplusde ich hoffe es ist ok, wenn es unterhalb deiner doku mit drin ist. Freue mich über weitere Anpassungen in der Doku und vielen Dank schon...

**Comment by alexplusde** [comment]
Na klar :) 

Wäre glücklich, wenn der Wulst an Text über das Doku-Plugin dann in kleinere Einheiten aufgelöst würde. Vielleicht ziehst du es ja doch noch in Erwägung.

**Comment by skerbis** [comment]
Cool, dann der Trick ja mit fern nächsten Release raus. Wieder etwas mehr Ordnung :)

**Comment by skerbis** [comment]
Eigentlich können alle Tricks da rein, gerade die Nginx Direktiven wären ganz gut: https://github.com/FriendsOfREDAXO/tricks/blob/master/addons_yrewrite_nginx.md
