### ISSUE TITLE
individuelle Parent-URL kein Standard in Child-Elementen

### ISSUE THREAD

**Issue by dpf-dd** [yakamara/redaxo_yrewrite#185]
Ich habe folgendes Problem mit der aktuellen yrewrite-Version im Redaxo 5.3 (leicht reproduzierbar)...

Kategorie "Shop und Verleih", darin 1 Child-Kategorien "Shop", die automatisch generierte URL lautet also:

**/shop-und-verleih/shop/**
=> aus SEO-technischen Gründen manuell editiert in:
**/shop-und-verleih/kaufen/**

Wenn ich jetzt in "Shop" eine Child-Kategorie "Produkt-A" erstelle, dann sollte ja auch eigentlich folgende URL generiert werden:
/shop-und-verleih/**kaufen**/produkt-a/

yrewrite bzw. Redaxo liefert mir aber:
/shop-und-verleih/**shop**/produkt-a/

Düdüm... Ich sehe das als kleinen Bug an und wäre froh, wenn das a) jemanden bestätigen kann und b) es irgendwie zu lösen ist, weil es aus SEO-technischer Sicht in diesem Fall schon wichtig ist, da ich nicht alle "Produkt"-Childs ebenfalls manuell editieren möchte (Wartungsaufwand bei Änderungen zu hoch)

Vielen Dank und MfG
dpf.dd

**Comment by skerbis** [comment]
Die individuelle URL bezieht sich auf den einzelnen Artikel, den du angelegt hast. 
z.B. um ggf. eine kürzere URL zu erzeugen, z.B. /shop. Ich frage mich aber, bei deinem Vorgehen, warum der Pfad nicht von vorn herein mit der Kategorie shop erstellt wurde. Um die Begrifflichkeit zu tauschen kannst, du ja auf Metas oder den Artikelnamen  in der Navi zurückgreifen.

**Comment by dpf-dd** [comment]
Zur Erklärung: Prinzipiell mag ich es, wenn der Menüpunkt im Frontend 1:1 so lautet, wie er in der Strukturverwaltung angezeigt wird... Der Menüpunkt soll in der 1. Ebene halt "Shop & Verleih" heißen => Flyout/Tap => "Shop" dann als ersten Unterpunkt und "Verleih" als zweiten... SEO-optimiert hätte ich aber auch gern "kaufen" und "ausleihen" in der URL stehen...

Also wenn ich dich richtig verstehe, ist das am einfachsten zu realisieren, indem ich ein Meta-Feld wie z.B. "cat_navname" erstelle und diesen "Shop"" zuweise. Dann kann ich in der Navigation eine Abfrage einbauen, die auf Vorhandensein des Meta prüft und ggf. diesen Bezeichner statt dem Artikelnamen nimmt. Dann "Shop" in "Kaufen" umbenennen und schon müsste es flutschen...
Klingt logisch, probiere ich morgen mal aus :)

Danke!

**Comment by skerbis** [comment]
@dpf-dd es geht noch einfacher. Du kannst auch mit xoutputfilter oder evtl. Spross einfach die Bezeichnung des Links umschreiben.

**Comment by dpf-dd** [comment]
Bisher bin ich immer um xouputfilter rumgekommen und hab Extension Points benutzt. Da hab ich jetzt endlich mal einen Usecase um mich mal damit zu beschäftigen :D
