### ISSUE TITLE
Absolute Urls

### ISSUE THREAD

**Issue by lexplatt** [yakamara/redaxo_yrewrite#188]
Ich finde es wäre das Beste wenn bei `rex_getUrl` immer die absolute Url zurückgegeben wird # @

**Comment by tbaddade** [comment]
@lexplatt Wann ist das nicht der Fall?

**Comment by gharlan** [comment]
Naja, wenn man sich innerhalb der Domain befindet.

Die Frage ist, was haben relative URLs für Vorteile? Gibt es welche?

**Comment by lexplatt** [comment]
genau, ich sehe eigentlich nicht wirklich Vorteile und ich hab auch mal irgendwo aufgeschnappt dass Google lieber die absoluten Urls hat

**Comment by tbaddade** [comment]
> Naja, wenn man sich innerhalb der Domain befindet.

@gharlan eben nicht. Ich habe absolute Urls.

**Comment by gharlan** [comment]
Dann wäre die Frage, was wir unter absolute Urls verstehen?
Ausgehen vom Root, also beginnend mit `/`. Meinst du das?
Alex meint glaube ich: Immer komplett mit Domain.

**Comment by tbaddade** [comment]
| | Url | Bezeichnung |
| - | - | - |
| A | ich/bin/eine/url | relative |
| B | /ich/bin/eine/url | absolute |
| C | http://domain.de/ich/bin/eine/url | ?? |

ggf. mit den Buchstaben A/B/C arbeiten, dann wissen wir, wer was wie meint :)

**Comment by lexplatt** [comment]
Gute idee :D -> ich meine C

**Comment by dergel** [comment]
gibt es mittlerweile
