### ISSUE TITLE
Artikelnamenänderung in Metadaten und Verschieben lösen keine URL-Änderungen aus (ohne komplett den REX-Cache zu leeren)

### ISSUE THREAD

**Issue by alexwenz** [yakamara/redaxo_yrewrite#190]
Habe grade festgestellt, dass eine Artikelnamenänderung über die Metadaten im Artikel keine Auswirkungen auf die URL (yrewrite) des Artikels hat, solange man nicht den Hauptcache von Redaxo leert. Wenn man den Namen über die Struktur (also Artikelübersicht ) ändert, funktioniert es ohne Cacheleerung. 

Auch das Verschieben eines Artikels über die "Funktionen" hat keinerlei Auswirkungen auf die URL, wenn man nicht den Cache leert. 

Bei einer Website mit vielen Redakteuren ist das natürlich sehr schwierig.

**Comment by alexwenz** [comment]
Siehe auch #57

**Comment by tbaddade** [comment]
Da fehlen scheinbar Extension Points an die sich yrewrite hängen kann.

**ART_UPDATED** existiert wird aber bei den Metadaten nicht aufgerufen
**CAT_MOVED**  und **ART_MOVED** existieren noch nicht

**Comment by dergel** [comment]
https://github.com/redaxo/redaxo/issues/2159 CAT MOVED fehlt noch
https://github.com/redaxo/redaxo/issues/2161 muss noch bei Metas aufgerufen werden

CAT_MOVED ist nun in yrewrite schonmal ergänzt,sobald es in REDAXO drin ist,funktioniert auch das .. für yrewrite ist hier das Thema durch .. denke ich :)
