### ISSUE TITLE
Startartikel nicht in Sitemap wenn Startkategorie offline

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#193]
Unabhängig vom Status online/offline des Startartikels oder seiner Kategorie, sollte dieser in der Sitemap abgebildet werden. Aktuell wird er nicht gelistet, wenn die Startkategorie offline ist.

**Comment by tbaddade** [comment]
Ich halte das jetzige Verhalten für richtig. Inwiefern hälst du es für falsch?

**Comment by skerbis** [comment]
Oft wird die Startkategorie per "offline" in der Navigation ausgeblendet, damit diese dort nicht auftaucht. Und tatsächlich scheint Google auf den fehlenden Startartikel der Website zu reagieren. Die Startseite sollte aber in der sitemap.xml drin sein. Man kann das natürlich umgehen indem man die Startseite einfach als Artikel in / anlegt. In bestimmten Konstellationen geht dies aber ggf. nicht.

**Comment by tbaddade** [comment]
Es gibt beim Artikel in der rechten Spalte "Indizierung und Sitemap". Dort müsstest du die Option "Index" auswählen.

**Comment by skerbis** [comment]
grrr. ... ich brauche ne neue Brille ;-)
