### ISSUE TITLE
Umlautdomain (Punycode) macht Probleme

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#194]
Es werden nicht die geforderten Artikel aufgerufen, sondern die 404-Seite.

Übergangs-Lösung: Umlaut-Domain decodiert eintragen.

**Comment by TobiasKrais** [comment]
Du kannst das D2U Helper Addon installieren und dort in den Einstellungen für diese Sprachen ein anderes Rewrite Schema verwenden. Dann kommen richtige URLs heraus. Als Demoseite kannst du auf https://www.kaltenbach.com/zh/ schauen wie gut das funktioniert.

**Comment by TobiasKrais** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/170

**Comment by dergel** [comment]
Über eine eigene Klasse ist das lösbar.

**Comment by alexplusde** [comment]
Es ging nicht um Umlaut-URLs, sondern um die Domain

**Comment by alexplusde** [comment]
https://www.php.net/manual/de/function.idn-to-utf8.php

**Comment by gharlan** [comment]
Man könnte es entweder nur unterstützen, wenn die Intl-Extension installiert ist (was längst nicht immer der Fall ist), oder man könnte die polyfill-lib für die funktionen hier mit reinlegen: https://github.com/symfony/polyfill-intl-idn

**Comment by eaCe** [comment]
idn_to_utf8 funktioniert bei mir z.B. nicht. Wie Gregor bereits erwähnt - die Intl-Extension fehlt. Habe irgendeinen online converter genutzt, bin auch auf den polyfill gestoßen.

**Comment by alexplusde** [comment]
Für mich besteht die Frage, wann und warum eine Umwandlung stattfinden soll.

Variante 1

* URL direkt mit Umlaut eintragen ermöglichen
* URL wird nur für die Validierung in Punycode umgewandelt und dann validiert
* URL wird in der Datenbank mit Umlaut abgespeichert
* URL wird in YRewrite-Methoden mit Umlauten ausgegeben
* YRewrite stellt eine Methode bereit, bei der man die eingetragene Domain via Vendor als Punycode erhält optional.

Das hätte zur Folge, dass fast alle Stellen so bleiben können wie sie sind, aber die Eintragung ermöglicht wird. Denn momentan scheitert es ja nur am Eintragen und Browser kommen hervorragend ohne Punycode klar.

Variante 2

* URL direkt mit Umlaut eintragen ermöglichen
* URL wird für die Validierung in Punycode umgewandelt und dann validiert
* URL wird in der Datenbank als Punycode abgespeichert
* URL wird nur in der Domain-Übersicht von YRewrite als Umlaut-Domain dargestellt, im Domain-Eingabefeld jedoch dann als Punycode
* URL wird in YRewrite-Methoden als Punycode ausgegeben
* YRewrite stellt eine Methode bereit, bei der man die eingetragene Domain via Vendor OHNE Punycode erhält optional.

Diese Variante wäre möglicherweise kompatibler mit Addons, die an YRewrite anknüpfen, weil sie immer eine gültige URL erhalten, die vlt. an anderer Stelle so erwartet würde.

**Comment by gharlan** [comment]
Ich habe letztens mit der Umsetzung begonnen. Wollte mich mal rantasten und bisschen ausprobieren. REDAXO erfordert inzwischen ja auch die intl-Extension, wodurch `idn_to_utf8()` zur Verfügung steht.
Aber ich hatte dann bemerkt, dass meine angedachte Lösung BC-Probleme schaffen würde für die, die jetzt bereits Punycode-URLs eingetragen haben. Ich weiß gerade nicht mehr genau, an welcher Stelle ich die Probleme gesehen hatte.

Meine Wunschvariante wäre eigentlich, dass man die Domain mit Umlauten einträgt, yrewrite sie auch so abspeichert und überall so ausliefert. Und nur intern beim Hostabgleich würde yrewrite umformen zu Punycode.

**Comment by gharlan** [comment]
> Meine Wunschvariante wäre eigentlich, dass man die Domain mit Umlauten einträgt, yrewrite sie auch so abspeichert und überall so ausliefert. Und nur intern beim Hostabgleich würde yrewrite umformen zu Punycode.

Für die Variante spricht übrigens auch, dass wir nur eine Funktion in die eine Richtung zur Verfügung haben, `idn_to_utf8`. 
Man würde also den reinkommenden Host mit `idn_to_utf8` umwandeln, und dann mit den utf8-domains in yrewrite abgleichen.
Für die andere Richtung (utf8 to idn) bräuchte man wieder eine externe Lib oder so.
