### ISSUE TITLE
Yrewrite Redirects: Variablen ermöglichen

### ISSUE THREAD

**Issue by chrfickinger** [yakamara/redaxo_yrewrite#196]
Variablen in Yrewrite Redirects Tabelle (analog Seo42/Rex4) für die Umsetzung von mehrsprachigen Projekten.

![](https://user-images.githubusercontent.com/91317/34718699-f915828a-f537-11e7-81ff-7cd9878432c3.jpg)

**Comment by alexplusde** [comment]
Würde das auch immer mal wieder benötigen und setze derzeit die Weiterleitungen dann in der .htaccess direkt. @RexDude du hast das damals so super umgesetzt - wäre es dir ein leichtes, die Funktion nachzureichen?

**Comment by dergel** [comment]
sehe ich in der htaccess. Geplant ist, dass man eigene htaccess regeln reinhaengen kann. Dann gehen diese auch nicht verloren bei einem Update
