### ISSUE TITLE
Forciertes Ausloggen nach Aufruf via yrewrite weitergeleiteten URLs

### ISSUE THREAD

**Issue by schorschy** [yakamara/redaxo_yrewrite#197]
Beispiel:
alte URL: **domain.de/kontakt.html**
Weiterleitung via yrewrite: 301 moved permanently, auf Artikel **domain.de/kontakt/**.

Beim Aufruf von domain.de/kontakt.html werde ich wie gewünscht auf domain.de/kontakt/ weitergeleitet, allerdings beendet sich dadurch meine Backend-Session.

**Comment by madiko** [comment]
Hallo. Das Problem hatte ich auch. Ich hatte die Vermutung, dass es an einer falschen Einstellung in der .htaccess liegt. Freue mich, wenn es eine schlaue Lösung  bzw. ein Tipps&Tricks daraus gibt. Danke!

**Comment by alexplusde** [comment]
Hab's auf Slack schon berichtet, gleiches gilt, wenn ich in einer Multidomain-Installation bei domain1.de im Backend bin und dann domain2.de im Frontend aufrufe.

**Comment by dergel** [comment]
bei verschiedenen domain ist das klar. Man ist auf der 2. Domain ja gar nicht eingeloggt (Cookies und damit PHP Session etc.)

den anderen Fall muss ich mich ansehen.. sollte natürlich nicht so sein.. Sicher auch, dass die Domain nicht mit oder ohne www. ist ?

**Comment by alexplusde** [comment]
Also dass man in domain1.de im Backend ausgeloggt wird, wenn ich domain2.de im Frontend aufrufe, ist für mich kein nachvollziehbares und erwünschtes Verhalten.

**Comment by alexplusde** [comment]
Da hatten wir ja im Slack nochmal diskutiert und in der `config.yml` und mit der Einstellung `lax` statt `strict` im Frontend und Backend tritt das Problem mit seinen verschiedenen Szenarien nicht mehr auf.

Allerdings weiß ich nicht, ob es bereits genügt, eine von beiden Varianten auf lax zu stellen.

**Comment by alexplusde** [comment]
Vielleicht nochmal aufmachen und dokumentieren? Es gibt immer wieder forciertes Ausloggen im Slack-Channel, bspw, auch durch YCom-Aktionen.

Die Frage ist auch: Will man das Backend auf lax gestellt sehen?

**Comment by alexplusde** [comment]
@pgmrrobot würdest du für die Doku einen PR einreichen?

**Comment by alexplusde** [comment]
Soweit ich weiß wurde das Problem im Core behoben und muss nun nicht mehr extra dokumentiert werden.

**Comment by alexplusde** [comment]
(Kann geschlossen werden)
