### ISSUE TITLE
404 Status-Code wird nicht ausgegeben

### ISSUE THREAD

**Issue by chip75** [yakamara/redaxo_yrewrite#201]
sobald die Startartikel ID = 404 Artikel ID ist.
Dies sollte ggf. korrigiert werden

**Comment by tyrant88** [comment]
brauche ich auch bei search it

**Comment by tyrant88** [comment]
Und REDAXO selbst (ohne yrewrite) macht es auch so, Herr @gharlan !

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/search_it/issues/177

**Comment by elpschulzo** [comment]
Ist das wirklich ein Bug oder evtl. Intention, damit Google Bot und Co. nicht ein und die selbe Seite (Content, Canonical etc.) sehen für 404 und Startseite (wichtigste Seite)?

Ich fänd es sogar OK so, würde dann aber unter dem Auswahlwidget für den Fehlerartikel gern noch eine Checkbox haben wollen "404-Status erzwingen für Fehlerseite" oder so ähnlich, damit man selbst wählen kann.

**Comment by gharlan** [comment]
Wenn man die Startseite direkt aufruft, darf natürlich nicht 404 kommen.

Wenn man aber eine falsche URL aufruft, bleibt die URL stehen (keine Umleitung), aber es erscheint der Fehlerartikel. Dann muss es 404 sein, auch wenn Fehlerartikel==Startseite.

**Comment by tyrant88** [comment]
Der Status code 404 sagt google ja gerade, dass die URL mit dem Inhalt nicht in den Index soll, weil es ein Fehler ist.

**Comment by elpschulzo** [comment]
Gibt es einen Workaround oder läuft es auf das Anlegen eines Fehlerartikels hinaus?

**Comment by alexplusde** [comment]
Ich würde an deiner Stelle immer einen Fehler 404 Artikel anlegen.

**Comment by dergel** [comment]
Status wird nun gesetzt - egal ob Startartikel oder nicht. Es kann aber natürlich nun sein, dass andere AddOns (URL ?) diesen Status zurücksetzen müssen. Was auch der richtige Weg ist, dennoch hat das hoffentlich keine Folgeproblem. @tbaddade kannst du dir das bei URL mal anschauen ?

**Comment by tyrant88** [comment]
super!

**Comment by alexplusde** [comment]
Der richtige Weg ist doch, dass der 404-Artikel und der Startseiten-Artikel nie derselbe sein sollte. 

Findet ihr, man sollte das in der Doku hier noch klarer kommunizieren?
https://github.com/yakamara/redaxo_yrewrite#domain-hinzuf%C3%BCgen @tyrant88 @elpschulzo @gharlan @dergel

**Comment by tyrant88** [comment]
Ich finde die Aussage nicht korrekt. Kann doch Fälle geben, woher soll ich das jetzt wissen?

**Comment by dergel** [comment]
Ich finde, dass man in der Doku ruhig schreiben kann, dass wir empfehlen eine eigene 404 Seite zu verwenden.

**Comment by alexplusde** [comment]
> Ich finde die Aussage nicht korrekt. Kann doch Fälle geben, woher soll ich das jetzt wissen?

Auf eigene Gefahr dann, oder nicht?

**Comment by tyrant88** [comment]
"nie" ist einfach nicht richtig.
was @dergel sagt
