### ISSUE TITLE
Eigene Statuscodes bei Weiterleitungen definieren können

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#206]
z.B. für https://github.com/FriendsOfREDAXO/tricks/blob/master/howto_errorcode_410.md

**Parameter**
`Alte URL`
statt Neue URL: `Fehlercode`

**Comment by dergel** [comment]
ich würde liebe diese Codes ergänzen. Welche fehlen dir ?

**Comment by alexplusde** [comment]
Hmm, das verlinkte howto fehlt inzwischen... Ich weiß es nicht mehr...

**Comment by tbaddade** [comment]
Das ist durch das Verschieben der Docs passiert. Das hier könnte es nach dem Namen her sein
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/howto/errorcode_410.md

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yrewrite/blob/48830dfbbe399553d07d219e03bc5539c5ac0ef6/pages/forward.php#L47 hier werden die Status-Codes gesetzt

Vollständig wären die 3xx gemäß https://http.cat/ mit 

- [ ] 304 Not Modified
- [ ] 305 Use Proxy
- [ ] 308 Permanent Redirect (Der fehlt mir gelegentlich)  

Was mir fehlt (und Anlass des Issues wäre), ist, statt auf eine neue URL weiterleiten zu können, dass eine eingetragene URL einfach nur diesen Status ausgibt:
- [ ] 400 Bad Request
- [ ] 403 Forbidden
- [ ] 404 Not Found

Oder zumindest dieser Status mit einem Artikel verknüpft werden kann.

**Comment by alxndr-w** [comment]
Template regelt.
