### ISSUE TITLE
SSL bei vorgeschaltetem SSL-Server ermöglichen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#218]
Szenario für den Betrieb mit vorgeschaltetem CloudFlare-SSL o.ä.: 

Die Website muss den Betrieb in http ermöglichen, aber alle internen Links mit https:// ausgeben können.

Workaround: Mit dem XOutputfilter alle internen Links von http in https ersetzen und YRewrite weiter auf http stehen lassen.

**Comment by leyyinad** [comment]
Bei meinem Kunden ist `$_SERVER['HTTP_CLOUDFRONT_FORWARDED_PROTO'] == 'https'`, es würde also vermutlich helfen, wenn man bei `isHttps()` einfach diese Variable mitabfragt, analog zu `HTTP_X_FORWARDED_PROTO`.

**Comment by gharlan** [comment]
@dergel wie besprochen, hier die Links:

[Doku zu Trusted Proxies in Symfony](https://symfony.com/doc/current/deployment/proxies.html).
Wobei sich da [gerade was geändert hat](https://bit.ly/2Ro3Bca) (auch die Diskussion unten ist interessant).
[getHost](https://github.com/symfony/symfony/blob/28edd705e8d095085deccbe491518415f91ac702/src/Symfony/Component/HttpFoundation/Request.php#L1182-L1232)- und [isSecure](https://github.com/symfony/symfony/blob/28edd705e8d095085deccbe491518415f91ac702/src/Symfony/Component/HttpFoundation/Request.php#L1159-L1168)-Methode, und von da geht es in [getTrustedValues](https://github.com/symfony/symfony/blob/28edd705e8d095085deccbe491518415f91ac702/src/Symfony/Component/HttpFoundation/Request.php#L2028-L2077).

**Comment by gharlan** [comment]
Das Thema wird nun hier behandelt: https://github.com/yakamara/redaxo_yrewrite/issues/441
