### ISSUE TITLE
Block access to directories without a default document

### ISSUE THREAD

**Issue by RexDude** [yakamara/redaxo_yrewrite#22]
Huhu :) Das sollte aufjedenfall in die .htaccess mMn um eben zu vermeiden, dass das ganze Zeugs aus files/addons etc. im Google Index landet.

https://github.com/h5bp/html5-boilerplate/blob/master/.htaccess#L289-L300

(sollte jetzt unproblematisch sein, wegen der If-Abfrage, Boilerplate machts ja auch ;))

**Comment by gharlan** [comment]
Dann lassen wir das wohl lieber.
