### ISSUE TITLE
Cache löschen: muss wirklich der gesamte Cache gelöscht werden?

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yrewrite#223]
Wenn YRewrite seinen Cache löscht, wird aktuell der gesamte REDAXO-Cache gelöscht:
https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/yrewrite.php#L624-L627

Muss das sein? Würde es nicht reichen, wenn YRewrite wirklich nur seine eigenen zwei (?) Cache-Dateien löschen würde?

Ich pinge einfach mal ein paar Leute an:
@tbaddade @alexplusde @staabm @bloep @RexDude
Fällt euch irgendein Grund ein, warum das notwendig sein könnte, mehr als die YRewrite-Cache-Dateien zu löschen? 

(Wie ich drauf gekommen bin: https://github.com/RexDude/xcore/issues/237)

**Comment by tbaddade** [comment]
> Würde es nicht reichen, wenn YRewrite wirklich nur seine eigenen zwei (?) Cache-Dateien löschen würde?

Ich vermute nicht. Das Url AddOn hätte vermutlich dann noch falsche Domains im eigenen Cache. Abhilfe würde dann ein EP schaffen.

**Comment by alexplusde** [comment]
Wir hatten die Diskussion doch mal, dass man einzelne Cache-Bereiche löschen können sollte. Und da wäre ich nach wie vor dafür. Insb. Bilder und Artikel/DB/URLs sind getrennt zu betrachten.

**Comment by tbaddade** [comment]
wie wäre es mit

```
rex_addon::get('yrewrite')->deleteCache();
rex_addon::get('yrewrite')->deleteCacheFile($file);
```

Sobald die Methode aufgerufen wird, wird ein EP registriert, so dass andere abhängige AddOns darauf reagieren und ihren eigenen Cache löschen können.

**Comment by bloep** [comment]
Mir fällt spontan auch kein Fall ein.
Aber ich finde die Idee von @tbaddade nicht schlecht, einen EP zu verwenden. Ich würde dann vielleicht sogar sagen, dass das etwas für den Core wäre.

Die Methoden `rex_package::deleteCache()` und `rex_package::deleteCacheFile($file)` fände ich gut.
Aktuell gibt es ja den EP `CACHE_DELETED`. Man könnte diesen erweitern, sodass beim Löschen eines Package-Caches als Param/Subject der Package-Key mit übergeben wird und optional bei `deleteCacheFile` zusätzlich die gelöschte Datei.

**Comment by tbaddade** [comment]
>  Ich würde dann vielleicht sogar sagen, dass das etwas für den Core wäre.

Genau. Die obigen Methoden existieren so noch nicht in der `rex_package` class

**Comment by gharlan** [comment]
Seit 5.6 gibt es eine `clearCache`-Methode in `rex_package`:
https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/packages/package.php#L305

**Comment by staabm** [comment]
bevor man hier noch mehr EPs schafft, die die Anbhängigkeiten der Addons untereinander noch wetier verschlimmern würde ich es lieber so lassen wie es ist.

dann lieber ein bissl zu viel gelöscht ...

Fehler durch die Abhängigkeiten sind immer sehr schwer zu finden, fixen und auch Versionsübergreifend schwierig ohne Regressions beizubehalten.

**Comment by bloep** [comment]
Ich teile die Bedenken von @staabm ... Sind ja jetzt schon teils "riesige" Abhängigkeitsbäume.

**Comment by tbaddade** [comment]
Welche Abhängigkeiten verschlimmern wir? Ich finde es von Vorteil zu wissen, wenn ein AddOn sein Cache löscht, dass auch ein anderes AddOn ggf. darauf reagieren kann.

**Comment by bloep** [comment]
Wobei man ja eigentlich nur optionale Abhängigkeiten schaffen würde... Wäre eigentlich für eine Überarbeitung des `CACHE_DELETED`-EPs wie oben beschrieben.

**Comment by IngoWinter** [comment]
Ich betreue einige arg bildlastige Seiten. Nach jeden YRewrite Update muss ich manuell ein paar tausend Bilder neu generieren lassen. Könnte man nicht der `rex_delete_cache` ein Array von Verzeichnissen mitgeben, die explizit nicht gelöscht werden sollen? Was in Richtung
```
function rex_delete_cache($exceptions = [])
{
    // close logger, so the logfile can also be deleted
    rex_logger::close();

    $finder = rex_finder::factory(rex_path::cache())
        ->recursive()
        ->childFirst()
        ->ignoreFiles(['.htaccess', '.redaxo'], false)
        ->ignoreDirs($exceptions)
        ->ignoreSystemStuff(false);
    rex_dir::deleteIterator($finder);

    rex_clang::reset();

    // ----- EXTENSION POINT
    return rex_extension::registerPoint(new rex_extension_point('CACHE_DELETED', rex_i18n::msg('delete_cache_message')));
}
```

**Comment by alexplusde** [comment]
Statt einer Blacklist würde ich eher mit einer Whitelist arbeiten und nur das löschen lassen, was benötigt wird.

**Comment by IngoWinter** [comment]
Den Cache komplett zu löschen finde ich in Ordnung. Ist ne bombensichere Nummer, niemand muss sich einklinken und was beachten. Der einzige Cache der mir Bauchschmerzen macht (und der 100%ig nix mit YRewrite zu tun hat), ist der media_manager Cache. Weil der sehr zeitaufwendig generiert werden muss und - falls nicht vorhanden - einen merkbaren negativen Einfluss auf die Ladezeit der Website hat. Die rex_delete_cache Erweiterung ist minimal und rückwärtskompatibel.

**Comment by alxndr-w** [comment]
Ich hoffe, mein PR ist so richtig. Bitte gerne drüberschauen.
