### ISSUE TITLE
Wunsch: Multiple Domains :: Redaktionsdomain / Minibar / Frontend

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#226]
Wenn es eine Domain wie **redaktion.xyz.tld** gäbe über die **alle** Seiten erreichbar wären, könnte man so den Backenduser abfragen und auf allen Seiten **Edit-Buttons oder die Minibar** zur Verfügung stellen. Das Problem aktuell ist ja dass die Session nicht auf alle Domains übertragen werden kann und so die Minibar nur auf der eingelogten Domain zu sehen wäre. 

Mit einer Redaktions-Domain könnte das Problem gelöst werden. 

Kann ich alle Seiten ohne automatische Umschaltung der Domain per YRewrite über das Frontend in dieser redaktions-Domain erreichen, wären umständliche Konstrukte per JS oder Iframe Session Übergabe nicht erforderlich um die Session zu übergeben.

**Comment by dergel** [comment]
ich verstehe was du lösen willst, aber eigentlich ist das kein yrewrite thema.. hier ist im Moment klar definiert, dass ein Artikel nicht auf mehreren Domains sein darf und alles ist darauf ausgelegt...

hmm

**Comment by skerbis** [comment]
Ist ja auch richtig so nach "außen". Es dürfte ja nur für diesen Zweck sein, also für die Redaktion.

**Comment by dergel** [comment]
ich denke da eher an Sessions die domainübergreifend funktionieren und damit wäre man auch bei diesem Thema fein raus.

Es gibt sicherlich Möglichkeiten das irgendwie auch über yrewrite zu lösen, aber das wäre meiner Erachtens an der falschen Stelle.. deswegen einerseits YCom und REDAXO selbst wäre passender

**Comment by skerbis** [comment]
Ich finde eine "Redaktions"-Domain ist die einfachste Lösung. Sessions über Domains hinweg funktionieren einfach nicht.

**Comment by alxndr-w** [comment]
Ich sehe schon Kunden, die dann Redaktions-Domains kopieren und an irgendwen schicken, statt der richtigen URL.

Ein domainübergreifender Login wäre super – weiß aber nicht, wie das möglich wäre.

**Comment by skerbis** [comment]
Mit Subdomains ja. Mit unterschiedlichen Domains (auch auf dem gleichen Server) tricky bis garnicht.

**Comment by gharlan** [comment]
> Ich sehe schon Kunden, die dann Redaktions-Domains kopieren und an irgendwen schicken, statt der richtigen URL.

Das würde ich aus dem Grund auch eher vermeiden wollen.
Entweder die Redakteure hätten automatisch die Redaktionsdomain im Frontend (wenn eingeloggt). Dann entstände genau das Problem, dass sie leicht versehentlich diese URLs verschicken würden, da sie die echten URLs separat irgendwo herbekommen müssten.
Oder man würde es zum Umschalten machen. Dann kann es einerseits aber ja auch immer noch passieren, wenn die in dem Modus gerade sind. Und außerdem müssen die Redakteure dann erstmal verstehen, wozu der Modus überhaupt gut ist und wann sie ihn (de)aktivieren sollten.
