### ISSUE TITLE
yrewrite Benutzerrechte

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yrewrite#227]
Die Möglichkeit Seo-Daten und Benutzerdefinierte Url über die Benutzerverwaltung zu steuern wäre gut/sinnvoll. "Normale" Redakteure sollten in meinem Fall keinen Einfluss auf die Daten haben. Wenn überhaupt dann nur auf die SeoDaten aber in keinem Fall auf die Benutzerdefinierte Url. Lustiges wöchentliches Ändern ist hier nicht sinnvoll ..

Hier gibts schon was passendes dazu:
https://github.com/yakamara/redaxo_yrewrite/pull/141/commits/4de4b66fdcf4c595b0f1cace333b380f41f38c3a

**Comment by dergel** [comment]
Ist nun drin. Kam als PR
