### ISSUE TITLE
Notice Undefined index: SCRIPT_NAME

### ISSUE THREAD

**Issue by bitshiftersgmbh** [yakamara/redaxo_yrewrite#228]
Moin.
Im System-Log erscheint seit dem letzten Update:
```
Notice	Undefined index: SCRIPT_NAME	redaxo/src/addons/yrewrite/lib/yrewrite.php   43
```
Evtl. auch durch eines der REX 5.6.x Updates zuletzt... i dont know. Ist nicht schlimm, wollte es aber reported haben.

**Comment by elpschulzo** [comment]
Vermutlich gibt's das schon immer (?), wenn eben die Server-Config diese Var nicht mit ausgibt. Seit ner Weile ploppen aber auch die Notices im Syslog auf. Deshalb fällt es wohl gerade auf.

**Comment by bitshiftersgmbh** [comment]
Die Notice taucht immer noch auf. :/
`SCRIPT_NAME` ist leider nicht überall zuverlässig verfügbar in `$_SERVER`.

**Comment by alexplusde** [comment]
Was müsste anstelle dessen verwendet werden in deiner Konfiguration @bitshiftersgmbh ?

**Comment by gharlan** [comment]
Ist `$_SERVER['PHP_SELF']` bei dir gesetzt @bitshiftersgmbh?

**Comment by bitshiftersgmbh** [comment]
> Ist `$_SERVER['PHP_SELF']` bei dir gesetzt @bitshiftersgmbh?

Puh! Das ist Ewigkeiten her. Ich weiß nicht mal mehr bei welchem Projekt das war. :/ Hatte jetzt wirklich sehr lange kein Thema mehr mit diesem Issue.

**Comment by gharlan** [comment]
Dann schließe ich hier erstmal, bis es bei irgendwem mal wieder auftritt.
