### ISSUE TITLE
Default Keywords und Description führen zu einer Warnung in den Webmaster Tools

### ISSUE THREAD

**Issue by RexDude** [yakamara/redaxo_yrewrite#23]
http://www.seo-diaries.de/wp-content/uploads/Bildschirmfoto-2012-12-11-um-20.02.10.png

Es sollte deshalb überlegt werden, ob man dem User tatsächlich ermöglichen sollte hier Defaults einstellen zu können. MMn sollten die Felder entweder leer bleiben, oder man sollte sie von Hand und individuell auf den Content zugeschnitten befüllen.

**Comment by gharlan** [comment]
Bin auch für Entfernen der Default-Description.

**Comment by dergel** [comment]
dann raus damit .. @gharlan machst du das ? ;) ..

**Comment by dergel** [comment]
default description ist entfernt

**Comment by RexDude** [comment]
:clap:
