### ISSUE TITLE
Error yrewrite.php:392

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yrewrite#231]
Nach Umstellen der System- und yrewrite URL auf anderen Wert bekomme ich einen Error, siehe Screenshot anbei.

Ich muss die pathlist.json aus dem Cache löschen, damit es wieder funktioniert.

![bildschirmfoto 2018-07-26 um 09 37 05](https://user-images.githubusercontent.com/1846849/43248379-f6a4fcee-90b7-11e8-8997-87b6219f8dd7.png)

**Comment by fietstouring** [comment]
yrewrite 2.3, Redaxo 5.6.2

**Comment by dergel** [comment]
kann ich leider nicht nachvollziehen, mit version 2.4 geprüft ?

**Comment by alexplusde** [comment]
Es müsste die pathlist in solchen Fällen ungültig gemacht werden.
