### ISSUE TITLE
aktuelle .htaccess liefert CSS Datei als text/plain aus

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#232]
Auf meiner Testseite wird die CSS Datei /media/stylesheet-startseite.css als Content-Type text/plain ausgeliefert. Wenn in der .htaccess die Zeile `RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]` auskommentiere ändert sich der Content-Type zu text/css. Braucht es diese Zeile wirklich?

**Comment by iceman-fx** [comment]
Ich schließe mich dem Issue hier an.
Auch bekomme mit der aktuelle htaccess keine CSS geladen, da diese als JPG interpretiert werden.

Entfernt man folgende Zeilen in der htaccess, klappt es wieder, was aber wiederum dann u.U. mit den Bildaufrufen gibt:
RewriteRule ^media/([^/]+)/(.*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]
RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]

**Comment by staabm** [comment]
Heute im slack erneut gemeldet

**Comment by TobiasKrais** [comment]
Der Fix von Ingo löst zwar das Problem, dass CSS / JS Dateien und andere richtig ausgeliefert werden, aber das auth_media Plugin von YCom ist auf die Zeile angewiesen um die Rechte zu prüfen.

**Comment by dergel** [comment]
d.h. auch mit der REDAXO 5.7 Version und dem dort angepassten media_manager klappt die Auslieferung von .css Dateien nicht richtig ? Was passiert genau ?

**Comment by TobiasKrais** [comment]
Ich melde mich Morgen Abend oder Übermorgen. Bin gerade unterwegs.

**Comment by TobiasKrais** [comment]
Ja, auch mit der 5.7 Beta klappt die Auslieferung nicht richtig. In dieser Zeile:
https://github.com/redaxo/redaxo/blob/19ec96d5ba2cb6a963991053ffe65ded8e1a6aa0/redaxo/src/addons/media_manager/lib/managed_media.php#L373
wird "text/plain" statt "text/css" oder "text/js" ausgegeben.

Andere haben wohl auch das Problem: https://stackoverflow.com/questions/45179337/mime-content-type-returning-text-plain-for-css-and-js-files-only

**Comment by TobiasKrais** [comment]
Hier eine Mögliche Lösung:
`			if($content_type == 'text/plain') {
				if(pathinfo($this->getSourcePath(), PATHINFO_EXTENSION) == "css") {
					$content_type = 'text/css';
				}
				else if(pathinfo($this->getSourcePath(), PATHINFO_EXTENSION) == "js") {
					$content_type = 'application/javascript';
				}
			}	
`

**Comment by TobiasKrais** [comment]
Soll ich einen Pull Request machen?

**Comment by TobiasKrais** [comment]
Alle Hinweise die ich im Netz gefunden habe, verwenden eine Lösung wie im Pull Request.

**Comment by TobiasKrais** [comment]
Danke fürs Mergen!
