### ISSUE TITLE
Bug? Artikelname statt Kategoriename bei .html-Suffix

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#234]
Aus Slack

XXX
Hallo zusammen, eine Frage zu yrewrite:
Leider schreibt das Addon die URLs nicht so wie ich sie bräuchte. Mein benötigtes Pfadschema wäre
domainname.tld/kategoriename/startartikelname.html, erzeugt wird aber domainname.tld/kategoriename/kategoriename.
in der class rex_yrewrite_scheme kann ich das suffix auf .html einstellen, ok, aber wo setze ich an, wenn ich anstatt des kategorienamens den artikelnamen möchte? Wäre schön, wenn das im yrewrite Addon ohne das zusätzliche scheme-Addon ginge, welches mir auch nicht das gewünschte Schema anbietet.

Alexander Walther [vor 20 Stunden]
Hallo XXX, das sollte m.E. von Haus aus so sein. Evtl ein Bug, den niemand bisher bemerkt hat? Kannst du ein issue bei GitHub dazu aufmachen?

Alexander Walther [vor 20 Stunden]
Geht es darum, dass du die alten URLs aus R4 beibehalten möchtest wegen seo? Dann hätte ich einen alternativen Vorschlag

XXX
Es gibt im yrewrite-Scheme offenbar einen Unterschied zwischen $cat->getName() und $cat->getValue('name'). In der Funktion appendCategory habe ich das nun geändert und den Suffix auf '.html' gestellt. Jetzt wird der URL geschrieben so wie ich es wollte.

Alexander Walther [vor 2 Stunden]
kannst du genauer beschreiben, wo?

XXX
Im Addon-Verzeichnis, yrewrite/lib/scheme.php, Zeile 13 -> suffix auf '.html' stellen, Zeile 55 -> $this->normalize($cat->getName(), $cat->getClang()); ersetzt durch $this->normalize($cat->getValue('name'), $cat->getClang());

**Comment by tbaddade** [comment]
> erzeugt wird aber domainname.tld/kategoriename/kategoriename.

erzeugt wird aktuell meines Wissens

| Art | Url |
| --- | --- |
| für die Kategorie | `domainname.tld/kategoriename/` |
| für einen Artikel in der Kategorie | `domainname.tld/kategoriename/artikelname/` |
| für eine Unterkategorie | `domainname.tld/kategoriename/unterkategorienname/` |

Wenn man jetzt das Suffix ändert, dann sollte anstatt des letzten `/` das neue Suffix erscheinen.

> Im Addon-Verzeichnis, yrewrite/lib/scheme.php, Zeile 13 -> suffix auf '.html' stellen
Das sollte man vermeiden. Bei einen Update wäre das weg. Besser eine eigne Scheme class erstellen, die von der `rex_yrewrite_scheme` erbt.

**Comment by alexplusde** [comment]
Kannst du den Bug denn verifizieren/falsifizieren? Dann brauchen wir entweder einen PR oder Close.

**Comment by tbaddade** [comment]
Ich kann die Urls, wie oben in der Tabelle abgebildet, bestätigen.

D.h. wie kam es denn zu solch einer Url `domainname.tld/kategoriename/kategoriename`?
Eventuell kann der eigentliche Autor da genauere Informationen zu geben.

**Comment by alexplusde** [comment]
> Ich fände es sinnvoller, wenn er hier sein Problem genauer schildert.

Da bin ich bei dir. Hat er aber nicht gemacht.

**Comment by erraiva** [comment]
Hallo, tut mir leid für die verspätete Antwort, ich hab die Benachrichtigung nicht gesehen.
Hier zwei Screenshots, die das Problem zeigen. (Es hat nicht mit dem .html-Suffix zu tun, wobei ich mich schon frage, warum der in yrewrite nicht genauso einfach einzustellen ist wie z.B. im yrewrite_scheme.) 
Der Artikelname wird nicht verwendet, sondern der Kategoriename:
http://www.kipp-agentur.de/transfer/yrewrite_frontend.png
http://www.kipp-agentur.de/transfer/yrewrite_backend.png
Login ist transfer / download

LG Heinz

**Comment by erraiva** [comment]
Ok, so gehts auch:
![yrewrite_backend](https://user-images.githubusercontent.com/17403820/45806549-a6ec1580-bcc1-11e8-85e9-18307705dff6.png)
![yrewrite_frontend](https://user-images.githubusercontent.com/17403820/45806550-a6ec1580-bcc1-11e8-9c04-0dc1f903b7da.png)
Ich weiß, das ist kein Bug, aber warum sollte nicht auch der Startartikelname generiert werden?

**Comment by tbaddade** [comment]
Ich sehe da keinen Fehler, denn genau das macht aktuell yrewrite so. Siehe auch weiter oben in der Tabelle Zeile 3.

Ich ging von dieser Url aus `domainname.tld/kategoriename/kategoriename`
Ich dachte das die Kategorie doppelt angehangen wird, dabei handelt es sich um den Name einer Unterkategorie

Wenn du jetzt dort den Startartikelnamen haben willst, nutze ein eigenes Scheme welches von `rex_yrewrite_scheme` erbt. Registrieren kannst du das Scheme so https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/project/boot.php#L7-L8

Wenn du dann diese Zeile
https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/scheme.php#L55

 in deinem Scheme so anpasst
```
return $path . '/' . $this->normalize($cat->->getStartArticle()->getName(), $cat->getClang());
```

sollte deine gewünschte Url erstellt werden.

Ich schließe, da es keinen wirklichen Fehler seitens yrewrite ist.

**Comment by erraiva** [comment]
Ja, danke. :-)
