### ISSUE TITLE
SVGs verschwinden nach setzen der htaccess

### ISSUE THREAD

**Issue by MrJackJonesIII** [yakamara/redaxo_yrewrite#235]
Wie ich im slack-channel erfahren habe ist der Bug bekannt und es müsste schon ein issue bestehen, ich konnte es jedoch hier nicht finden:
In einer frischen Installation von redaxo sind nach setzen der htaccess SVGs in Backend und Frontend nicht mehr angezeigt worden. Alle weiteren Bilddateien aus /media wurden weiterhin normal dargestellt. 
Nach Löschen des Folgenden läuft es wieder:
`RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]`
Zeile 97 in der htaccess unten.

Nachdem ich das Problem in meinen letzten Installationen nicht hatte, frage ich mich was diesmal anders war. 
1. Zum einen sind einige Dateien drin, die gleich im Dateinamen sind und sich nur in der Endung unterscheiden.
2. Einige haben denselben Titel im Medienpool. 
3. Habe ich die svgs über die Synchronisierungsfunktion im Medienpool hinzugefügt.

[htaccess.txt](https://github.com/yakamara/redaxo_yrewrite/files/2400017/htaccess.txt)

![screen_mmnote_2018-09-20 08 40 03](https://user-images.githubusercontent.com/1665937/45800394-1a395b80-bcb1-11e8-82e5-175fc78565f8.png)

**Comment by alexplusde** [comment]
> Habe ich die svgs über die Synchronisierungsfunktion im Medienpool hinzugefügt.

Dann haben sie vermutlich dadurch alle denselben Titel bekommen, der da eingestellt war. Kann das sein?

**Comment by alexwenz** [comment]
Habe grade ein update von R4 auf R5 gemacht. Danach waren bei mir auch alle über /media/blabla.svg eingebundenen Dateien nicht mehr da.

Entfernen der o.g. Zeile hilft. Ist die nicht ein wenig zu global? PDFs oder sonstige Dateien können so nicht mehr "einfach" verlinkt werden.

**Comment by MrJackJonesIII** [comment]
> 
> 
> > Habe ich die svgs über die Synchronisierungsfunktion im Medienpool hinzugefügt.
> 
> Dann haben sie vermutlich dadurch alle denselben Titel bekommen, der da eingestellt war. Kann das sein?

Das kann sein. Sicher bin ich mir das jetzt leider nicht mehr. Soll ich testen?

**Comment by alexplusde** [comment]
> Das kann sein. Sicher bin ich mir das jetzt leider nicht mehr. Soll ich testen?

Einfach Bescheid geben, wenn es nochmal passiert. Ich gehe davon aus, dass das der Grund war.

**Comment by ynamite** [comment]
Ich habe das Issue gerade mit einer SVG Datei, die im FE und im Medienpool nicht angezeigt wird, wenn die Rule von MediaAuth in er htaccess ist. Sobald ich die auskommentiere, wird die Datei korrekt ausgegeben.
R5.14.1
ycom 4.0.7
media auth 4.0.7

**Comment by ynamite** [comment]
Funktioniert nun wieder. Lösung für meinen Fall: 
ich hatte bereits einen eigenen MM-Typ mit Namen "default" und die Regel erwartet ja einen Typ mit Namen "default", der einfach die Datei anzeigt (Effekt "Header anpassen" -> "open_media").
Habe jetzt einen Typ mit Namen open_media erstellt, mit dem entsprechenden Effekt und die htaccess Regel angepasst
`RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=open_media&rex_media_file=$1&%{QUERY_STRING} [B]`

**Comment by skerbis** [comment]
@ynamite eigentlich sollte das Problem in der aktuellen Version nicht auftauchen da yform den Medientyp yrewrite_default verwendet. Ich schätze du hast YRewrite aktualisiert aber die htaccess nicht aktualisiert.

**Comment by ynamite** [comment]
@skerbis 
Ja das stimmt, ich hatte yrewrite aktualisiert und ycom inkl. media-auth in der aktuellsten Version heruntergeladen und installiert. yrewrite hat bei mir keinen Medientyp Namens "yrewrite_default" angelegt ... in der aktuellsten media-auth Doku steht zudem:
`RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]`

und wie gesagt, der Typ mit Namen "default" ist bei mir bereits in Verwendung (eigener Typ), daher auch der Fehler. 
Find ich übrigens super, dass der Default MM-yrewrite-Typ neu "yrewrite_default" heisst :)

**Comment by skerbis** [comment]
ups da muss mal was an der Doku gemacht werden.
