### ISSUE TITLE
IDEE für Redirects: Filter ergänzen

### ISSUE THREAD

**Issue by elpschulzo** [yakamara/redaxo_yrewrite#237]
Wie viele nutze/brauche ich die Weiterleitungen von YRewrite regelmäßig. Was ich zu Weilen vermisst habe ist die Möglichkeit die eingehende Anfrage noch weiter zu filtern (bzw. zu validieren) ehe tatsächlich die Umleitung stattfindet.

Folgende Filter hätten mir schon oft sehr geholfen:
- URL-Params
- HTTP-Referrer (aus $_SERVER)
- User Agent

Man sollte 0-n dieser Filter zusätzlich anwählen können. Alle 3 hätten noch 2 weitere Felder im Config-Set:
- Text-Feld für den zu prüfenden Wert
- Dropdown für Art der Prüfung mit...
  - `=`
  - `!=`
  - `regex match`
  - (ggf. `!regex match`)

Bsp.-Szenario:
- Nur Aufrufe von URL mit bestimmten URL-Parametern sollen umgeleitet werden
- Falsch konfigurierter Newsletter mit Link, der da nicht reingehört: Bei Klick auf Link in Mail sind i.d.R. URL-Params dabei, die man abfragen und so nur Leute, die den falschen Ziellink klicken, umleiten könnte. Hingegen klappt der Link bei normalem Aufruf über die HP oder Google.
  - Das gleiche wäre (mit mehr Unsicherheit) über den Referrer-Filter zu lösen

Zumindest der Param-Filter wäre richtig nice und würde vieles vereinfachen, was ich aktuell in die .htaccessen stopfen muss.

**Comment by dergel** [comment]
leider erst jetzt wieder auf dem Schirm. Das sind für mich doch keine YRewrite Funktionen, da zu komplex um es abstrakt abzubilden. Lieber dann eigene Regeln in der .htaccess schreiben.
