### ISSUE TITLE
Update auf neue Version zerschießt Chinesische URLs aus eigenem Schema

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#241]
Ich habe ein Redaxo mit YRewrite am laufen (www.kaltenbach.com). Wir nutzen dort auch Chinesische URLs. Die funktionieren mit meinem Rewriter Schema normalerweise ohne Probleme. Nach dem Update von YRewrite 2.2 auf 2.3 und dann auch nach dem Update von 2.3 auf 2.4 waren die URLs kaputt. Beispiel vor dem Update:
https://www.kaltenbach.com/zh/%E4%BA%A7%E5%93%81/
Daraus wurde nach dem Update:
https://www.kaltenbach.com/zh//
Hier mein Rewrite Schema: https://github.com/TobiasKrais/d2u_helper/blob/master/lib/d2u_yrewrite_scheme.php

Das Löschen des Cache nach dem Update konnte das Problem nicht beheben. Erst als ich in meinen Rewriter die Zeile `print "Hallo Welt";` eingefügt habe und den Cache neu generiert habe, wurden die URLs wieder angepasst. Dann die Zeile wieder raus und den Cache nochmals generieren und es funktioniert alles wie vor dem Update.

**Comment by dergel** [comment]
?? sehr seltsam. kannst du den Fehler reproduzieren ? kannst du schauen was im cache file steht ?

**Comment by TobiasKrais** [comment]
Leider kann ich den Fehler nicht reproduzieren. Wenn er das nächste mal kommt, werde ich mir das cache file anschauen.

**Comment by dergel** [comment]
Dann melde dich dann nochmal.

**Comment by dergel** [comment]
cache gelöscht ? .. an diesen Bereichen ist eigentlich gar nichts gemacht worden..

**Comment by tbaddade** [comment]
Es scheint, dass dein Scheme nicht genutzt wird … Kannst du den Fehler eingrenzen?

**Comment by dergel** [comment]
wo liegt die schema datei ?

**Comment by TobiasKrais** [comment]
Spannend ist, dass es vorhin auf einmal wieder funktioniert hat. Darauf habe ich zum Test die Versionsnummer von YRewrite in der package.yml zurück gesetzt und das Update nochmals laufen lassen. Wieder genau der gleiche Fehler. Die Schritte, die ich vorher zur "Fehlerbehebung" gemacht habe, haben dieses mal dann keine Wirkung gezeigt. :-(
Wo ist im Code die Weiche, welcher Rewriter genutzt werden soll? Vielleicht kann ich da was rausfinden.

**Comment by TobiasKrais** [comment]
Was ich bisher herausfinden konnte: der Rewriter wird tatsächlich nicht aufgerufen. Hier die Zeile in der boot.php, in der der Rewriter aufgerufen wird:
https://github.com/TobiasKrais/d2u_helper/blob/903b606eeb35dd57663dc685e53624e24653939e/boot.php#L3
Selbst wenn ich das "if" entferne wird der Rewriter nicht aufgerufen. Hat jemand eine Idee, wie ich herausfinden kann woran das liegt?

**Comment by dergel** [comment]
welchen Teil des IFs musst du entfernen ?

`rex_addon::get('yrewrite')->isAvailable() `

oder 

`rex_config::get('d2u_helper', 'activate_rewrite_scheme', 'false') == 'true'`

**Comment by TobiasKrais** [comment]
Ich habe mal beide entfernt und es hilft nichts.

**Comment by dergel** [comment]
kann ich im moment nicht helfen.. ich weiss nicht welche abhängigkeiten in deinem addon existieren. leg das ganze doch mal in das project addon ..

**Comment by TobiasKrais** [comment]
Danke trotzdem für deine Hilfe.
Wenn du dir den Code anschaust, dann ist die erste Zeile der Addon boot.php nachdem ich das "if" entfernt habe diese:
`rex_yrewrite::setScheme(new d2u_yrewrite_scheme());`
Das d2u_yrewrite_scheme liegt im /lib/ Verzeichnis des Addons und sieht so aus: https://github.com/TobiasKrais/d2u_helper/blob/master/lib/d2u_yrewrite_scheme.php
gibt es da noch Abhängigkeiten, die dazwischen funken können?

**Comment by tbaddade** [comment]
Schau mal ob vor dem if hier
https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/yrewrite.php#L34

dein Scheme gesetzt wird. 
`dump(self::$scheme); exit();`

Ich vermute nicht. Wenn du einen chinesischen Artikelnamen änderst wird dann die Url korrekt erstellt?

**Comment by TobiasKrais** [comment]
Der dump gibt folgendes aus:
```
d2u_yrewrite_scheme {#98 ▼
    #suffix: "/"
}
```
Mein Schema ist gesetzt!
Wenn der Artikelname geändert wird, wird die URL nicht korrekt geändert.

**Comment by TobiasKrais** [comment]
Spannend: ich habe eine blanke Redaxo Installation aufgesetzt. Dort kann ich den Fehler nicht nachstellen.
Workaround: beim Speichern der Einstellungen im D2U Helper Addon erzwinge ich das neue Schema, lösche dann den Cache und generiere die Pfadliste in einem Rutsch neu (https://github.com/TobiasKrais/d2u_helper/blob/40c673ada987d6ddb488c9a10809516052f93153/pages/settings.php#L48). Dann klappt es.

**Comment by TobiasKrais** [comment]
Auch wenn der Issue geschlossen ist, habe ich noch eine sehr interessante Entdeckung gemacht: das Addon cookie_consent ist der Schuldige. Wird das Addon deaktiviert, funktionieren die chinesischen URLs korrekt!? Eventuell hat es was hiermit zu tun: https://github.com/FriendsOfREDAXO/cookie_consent/issues/89

**Comment by TobiasKrais** [comment]
Fehler behoben: https://github.com/FriendsOfREDAXO/cookie_consent/commit/92ae5cc7651220bd5b2ef2be48884fa01e5225b1
