### ISSUE TITLE
Domain: Eingabe der Artikel validieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#243]
Um den Nutzer vor einer fehlerhaften Konfiguration zu schützen, sollte der Nutzer durch eine Validierung daran gehindert werden, als Fehlerartikel den Mountpoint-Artikel oder den Startseiten-Artikel auswählen zu können.

Alternativ sollte der Nutzer davor gewarnt werden.

Infolge einer solchen fehlerhaften Konfiguration können Addons nicht ordnungsgemäß funktionieren. Das Problem gab es Mal mit search_it, aber es scheint auch sonst Mal zu unerwarteten Problemen zu kommen.

**Comment by dergel** [comment]
das stimmt.. und die Übrprüfung der Domain inkl. Protokoll passt auch noch nicht ganz

**Comment by dergel** [comment]
gerade gemacht .. issue war doppelt, passt also nun (sollte ;) )
