### ISSUE TITLE
Doku: redirect auch bei vorhandenen Artikeln ermöglichen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#247]
```
rex_yrewrite_forward::getForward(['domain'=>rex_yrewrite::getCurrentDomain(),'url'=>trim(rex_getUrl(rex_article::getCurrentId()),'/')]);
```
via @thielpeter in Slack, von mir ungetestet.

Peter, hast du das einfach ins Template gepackt?

**Comment by thielpeter** [comment]
Der Code kann so einfach in ein Template das früh eingehangen wird. So geht es glaub ich noch kompakter:

`rex_yrewrite_forward::getForward(['domain'=>rex_yrewrite::getCurrentDomain(),'url'=>trim(rex_getUrl(),'/')]);`

**Comment by alexplusde** [comment]
@dergel könnte man eine Option in YRewrite schaffen, die diese Zeile automatisch ausführt, falls gewünscht? Das würde die oftmals gewünschte Weiterleitung einer bestehenden URL vereinfachen, ohne sie verpflichtend einzusetzen.

**Comment by staabm** [comment]
das die url am ende keinen "/" haben darf, ist eine url-format frage, die je nach website anders zu beantworten ist, oder?

**Comment by alexplusde** [comment]
Es geht glaube ich nicht um das End-Slash, sondern um das führende Slash, um URLs wie diese zu vermeiden: `https://domain.de//mein-artikel/`

**Comment by dergel** [comment]
Wenn es um den Slack am Ende geht, sollte das mittlerweile automatisch erkannt werden. Mit anderen Worten, ist die vorhandene URL nicht vorhanden, wird zusätzlich nach Alternativen gesucht und in diesem Fall mit "/" am Ende.

**Comment by alexplusde** [comment]
Es geht um den zwischen Domain und Pfad.
