### ISSUE TITLE
Warning    Invalid argument supplied for foreach() - falsch konfigurierte Domains

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#252]
`Invalid argument supplied for foreach() redaxo/src/addons/yrewrite/lib/yrewrite.php 365` im Syslog, wenn man die Website unter einer Domain aufruft, die auf das Verzeichnis am Server zeigt, aber nicht in YRewrite angelegt ist.

Zum Reproduzieren:
1. Domain `xyz.de` in YRewrite anlegen 
2. Domain `abc.de` auf das Installationsverzeichnis zeigen lassen, jedoch nicht in YRewrite anlegen
3. `abc.de` aufrufen.

Die Seite kommt dann unter abc.de - was nicht sinnvoll ist, aber zumindest erstmal keinen Fehler zeigt - bis auf die Warning im Syslog.

Besser wäre es jedoch, auf bspw. die Fehler 404-Seite der ersten Domain weiterzuleiten - und im Syslog eine Info dazuzuschreiben, dass die Website von einer nicht hinterlegten Domain aufgerufen wurde und welcher - anstelle der Warning.

**Comment by alexplusde** [comment]
Der Fehler kommt dann in mehreren Zeilen vor:

14.01.2019 10:47:29 | Warning | Invalid argument supplied for foreach() | redaxo/src/addons/yrewrite/lib/yrewrite.php | 367
-- | -- | -- | -- | --
14.01.2019 10:47:29 | info | requested url: /ansichten.html |   |  
14.01.2019 10:47:29 | Warning | Invalid argument supplied for foreach() | redaxo/src/addons/yrewrite/lib/yrewrite.php | 337
14.01.2019 10:47:29 | Warning | Invalid argument supplied for foreach() | redaxo/src/addons/yrewrite/lib/yrewrite.php | 324

**Comment by skerbis** [comment]
```
16.12.2019 15:14:11 | Warning | Invalid argument supplied for foreach() | redaxo/src/addons/yrewrite/lib/yrewrite/yrewrite.php | 370
```

Version 2.6

**Comment by skerbis** [comment]
Immer noch, wie bekomme ich das weg @alexplusde  @dergel  
Anders als bei @alexplusde beschreiben sind die Domains serverseitig und in yrewrite korrekt eingetragen. 

<img width="1068" alt="Bildschirmfoto 2020-03-25 um 12 34 18" src="https://user-images.githubusercontent.com/791247/77532347-0158ca00-6e95-11ea-97f8-f1ef54c17300.png">

**Comment by skerbis** [comment]
Es scheint daran zu liegen, dass ich in der Hauptebene Kategorien habe, die keiner Domain zugewiesen sind. Füge eine Domain auf root hinzu, ist der Fehler weg.
