### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'PHP version >=5.5.9 needed!'

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#255]
```
Fatal error: Uncaught exception 'Exception' with message 'PHP version >=5.5.9 needed!' in /kunden/2019/redaxo/src/core/boot.php:15 Stack trace: #0 /kunden/2019/index.php(9): require() #1 {main} thrown in /kunden/2019/redaxo/src/core/boot.php on line 15
```
im Frontend und Backend

Aber erst nach aktivieren der YRewrite-`.htaccess`. Sollte das Aktivieren mit zu niedriger PHP-Version nicht von YRewrite unterbunden werden?

**Comment by gharlan** [comment]
Das verstehe ich noch nicht. Die Exception kommt ja aus der Core-boot.php, wenn die PHP-Version zu niedrig ist. 
Das heißt ja, dass irgendwie durch Anlegen der .htaccess von yrewrite sich die PHP-Version geändert hat?
Ggf. war vorher schon eine htaccess vorhanden, die eine andere PHP-Version gesetzt hat?

Ich sehe akuell jedenfalls nicht, was yrewrite hier tun kann.

**Comment by alexplusde** [comment]
> Ggf. war vorher schon eine htaccess vorhanden, die eine andere PHP-Version gesetzt hat?

Gut möglich. Exotischer Nischenhoster. Würde nicht von Profi sprechen. Weiß nicht mehr welches Projekt das war.
