### ISSUE TITLE
Wie bekomme ich Mehrsprachigkeit hin

### ISSUE THREAD

**Issue by ruerob** [yakamara/redaxo_yrewrite#257]
Ich hab ein Problem mit der Mehrsprachigkeit.

Ein Kunde hat eine Webseite, die von mehreren URLs aus aufrufbar sein soll.

Ich hab alsounter Domains eine Domain eingerichtet.
Diese hab ich mit der Startsprache englisch versehen. 

Die anderen Domains hab ich als Alias Domains eingebunden und die Startsprache entsprechend der gewünschten eingestellt.

Leider wird mir aber nach aufrufen der Aliase trotzdem bei allen Englisch angezeigt..

---

Mein zweiter Versuch war es, eine zweite Domain mit der Startsprache Deutsch anzulegen und von den deutschen Domain Aliasen darauf zu verweisen... Das hat aber auch nicht funktioniert...
Es wurde immer auf die englische Domain umgeleitet...

Hab ich ein Verständnisproblem? Mach ich was falsch? Kann mir wer helfen?

**Comment by alexplusde** [comment]
Hallo Ruerob,

evtl. ist es bloß ein kleines Konfigurations-Problem. Schreib uns mal im Slack-Channel:
https://redaxo.org/support/community/#slack

Jede Sprache muss auch als Domain angelegt werden - nicht als Alias-Domain. Wenn die Alias-Domains nur Weiterleitungen sein sollen, dann am besten direkt per .htaccess anlegen.

**Comment by dergel** [comment]
genau .. support und solche dinge im slack-Channel redaxo.org/slack
hier bitte nur änderungswünsche, fehler korrekturen etc..

**Comment by alexplusde** [comment]
gelöst in #256
