### ISSUE TITLE
Schnellnavigation : nur Struktur der Domain abbilden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#26]
In der Schnellnavigation am besten nur die Struktur der aktuellen Domain abbilden und neben den Titel "Strukturverwaltung" einen Domainswitcher anzeigen lassen.

Hintergrund. Die Schnellnavi kann stark anwachsen und wird dadurch sehr unübersichtlich. Auch geht die Performance der Seitenaufrufe nach unten.

**Comment by dergel** [comment]
klingt sinnvoll ... müssen aber noch überlegen ob der allgemein Strukturbaum das mit abdecken kann .. 
Aber prinzipiell wäre das sehr sinnvoll und übersichtlicher ..

**Comment by alexplusde** [comment]
Gibt es die klassische Schnellnavigation überhaupt noch?
