### ISSUE TITLE
Wunsch :: Weitere Ersetzungen von Zeichen > wie &

### ISSUE THREAD

**Issue by Geri2017** [yakamara/redaxo_yrewrite#261]
Wäre es möglich ein zusätzliches Eingabefeld für weitere Ersetzungen einzubinden? Getrennt nach Sprachen?
Z.B.: ‚&‘ => ‚und‘
Ist aber viel relevanter bei anderen Sprachen! Ich brauche im ungarischen viel mehr Ersetzungen.
Z.B.: ‚ő’ => ‘oe’ (langes ő mit zwei Strichen, statt Punkten) + ‘ű’ => ‘ue’, etc. 
Danke 🙏🏻

**Comment by tbaddade** [comment]
Das ginge u.a. so

```php
<?php

class rex_project_rewrite_scheme extends rex_yrewrite_scheme
{
    /**
     * @param string $string
     * @param int $clang
     *
     * @return string
     */
    public function normalize($string, $clang = 1)
    {
        $string = str_replace(
            ['&'],
            ['und'],
            $string
        );

        // Id 2 = ungarisch
        if ($clang == 2) {
            $string = str_replace(
                ['ő', 'ű'],
                ['oe', 'ue'],
                $string
            );
        }
        return parent::normalize($string, $clang);
    }
}
```

Eingabefelder wollen wir hier vermeiden, da man mit der Class viel spezifischer arbeiten kann.

**Comment by dergel** [comment]
kann man also selbst in einer eigenen schemaklasse lösen

**Comment by alexplusde** [comment]
Bitte offen lassen und docs-Label dran
