### ISSUE TITLE
Vorschau benutzerdefinierte URL nicht aktualisiert

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#262]
Szenario: in einem Artikel habe ich eine benutzerdefinierte URL. Diese entferne ich nun, klicke auf "Aktualisieren" und die Änderung wird gespeichert. Aber das Vorschaufeld wird nicht angepasst. Es steht immernoch die benutzerdefinierte URL drin.
Erst wenn die Seite neu geladen wird, wird das Vorschaufeld aktualisiert.

**Comment by gharlan** [comment]
Das Problem besteht nicht mehr.
