### ISSUE TITLE
sitemap.xml je Sprache

### ISSUE THREAD

**Issue by brandes-webdesign** [yakamara/redaxo_yrewrite#264]
Ich würde gerne für eine mehrsprachige Webseite die sitemap.xml je Sprache einzeln haben, also z.B. 
sitemap_de.xml, sitemap_en.xml, sitemap_fr.xml, .....

Vielleicht ist das ja mit geringen Aufwand zu realisieren ?

DANKE schon einmal im vorraus.

**Comment by dergel** [comment]
sowas kannst du selbst gut lösen. Einfach die htaccess anpassen und die Sitemaps generieren. Ich sehe die Unterscheidung nicht in yrewrite selbst. lg

**Comment by alexplusde** [comment]
Die Unterscheidung pro Domain (nicht pro Sprache) ergibt schon Sinn, um Dienste wie die Google Search Console damit zu füttern.

**Comment by dergel** [comment]
klar. Aber alleine das mit den Namen und Aufschlüsselung nach Sprachen/Countries/Code braucht ein bischen mehr als nur die sitemap aufzuschlüsseln. deswegen eher individuell als über yrewrite selbst

**Comment by alexplusde** [comment]
@brandes-webdesign kannst du dir eine Lösung organsieren, dann könnte man sie in die Doku einarbeiten.
