### ISSUE TITLE
R5.7 Kategorie verschieben bei automatischer Weiterleitung macht ooops

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yrewrite#265]
Nachvollziehbar, auf verschiedenen Installationen getestet:
Wenn die automatischen Redirects aktiviert sind und eine Kategorie verschoben wird, gibt es einen ooops:

TypeError thrown with message "Argument 2 passed to rex_yrewrite_scheme::getClang() must be an instance of rex_yrewrite_domain, null given, called in \hostingredaxo\src\addons\yrewrite\lib\yrewrite.php on line 507"

Stacktrace:
#9 TypeError in \hostingredaxo\src\addons\yrewrite\lib\scheme.php:37
#8 rex_yrewrite_scheme:getClang in \hostingredaxo\src\addons\yrewrite\lib\yrewrite.php:507
#7 rex_yrewrite:generatePathFile in \hostingredaxo\src\addons\yrewrite\boot.php:44
#6 rex_package:{closure} in \hostingredaxo\src\core\lib\extension.php:45
#5 rex_extension:registerPoint in \hostingredaxo\src\addons\structure\lib\service_category.php:546
#4 rex_category_service:moveCategory in \hostingredaxo\src\addons\structure\lib\api_functions\api_category_move.php:24
#3 rex_api_category_move:execute in \hostingredaxo\src\core\lib\api_function.php:178
#2 rex_api_function:handleCall in \hostingredaxo\src\core\backend.php:202
#1 require in \hostingredaxo\src\core\boot.php:135
#0 require in \hostingredaxo\index.php:9

Folgender Patch behebt das Problem:

yrewrite.php Zeile 500 ff:
```
                rex_article_cache::delete($params['id']);
                if (!isset($params['clang']) && isset($params['clang_id'])) {
                    $params['clang'] = $params['clang_id'];
                }
                $domain = self::$domainsByMountId[0][$params['clang']];

```
Wenn ich das richtig interpretiere, liefern unterschiedliche Extensionpoints unterschiedliche Werte für die Sprache (clang, respektive clang_id).

**Comment by staabm** [comment]
Heute erneut im slack gemeldet

**Comment by f5alex** [comment]
> Heute erneut im slack gemeldet
Jupp! das war ich...
Kann aber bestätigen, dass der Patch funktioninert!

**Comment by LAnnika** [comment]
Der Fehler kommt auch ohne eingerichtete Weiterleitungen, mit "unkonfiguriertem" yrewrite in der aktuellsten Version, wenn eine Kategorie verschoben wird.

**Comment by alexplusde** [comment]
> unkonfiguriertem

du meinst eins ohne Domain? Da gibt's auch sonst mal merkwürdige Effekte.

**Comment by LAnnika** [comment]
Auch mit Domain ohne automatischer Weiterleitung ist es nicht möglich OHNE Fehlermeldung eine Kategorie zu verschieben.

**Comment by tbaddade** [comment]
@staabm @gharlan Sollte der Core hier nicht die EP-Params anpassen und vereinheitlichen?

**Comment by staabm** [comment]
@tbaddade worauf willst du hinaus? Welche EPs und was soll vereinheitlicht werden?

**Comment by tbaddade** [comment]
Die EP 
```
'ART_ADDED', 'ART_DELETED', 'ART_MOVED', 'ART_STATUS', 'ART_UPDATED',
'CAT_ADDED', 'CAT_DELETED', 'CAT_MOVED', 'CAT_STATUS', 'CAT_UPDATED',
```

liefern unterschiedliche ParamKeys. Mal `clang` mal `clang_id`

**Comment by staabm** [comment]
Hmmm kommt mir bekannt vor.. hatten wir das schonmal irgendwo diskutiert/als issue erfasst?

Prinzipiell seh ich aus dem bauch heraus erstmal kein problem es zu vereinheitlichen , solange wir BC erhalten

**Comment by tbaddade** [comment]
Der Fehler kommt ab 5.7.0 da erst hier der EP CAT_MOVED hinzugekommen ist.

**Comment by staabm** [comment]
Ich bin jetzt mal den rex core durchgeflogen. Ich hab nur eine stelle gefunden wo es clang_id heißt und das ist der neue CAT_MOVED
Bei allen anderen EPs in article_service bzw. category_service scheint es konsistent „clang“ zu sein.

Zu welcher stelle wolltest du konsistent sein als du in https://github.com/redaxo/redaxo/pull/2238#issuecomment-443607238 das clang_id vorgeschlagen hast?

**Comment by cukabeka** [comment]
Kann ich so bestätigen, bekomme ich auch, wenn ich eine Kategorie von einer Domain in eine andere verschieben will.

**Comment by cukabeka** [comment]
Hm, sie ist zwar verschoben, aber die URL fürs Frontend ist nicht korrekt, sondern zeigt noch auf den alten Pfad.

**Comment by alexplusde** [comment]
@cukabeka übergangsweise die Kategorie nochmal editieren, dann müsste die url wieder passen.

**Comment by IngoWinter** [comment]
Ich habe den Bug auch gerade gefunden :)

**Comment by cukabeka** [comment]
Willkommen im Club 😄

**Comment by dpf-dd** [comment]
Jawoll, ich reihe mich ein in die Entdeckerliste :)

**Comment by alexplusde** [comment]
Ist eigentlich kein Zustand ...

**Comment by Geri2017** [comment]
Ich bin jetzt auch im Club, nachdem mich gestern Daniel W. auf diesen Issue aufmerksam gemacht hat. 
Gleiches Problem: Verschieben einer Kategorie. 
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1560197340251700

**Comment by skerbis** [comment]
Eben getestet .. auch hier der Fall

**Comment by alexplusde** [comment]
Beim Ändern des Seitentitelschemas soll das Problem laut @pgmrrobot auch vorkommen.

@dergel @gharlan ping

**Comment by gharlan** [comment]
Die Ursache werde ich in der 5.8 beheben: https://github.com/redaxo/redaxo/pull/2843
Sollten wir hier dann trotzdem den Workaround reinnehmen, auch wenn er sich mit der 5.8 erübrigt?

**Comment by alexplusde** [comment]
Finde schon, da du das Add-on auch an anderer Stelle (min PHP-Version) noch für alte REDAXO-Versionen kompatibel hältst. Und ein Core-Update mehr Vorbereitung benötigt als nur ein Add-on zu aktualisieren.

**Comment by alexwenz** [comment]
Das Problem ist mit 5.8 behoben. Gerade getestet.

Vielen Dank!!
