### ISSUE TITLE
Parameter Abfrage, wenn kein Trailing Slash vorhanden ist

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_yrewrite#266]
Hey,

ich hab gerade beim Testen einer Seite folgendes Phänomen gehabt:

1. Aufruf der Seite ohne Trailing Slash
2. Trailing Slash + Fragezeichen werden angehängt

Eingabe: ../formular
wird zu: ../formular/?

Gebe ich die Url mit Trailing Slash an, wird sie wie gewünscht ohne Parameter ausgegeben. Passiert ist mir das jetzt bei der aktuellen Version 2.5.

Ich hab es anschließend nochmal in der 2.4 getestet, da war das noch nicht der Fall. Gibt es da einen Ansatzpunkt?

**Comment by alexplusde** [comment]
htaccess modifiziert? Könnte was vom Hoster dabei sein? Hängt es wirklich mit dem Update zusammen?

**Comment by pschuchmann** [comment]
Hab eben nochmal auf 2.5 geupdated und die .htaccess aus dem Setup Ordner genommen, gleiches Spiel.

**Comment by Hirbod** [comment]
Kann ich reproduzieren, eben das gleiche Problem gehabt. Bin auf nginx, weiss nicht, ob es daran liegt.

**Comment by tbaddade** [comment]
Könnte an diesem Commit liegen https://github.com/yakamara/redaxo_yrewrite/commit/ec1397369893664434759dce315641cd54879758

**Comment by Hirbod** [comment]
Vermutlich ist `isset($_SERVER['QUERY_STRING'])` nicht sicher genug in der Abfrage

**Comment by Hirbod** [comment]
QUERY_STRING ist im Default `string(0) ""` und damit `true` bei der isset() Abfrage. Hier müsste zusätzlich wohl auf Leerstring getestet werden

**Comment by Hirbod** [comment]
PR ist raus

**Comment by Hirbod** [comment]
Mir ist ein weiterer Bug in diesem Zusammenhang aufgefallen

`/datenschutz?a=b` wird zu `/datenschutz/?a=b&a=b`

**Comment by Hirbod** [comment]
@gharlan siehe meine letzte Meldung noch hierzu. Ggf kannst das gleich mitfiebern?

**Comment by Hirbod** [comment]
Mitfixen
