### ISSUE TITLE
Weiterleitungen: mehr Zeichen für aufgerufene Url erlauben

### ISSUE THREAD

**Issue by tema-web** [yakamara/redaxo_yrewrite#267]
Wenn ich eine URL wie

>  frontend/unternehmen/3,0.html?language=fr 

weiterleiten möchte, schlägt das validate zu verhindert das ( _Nur "a-z/0-9 -"_). 
"**,**" / "**?**" / "**=**" / "**&**" sollten auch zugelassen sein, um URL-Parameter anderer Systeme mit abzufangen. 
Ein "," hab ich so vorher auch noch nicht in einer URL gesehen, man lernt halt nie aus ;-)

**Comment by dergel** [comment]
Die Kommas haben in der Überprüfung noch gefehlt und sind nun möglich, aber nur hier bei Weiterleitungen, weil hier auch URLs möglich sein müssen, die nicht ideal sind. Der Querystring wird nicht als URL betrachtet. Also ? ist demnach nicht erlaubt

**Comment by alexplusde** [comment]
Dann bitte ein zusätzliches Feld für einen Query-String.
