### ISSUE TITLE
Domains plötzlich mit www.

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#269]
Dieser Code
```
        foreach(rex_yrewrite::getDomains(true) as $domain => $object) {
            $domains[$domain] = $domain;
        } 
```

gab bisher die Domains ohne `www.` aus, jetzt mit `www.` Dadurch bekomme ich Probleme beim DSGVO-Addon, da nun plötzlich die Domains nicht mehr stimmen. Kann man das Verhalten im Sinne der BC zurückändern?

**Comment by staabm** [comment]
zwischen den zeilen ist zu lesen, dass du ein update von yrewrite gemacht hast und dadurch das problem gekommen ist.

von welcher version auf welche haste denn aktualisiert?

**Comment by alexplusde** [comment]
das dürfte 2.4 auf 2.5 gewesen sein. (2.5 auf jeden Fall, mein Kollege hat geupdatet)

**Comment by dergel** [comment]
Verstehe das Problem nicht. Die Domain sollten immer exakt der vorhandenen Liste sein ?

**Comment by alexplusde** [comment]
Das Problem war, dass unvermittelt der Wert verändert wurde, der ausgegeben wurde. Aber jetzt ist es eh zu spät und ist ja auch scheinbar niemandem aufgefallen.
