### ISSUE TITLE
Weiterleitungen mit unterschiedlicher Großschreibung

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yrewrite#274]
yrewrite lässt es nicht zu, doppelte Weiterleitungen zu definieren, auch wenn sich diese Weiterleitungen in der Groß/Kleinschreibung unterscheiden.
Beispiel:
Es ist eine Weiterleitung der URL
`carsharing`
angelegt.
Dann ist es nicht möglich, Weiterleitungen der URL
`Carsharing`
oder
`carSharing`
anzulegen.

Da yrewrite diese URLs aber nicht abfängt und einen 404 zeugt, sollte es m.E. erlaubt sein, diese sich in der Großschreibung unterscheidenden Weiterleitungen zu definieren.

**Comment by tbaddade** [comment]
Sollen diese Urls auf denselben Artikel weiterleiten oder willst du unterschiedliche Artikel angeben?

**Comment by alexplusde** [comment]
Möchte hier auch nochmal nachfragen: Erwartetes Verhalten wäre für mich, dass yrewrite URLs grundsätzlich case_insensitive behandelt, also eine Weiterleitung von `carsharing` auch unter `carSharing` oder `cArShArInG` ausführt.
