### ISSUE TITLE
Fehler beim Verschieben in Hauptebene

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_yrewrite#275]
Hey,

ich habe eben versucht eine Kategorie auf die Hauptebene zu verschieben, dabei habe ich einen schönen Whoops produziert. Sobald YRewrite deaktivert ist, funktioniert alles wie gehabt. Version ist die 2.5.

![grafik](https://user-images.githubusercontent.com/35096518/56119022-83453100-5f6b-11e9-8950-7efc560d216f.png)

**Comment by staabm** [comment]
vermutlich ein duplikat von https://github.com/yakamara/redaxo_yrewrite/issues/265

**Comment by pschuchmann** [comment]
Ja, my bad.
