### ISSUE TITLE
Aufruf von rex_yrewrite_forward::generatePathFile() kann zu internem Serverfehler führen

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#279]
Der Aufruf von `rex_yrewrite_forward::generatePathFile()` kann zu einem internen Serverfehler, da `self::$pathfile` unter Umständen nicht initialisiert ist. Eine Lösung könnte so aussehen:
```php
    public static function generatePathFile()
    {
    	if(self::$pathfile == '') {
    		self::init();
    	}
        $gc = rex_sql::factory();
        $content = $gc->getArray('select * from '.rex::getTable('yrewrite_forward'));
		rex_file::put(self::$pathfile, json_encode($content));
    }
```
Wenn der Lösungsweg so gewünscht ist, kann ich ihn als PR zur Verfügung stellen. Vermutlich sind die anderen Methoden der Klasse vom selben Bug betroffen.

**Comment by gharlan** [comment]
Aus meiner Sicht sollte man so oder so erst die Initialisierung abwarten, und somit erst ab `PACKAGES_INCLUDED` mit den Yrewrite-Klassen hantieren.
