### ISSUE TITLE
Rotbot-Regeln verbessern

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#283]
Noindex mit follow ermöglichen
Noarchive ermöglichen

Passend dazu: 
https://github.com/yakamara/redaxo_yrewrite/issues/215

Ich schlage folgende Optionen vor

**Die  Seite soll nicht indexiert, und allen Links nicht gefolgt werden:**
`<meta name="robots" content="noindex, nofollow">`

**Links auf dieser Seite soll nicht gefolgt werden**
`<meta name="robots" content="nofollow">`

**Links der Seite soll gefolgt werden, allerdings soll die Seite nicht indexiert werden**
`<meta name="robots" content="noindex">`

Zusätzlich wäre noch noarchive als zusätzliche Option interessant

**Comment by alexplusde** [comment]
Dann sollte man mit Checkboxen arbeiten können statt einem select und jede Option einzeln wählen können.

**Comment by skerbis** [comment]
Das sind die gängigen Optionen soweit ich es überblicken kann. 
Das noarchive könnte als checkbox realisiert werden.

**Comment by alexplusde** [comment]
Ich meinte für nofollow, noindex, noarchive einzelne Checkboxen

**Comment by skerbis** [comment]
Das habe ich verstanden, würde aber mehr Platz brauchen.

**Comment by skerbis** [comment]
**Kurz noch als  Ergänzung** 

> **Interne Links mit Nofollow** auszuzeichnen sollte man **besser vermeiden**, da in diesem Fall kein Link Juice vererbt wird. Immer wieder verwenden Webmaster Nofollow-Links um die interne Linkanzahl je Webseite vermeintlich zu verringern. Jedoch werden diese Nofollow-Links von Suchmaschinen weiterhin zur gesamten Linkanzahl gezählt und vererben keine Link Power an die Zielseite.

Quelle: https://de.ryte.com/magazine/vorsicht-diese-fehler-solltest-du-bei-internen-links-unbedingt-vermeiden

**Comment by alexplusde** [comment]
Quelle ist von 2015 - ist das noch so gültig?

**Comment by skerbis** [comment]
Es gibt auch neuere Quellen die das so sehen.

**Comment by skerbis** [comment]
https://www.seo-suedwest.de/1577-kein-nofollow-interne-links-verwenden.html
 
https://de.ryte.com/magazine/vorsicht-diese-fehler-solltest-du-bei-internen-links-unbedingt-vermeiden
 
https://www.seokratie.de/indexierung/

**Comment by pschuchmann** [comment]
Wäre auf jeden Fall ein schönes Feature!

**Comment by alexplusde** [comment]
mit #341 gelöst?

Wann brauchst du `noarchive` @skerbis ?

**Comment by skerbis** [comment]
@alexplusde 
noarchive = 
Keinen im Cache gespeicherten Link in den Suchergebnissen anzeigen

Google erstellt einen cache / archiv , das möchte man ggf. vermeiden.

**Comment by skerbis** [comment]
Ich close das mal
