### ISSUE TITLE
Multidomain "vergisst" name, MountId und Id

### ISSUE THREAD

**Issue by dtpop** [yakamara/redaxo_yrewrite#287]
In einer Multidomaininstallation mit zwei definierten Domains wird im Template vor allen Ausgaben  mit `dump(rex_yrewrite::getCurrentDomain())` die aktuelle Domain abgefragt.
Nach dem Editieren eines Artikels sind die Werte für Id und mountId nicht gesetzt. Auch der name ist falsch. Cache löschen hilft, und die Werte sind wieder da. Das Errorlog ist leer.
PHP: 7.2 und 7.3. Kein Strato oder sonst irgendein dubioses Hosting. In der Entwicklungsumgebung ist alles ok.
![Unbenannt](https://user-images.githubusercontent.com/1282121/61548964-32a01100-aa4f-11e9-881a-fd0d7c1f000f.JPG)
Sorry dass ich nicht zu einer Lösung beitragen kann. Ox:Berg.

**Comment by dtpop** [comment]
Weitere Recherchen ... möglicherweise hat es mit einem eigenen Rewrite Scheme zu tun. Jedenfalls wird unter noch nicht herausgefundenen Umständen eine zusätzliche Domain "default" im Pathfile angelegt. Die dort eingetragenen Artikel sind aber bereits in den korrekten Domains enthalten. Dies passiert auch in der Entwicklungsumgebung. Es betrifft aber irgendwie andere Artikel als auf dem Webserver.
![Unbenannt](https://user-images.githubusercontent.com/1282121/61551745-49963180-aa56-11e9-96fb-94d2296fd3c3.JPG)

**Comment by dtpop** [comment]
#288 behebt den Fehler erstmal.
`$domain = self::$domainsByMountId[0][$params['clang']];` kann in einer Multidomainumgebung nicht das richtige Domainobjekt zurückgeben.

**Comment by dtpop** [comment]
Patch behebt zwar das Problem, schafft aber neue.

**Comment by gharlan** [comment]
Die "default"-Domain sollte eigentlich nur auftreten, wenn es Artikel/Kategorien gibt, die keiner Domain zugeordnet sind.
Und jede Artikel-Sprach-Kombi sollte immer nur in genau einer Domain sein. 
Somit ist bei dir oben auf jeden Fall was falsch in der Pathlist.

Große Frage ist nun, wie es denn dazu kommt.

**Comment by gharlan** [comment]
Ich konnte das gestern Abend noch nachstellen, indem ich Kategorien verschoben habe.
Also wenn man eine Kategorie von einem Domain-Bereich in einen anderen (oder einen ohne Domain, sprich "default") schiebt, dann ist die Kategorie beiden Domains zugeordnet, bis man den Cache nochmal ganz löscht.
Das kann ich mir auch erklären, wieso es so ist. [Diese Logik](https://github.com/yakamara/redaxo_yrewrite/blob/fa382b7f92ddde2cdad8be21b5304b1096d1b256/lib/yrewrite.php#L490-L496), um den alten Pfad rauszulöschen, muss auch beim EP CAT_MOVED greifen (und bei ART_MOVED).

Ich werde mir das nochmal weiter anschauen. Aber @dtpop kann es sein, dass es bei dir auch durch Verschieben von Kategorien zu dem Kuddelmuddel kam? Oder vermutest du, dass es noch andere Ursachen geben muss?

**Comment by dtpop** [comment]
Ja, bei mir hat es gereicht in den Metainfos etwas zu ändern. Ich konnte das nachvollziehen am Extensionpoint ART_META_UPDATED

**Comment by gharlan** [comment]
Und hast du eine Online-Version, wo das für dich reproduzierbar ist?
Also Pathlist passt, Metainfos ändern, Pathlist ist falsch?

Falls ja, wäre es vielleicht möglich mir dazu Rex- und FTP-Zugang zu geben?

**Comment by gharlan** [comment]
Bei @dtpop war die `path`-Spalte in der `rex_article`-Tabelle teils falsch gesetzt, und das war die Ursache hierfür.
Zu lösen ist aber noch, was ich oben herausgefunden habe zu CAT_MOVED.
