### ISSUE TITLE
Funktion rex_getFullUrl()

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#29]
Analog zu rex_getUrl nur eben mit kompletter Domain / Scheme / Host etc. vorne dran.

Hier kommt eine falsche Domain heraus
```
    $link = $REX['SERVER'] . rex_getUrl('', '', array('id' => $id));
    echo $link;
    // undefined/de/article.html?id=1
```

richtig wäre es so
```
    $link = rex_getUrl('','',array('news_id'=>$news_id));
    $link = substr($link, 1);
    $link = rex_yrewrite::getFullPath($link);
    echo $link;
    // http://www.domain.de/de/article.html?id=1
```

ist aber zu umständlich

**Comment by gharlan** [comment]
@tbaddade ist das noch aktuell? Es gibt ja zum Beispiel `rex_yrewrite::getFullUrlByArticleId()`..

**Comment by tbaddade** [comment]
@gharlan Ich denke das die Methode durch dieses Issue entstanden sein könnte. Daher schließe ich mal.
