### ISSUE TITLE
Fehler beim Ändern des Domainnamens

### ISSUE THREAD

**Issue by rolandsee** [yakamara/redaxo_yrewrite#294]
Ich habe eben meine lokale DB mit den Daten einer DEV-DB aktualisiert und wollte in YRewrite den Domainnamen auf "http://localhost" setzen. Das wurde mit folgendem Fehler quittiert:

**_[translate:domain_not_well_formed]**

> Domain 
> https://localhost
> http/https ist optional. Wenn man es angibt, leiten alle Links immer auf das angegebene Protokoll. Lässt man es weg, wird das jeweils aktuelle verwendet. Slash am Ende oder nicht ist egal, das wird vom AddOn normalisiert. "www" muss angegeben werden, wenn denn die Domain mit "www" genutzt wird. Für YRewrite ist es eine normale Subdomain. Läuft REDAXO in einem Unterordner, muss dieser mit notiert werden. Beispiel: http://domain.de/unterordner/_

Der Domainname wurde nicht geändert.

**Comment by dergel** [comment]
ist verbessert worden.
