### ISSUE TITLE
Fehler in Ersetzungstabelle

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yrewrite#295]
Nach dem Update von 2.5 auf 2.6b2 werden 'Ü' nicht mehr durch 'Ue' ersetzt, sondern lediglich durch 'U'. Grund ein Fehler in der Ersetzungstabelle der normalize Funktion:
https://github.com/yakamara/redaxo_yrewrite/blob/9f45113656279e4f7a1a1e2de619809f5dfd5560/lib/yrewrite/scheme.php#L128
https://github.com/yakamara/redaxo_yrewrite/blob/9f45113656279e4f7a1a1e2de619809f5dfd5560/lib/yrewrite/scheme.php#L129

**Comment by dergel** [comment]
ist zurückgesetzt.
