### ISSUE TITLE
Seo Klasse umbauen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#296]
Hintergrund ist, dass zum Bsp das Url-Addon gerne von außen verschiedene Elemente füttern mag.

Eine Variante wäre mittels ExtensionPoints, die vom @lexplatt hier im PR vorgeschlagen wurde
https://github.com/yakamara/redaxo_yrewrite/pull/276/commits/caf8c6e75a62b763c5940305270855301371665a

Eine Andere und flexiblere wäre die, wenn man die Seo Klasse wie die Scheme Klasse aufbaut, einbindet und registriert.

**Comment by dergel** [comment]
Alle Tags in ein Array .. nur noch ein getTags Aufruf.. Alte EPs raus und einen einzigen EP für den getTags setzen
