### ISSUE TITLE
404 bei rex_api call im Backend: 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#298]
```https://domain.tld/index.php?rex-api-call=sked_exchange&_csrf_token=buE2OyqR95tXzAFw2LkLFrMnzr-GCvGwfUub9PH-dH4&start=2019-08-26&end=2019-10-07```

erzeugt jetzt ein 404 in SKED. Der Aufruf erfolgt vom Backend aus.  Ein Aufruf direkt im Browser funktioniert einwandfrei

**Comment by skerbis** [comment]
Folgende URL scheint so nicht mehr zu funktionieren: 
https://github.com/FriendsOfREDAXO/sked/blob/42c989f35253c6ebb5f5c1b4ed017d46a32d5acd/assets/sked.js#L501

**Comment by alexplusde** [comment]
Subdomain korrekt?

**Comment by skerbis** [comment]
Ja

**Comment by dergel** [comment]
nun endlich nachgesehen.. so ganz falsch ist das nicht was yrewrite macht, nur anders als vorher. Jetzt sagt YRewrite: diese Seite kenne ich nicht, daher ist das eine 404 und setzt entsprechend den Status.

Richtigerweise müsste nun die sked api an der Stelle den Status neu auf 200 setzen .. `rex_response::setStatus(rex_response::HTTP_OK); 
`
dann sollte alles wieder passen.

**Comment by gharlan** [comment]
Wobei man schon auch überlegen könnte, ob yrewrite bei `rex-api-call`-Aufrufen nicht sagen sollte "oh, da bin ich wohl nicht zuständig, also halte ich mich raus".

Zu berücksichten ist aber, dass api-calls auch bewusst auf Artikel abgesetzt werden können, also `domain.tld/mein/artikel/pfad/?rex-api-call=...`, da wäre yrewrite dann natürlich schon wieder nicht ganz raus, denn die Artikel-URL müsste yrewrite dann natürlich schon behandeln.

Daher nicht so einfach, was hier denn das richtige Verhalten ist.

**Comment by gharlan** [comment]
Da fällt mir gerade ein, was passiert denn, wenn man statt `domain.tld/index.php?rex-api-call=...` das hier aufruft: `domain.tld/?rex-api-call`?
Dann müsste yrewrite es doch als Startartikel interpretieren, und dürfte kein 404 mehr werfen?

Was mich zur Frage bringt, ist es denn wirklich richtig, dass yrewrite bei `domain.tld/index.php` ein 404 wirft? Würde da eher die Startseite erwarten, entweder direkt, oder per Weiterleitung?

**Comment by skerbis** [comment]
Werde ich gleich mal testen. Finde aber auch das die index.php als Startseite interpretiert werden sollte. Es gibt noch mehr szenarien wo die index.php aufgerufen wird.

**Comment by gharlan** [comment]
Umleitung könnte aber problematisch sein, gerade weil man über die index.php ja wenn eher irgendwelche anderen Addons oder Api-Calls versucht aufzurufen, oder?

Status 200 mit canonical-Tag ist aber auch nicht ganz unproblematisch, aus dem selben Grund, weil eben gerade öfters gar nicht der Inhalt der Startseite dann kommt, sondern irgendein anderer Content (des Api-Calls o.ä.). Der canonical-Tag würde dann was falsches vermitteln.

**Comment by alexplusde** [comment]
> sondern irgendein anderer Content (des Api-Calls o.ä.)

...der dann auch nicht mehr den canonical-Tag enthält

**Comment by gharlan** [comment]
Du hast Recht, gedanklich war ich bei einem HTTP Header, obwohl ich auch "Tag" geschrieben habe.

**Comment by dergel** [comment]
lange mit gregor geredet und wir wissen keine perfekte Lösung. Im Prinzip kann man es aber so lassen wie es ist. Ich sage jetzt "einfach": Wenn yrewrite verwendet wird, ist index.php eine nicht auffindbaren Seite und daher 404. Wenn rex-api-call verwendet wird, wird bei einer nicht auffindbaren Seite der Status entsprechend gesetzt. D.h. man sollte, wenn man das nicht möchte, in seiner API Klasse den Status nach den eigenen Vorstellungen setzen. Dennoch verschiebe ich das issue erstmal

**Comment by skerbis** [comment]
Heißt das, dass `index.php?rex_media_type=MediaTypeName&amp;rex_media_file=MediaFileName`
nun auch zu einem 404 führt oder ist das nicht der Fall? 
Ich möchte nur noch mal drauf hinweisen, weil es noch ne ganze Menge andere AddOns gibt, die die index.php aufrufen.

**Comment by dergel** [comment]
das führt zu keinem Fehler, da dieser Aufruf nicht bis dahin durchgeschleift wird.
Grundsätzlich kann sowas aber zu einer Statusänderung führen, die man, wenn nötig, zurücksetzen müsste.

**Comment by alexplusde** [comment]
Ich stimme @dergel da zu. Es ist etwas, das bei der Nutzung der API immer berücksichtigt werden sollte. Das komplexe Tutorial bei FOR erwähnt das sogar auch, wenn ich mich nicht täusche - aber vielleicht sollte man nochmal ein "Minimal Setup" als Beispiel für eine rex_api-Anfrage formulieren, in der gleich auf den Status hingewiesen wird.

Unabhängig davon: die index.php ohne rex_api-Parameter sollte schon irgendwas machen, oder? (separates Issue?)

**Comment by dergel** [comment]
ja, separates issue..

**Comment by skerbis** [comment]
Auch die Minibar hat damit ein Problem https://github.com/FriendsOfREDAXO/minibar/pull/60
