### ISSUE TITLE
$article->isPermitted() nutzen anstatt eine eigene Logik

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#299]
heisst, weg vom EP YREWRITE_ARTICLE_PERM und solchen Dinge self::checkArticlePerm($article)

sondern direkt die redaxo isPermitted Methode verwenden

**Comment by gharlan** [comment]
https://github.com/yakamara/redaxo_yrewrite/commit/6b00d061a4f6a475c8044c8043f89ce1fc06771a
