### ISSUE TITLE
Sitemap.xml / xml-sitemap.xsl: HTTP Quellen und Wordpress YOAST Hinweis

### ISSUE THREAD

**Issue by godsdog** [yakamara/redaxo_yrewrite#302]
In der `assets/addons/yrewrite/xsl-stylesheets/xml-sitemap.xsl` werden die JS Quellen noch mit http eingebunden. Werden also wegen Mixed Content blockiert.

```
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="http://tablesorter.com/jquery.tablesorter.min.js"></script>
```

Auch befindet sich noch der Hinweis auf Wordpress YOAST SEO im Code :)
```
<p class="expl hidden">
 Generated by <a href="http://yoast.com/">Yoast</a>'s WordPress SEO plugin, this is an XML Sitemap, meant for consumption by search engines.
</p>
```

**Comment by dergel** [comment]
ich hatte das aus einem PR übernommen und zu wenig geprüft.. Wird korrigiert. Den Tablesorter und damit auch JQuery nehme ich raus. Denke, das ist nicht nötig und verkompliziert den Aufruf

**Comment by dergel** [comment]
Danke für den Hinweis
