### ISSUE TITLE
yRewrite 2.6 Port nicht möglich

### ISSUE THREAD

**Issue by fietstouring** [yakamara/redaxo_yrewrite#303]
habe in meiner lokalen Umgebung Ports angegeben wie z.B. meinedomain.test:7888 
seit 2.6 lässt mich yreWrite das nicht mehr speichern im Backend. 
Absicht?

![Bildschirmfoto 2019-09-27 um 10 17 46](https://user-images.githubusercontent.com/1846849/65754448-61063080-e111-11e9-992d-3416f79311db.png)

**Comment by dergel** [comment]
Also ohne Ports gehts wieder .. Mist, das wurde wohl einfach bei der Validierung übersehen. Wird korrigiert.

Bis dahin diese Zeile entfernen

**https://github.com/yakamara/redaxo_yrewrite/blob/master/pages/domains.php#L31**

**Comment by schuer** [comment]
Vielleicht in der aktuellen 2.7b2 noch fixen? :)
