### ISSUE TITLE
Bei Domains mit subfolder stimmt die sitemap nicht

### ISSUE THREAD

**Issue by 191977** [yakamara/redaxo_yrewrite#306]
Hi, 
ich bin mir jetzt nicht ganz sicher ob das so nicht sogar mit Absicht ist, weil eine sitemap zunächst mal wahrscheinlich die komplette Struktur einer damain darstellen sollte (?). 
Jedoch wird in meinem Fall mit einer Installation in einem Subfolder eine sitemap.xml mit falschen urls ausgeliefert:
![grafik](https://user-images.githubusercontent.com/47699885/66559385-9bca8880-eb55-11e9-95ee-9df33bf817ed.png)
Das subfolder wird nicht berücksichtigt. 
Weiss nicht ob es etwas damit zu tun hat, das ist aber auch schon im Setup so dargestellt:
![grafik](https://user-images.githubusercontent.com/47699885/66559494-c1579200-eb55-11e9-914b-145eb2ce79b2.png)

**Comment by mmt-buende** [comment]
in der  seo.php müsste es in Zeile 256 geändert werden:

ALT:
` "\n".'<loc>'.rex_yrewrite::getFullPath($path[$clang_id]).'</loc>'.`

NEU:						  
`"\n".'<loc>'.rex_yrewrite::getFullUrlByArticleId($article_id,$clang_id).'</loc>'.`

...hatte gerade das gleiche Problem.

**Comment by alexplusde** [comment]
Hey @mmt-buende, danke für deine Beteiligung! Bist du auch im Slack-Channel von REDAXO?

@dergel möchtest du einen Pull Request mit der vorgeschlagenen Änderung? Dann würde ich @mmt-buende anbieten, ihn beim Einreichen der Änderung zu unterstützen...

**Comment by mmt-buende** [comment]
Guten Morgen @alexplusde  
>Bist du auch im Slack-Channel von REDAXO?
Nein - Ich hatte mich hier nur angemeldet, weil ich Redaxo sehr gerne nutze und keine Lösung gefunden hatte und meine nicht für mich behalten wollte ^^ 
Würde im Rahmen meine Möglichkeiten (bin nicht der große PHP Kenner - Ich programmiere mit Perl) bei der Änderung helfen - Muss aber dazu sagen, dass ich mich mit "Slack" überhaupt nicht auskenne.

Gruß
Michael

**Comment by alexplusde** [comment]
@mmt-buende schreib mir doch Mal eine Mail (siehe Profil)

LG

**Comment by gharlan** [comment]
Bin mir nicht ganz sicher, aber ich glaube, ich sehe den Bug eher in `rex_yrewrite::getFullPath`.
Also der Fix oben löst es zwar, weil die Funktion umgangen wird, aber eigentlich müsste eher die Funktion gefixt werden.
