### ISSUE TITLE
Seo Sitemap erweitern via EP

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#31]
Wäre fein, wenn man via EP die Seo Sitemap erweitern könnte.

Siehe auch
https://github.com/tbaddade/redaxo_plugin_url_control/issues/8

**Comment by olien** [comment]
:+1:

**Comment by dergel** [comment]
@tbaddade kannst du schauen wo das hin muss ?

**Comment by dergel** [comment]
sehe ich das richtig, das du es bereits eingebaut hast ? .. dann bitte das issue hier schliessen
