### ISSUE TITLE
Warning beim Leeren des Cache

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yrewrite#311]
Wenn ich den Cache im System lösche, werden immer Warnings von yRewrite geworfen:

25.10.2019 08:49:28 | Warning | include(/var/www/web2407/html/sub_demo_redaxo/redaxo/cache/addons/yrewrite/config.php) [<a href='https://php.net/manual/function.include'>function.include</a>]: failed to open stream: Datei oder Verzeichnis nicht gefunden | redaxo/src/addons/yrewrite/lib/yrewrite/yrewrite.php | 658

25.10.2019 08:49:28 | Warning | include(/var/www/web2407/html/sub_demo_redaxo/redaxo/cache/addons/yrewrite/config.php) [<a href='https://php.net/manual/function.include'>function.include</a>]: failed to open stream: Datei oder Verzeichnis nicht gefunden | redaxo/src/addons/yrewrite/lib/yrewrite/yrewrite.php | 658

Die Datei config.php gibt es nicht im Cache-Ordner, weder vor noch nach dem löschen des Cache.

getestet auf mehreren Installationen
rex 5.8
php7.3.8 mit opcache
yrewrite 2.6

**Comment by gharlan** [comment]
Da scheinen die Schreibrechte nicht zu passen.
