### ISSUE TITLE
URLs aus der Sitemap entfernen können.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#316]
über das SEO Feld

**Comment by dergel** [comment]
<img width="501" alt="Bildschirmfoto 2019-11-13 um 13 04 40" src="https://user-images.githubusercontent.com/322951/68762317-3c5d0e00-0616-11ea-9422-5b7a4d420a8c.png">

wird das nicht richtig beachtet ?

**Comment by alexplusde** [comment]
Du schreibst mit dir selbst?

**Comment by dergel** [comment]
genau :D

**Comment by skerbis** [comment]
Das direkt auch anfassen: 
https://github.com/yakamara/redaxo_yrewrite/issues/283

**Comment by alxndr-w** [comment]
Das ist bereits der Fall, nur Artikel mit "auto" oder "index" landen in der Sitemap.xml - eben in einem Projekt getestet: https://github.com/yakamara/redaxo_yrewrite/blob/ac6a3b8ea31d6ed9e90703ab1d8c6fe300f96ccc/lib/yrewrite/seo.php#L278-L280

Dieses Issue kann m.E. geschlossen werden.
