### ISSUE TITLE
Tabellenfelder auf utf8mb4 umstellen.

### ISSUE THREAD

**Issue by danspringer** [yakamara/redaxo_yrewrite#317]
Die Felder `yrewrite_title` und `yrewrite_description` sollten ebenfalls auf utf8mb4 umgestellt werden, um Emojis zu unterstützen.

YRewrite: 2.6
REDAXO: 5.8.1
PHP: 7.3.11

**Comment by alexplusde** [comment]
zur Ergänzung: `rex_article` - für vollständigen Support bei automatischen Titeln müsste auch mal `rex_article.name` nachgezogen werden im Core.

**Comment by gharlan** [comment]
Inzwischen kennt der Core ja utf8mb4, und wenn man es dort aktiviert, sind auch diese yrewrite-felder entsprechend.
daher würde ich hier in yrewrite nun nichts mehr machen.
