### ISSUE TITLE
Feld "SEO-Bild" hinzufügen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#319]
Für den Abschnitt "SEO-Daten" beim Bearbeiten eines Artikels sollte ein weiteres Feld für Bilder angelegt werden. Bilder werden oft von Facebook, Whatsapp, Twitter, LinkedIn u.a. beim Teilen eines Links herangezogen, daher sollte das ein fest verbautes Feature von YRewrite sein.

**Comment by skerbis** [comment]
Sehe ich nicht so, da es allgemein aus den Metas oder automatisch durch das Template gespeist werden könnte.

**Comment by alexplusde** [comment]
Mit dieser Argumentation benötigt man auch keinen eigenen Title oder eine Description. Entweder ganz oder gar nicht.

**Comment by skerbis** [comment]
Nein, da diese bei der Installation von REDAXO längst keine Default-Felder mehr sind

**Comment by alexplusde** [comment]
Auch Title & Description sind keine Default-Felder. Ich kann mich da nicht deiner Meinung anschließen. 

Lediglich eine Bildersitemap fände ich auch interessant - könnte man ja sicher ohne Weiteres hinzufügen.

**Comment by skerbis** [comment]
Ich meinte die Artikelbeschreibung wird per default nicht installiert

**Comment by alexplusde** [comment]
Die description wird in YRewrite standardmäßig immer mit installiert.

**Comment by skerbis** [comment]
Ja, das ist auch gut so. Ich meinte die REDAXO Meta-Daten. Menno!

**Comment by alexplusde** [comment]
Bist du dann noch immer gegen meinen Vorschlag?

**Comment by skerbis** [comment]
Ja

**Comment by alexwenz** [comment]
Ich würde mich auch drüber freuen...

**Comment by skerbis** [comment]
Hier eine ausführlichere Erläuterung warum ich dagegen bin. 

Anders als bei den Metadaten kann man nicht bestimmen wo innerhalb der Struktur die Eingabe benötigt wird.
Wenn wir nun ein fixes Bild-Feld einbauen dann werden wir nicht drum rum kommen auch Definitionen für Twitter-Cards, JSON-Ld, Facebook-Dingsbums und Co anzubieten. Man braucht diese aber evtl. in bestimmten Kategorien oder Templates nicht. 

Eher wäre ich dafür dass diese Felder (ja ich nutze sie auch) als Metadaten erfasst werden und ggf. einen Marker bekommen um im SEO-Abschnitt dargestellt zu werden. Also konfigurierbar nach Bedarf. 
 
 Title und Description sind soweit ok, da sie quasi die Mindestmenge der erforderlichen Daten darstellen.

**Comment by alxndr-w** [comment]
Mit SEO-Titel und SEO-Description nimmt man auf 2 von 3 Elementen einer Linkvorschau Einfluss. Mittlerweile gewinnt das beim Teilen an Gewicht - grundsätzlich suchen Facebook, WhatsApp, Telegram, Twitter, LinkedIn, Xing, ... nach einem Vorschaubild und wählen "irgendeins" aus, anstatt man - auf Wunsch - dieses in REDAXO direkt auswählt. 

Das Bild stellt für mich die Mindestmenge erforderlicher Daten dar, noch vor dem Titel - der ist ja schon durch den Artikelnamen gegeben.

**Comment by Matze202** [comment]
Ich schließe mich der Bereitstellung vom SEO-Bild im yRewrite ebenfalls an. 

Ebenfalls fände ich es gut, wenn man spezifisch Daten für gewisse Social-Medien-Seiten eintragen kann, damit die Social-Median-Seiten die Artikel und Kategorien richtig anzeigen, wie man es selbst wünscht.

Irgendwo hatte ich von @skerbis gelesen, dass es für ihn etwas den SEO-Bereich vom yRewrite überladen würde? (Oder hatte ich es falsch verstanden?)

Man könnte doch wie beim CKeditor 5 Plugin für die Editor-Einbindungen, diese sozialen Medien sich selbst eintragen (sowie ein paar als Muster voreingetragen haben) und mit Vorgabewerten selbst versehen lassen, die dann aber aktiviert und deaktiviert werden können. Hauptsache es wird bei den Artikeln dann an richtiger Stelle beim SEO mit eingeblendet, damit man dies dann nicht sucht.

Ebenfalls sollte dann auch das SEO-Bild optional im Backend aktiviert und deaktiviert werden können.
