### ISSUE TITLE
HTTP_X_FORWARDED_HOST statt HTTP_X_FORWARDED_SERVER?

### ISSUE THREAD

**Issue by anveno** [yakamara/redaxo_yrewrite#324]
**Problem:**
Bei einer Installation von redaxo auf einem Server hinter reverse proxy (mit traefik), wird bei aktiviertem yrewrite auf der Startseite einen Umleitungsfehler angezeigt und alle Unterseiten gehen auf die 404-Seite.

**Lösungsansatz**
Aufruf von phpinfo zeigt für $_SERVER['HTTP_X_FORWARDED_SERVER']
den Wert "rproxy", was auch korrekt sein dürfte. [1](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers)

Muss es evtl. hier [2](https://github.com/yakamara/redaxo_yrewrite/commit/8d234a55d5b72526a74f94ebe7a6dac22f3704bd)
statt HTTP_X_FORWARDED_SERVER vielleicht HTTP_X_FORWARDED_HOST heißen? 

Damit funktioniert es bei mir zumindest. 
Habe aber nicht wirklich Ahnung davon und keine weiß nicht welche Auswirkungen das sonst so hat.

**Comment by dergel** [comment]
hier gehts weiter: https://github.com/yakamara/redaxo_yrewrite/issues/218
