### ISSUE TITLE
Wunsch: www-Klärung auch für Backend konfigurierbar

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yrewrite#325]
Es wäre toll, wenn man je Domain die www-Klärung einstellen könnte, so dass der Be-Aufruf auch ohne manuelle htaccess-Konfiguration mit www erfolgen kann.

**Comment by alexplusde** [comment]
Ein Beispiel aus der Praxis: der Entwickler ruft die Website mit www auf, das Backend aber ohne. Somit stimmen die Session-Cookies nicht mehr.

**Comment by iceman-fx** [comment]
Achso...
... dann passiert es (bei mir zumindest) auch, dass die Vorschauversion einen Oppps bringt, da die Sessions unterschiedlich sind.

**Comment by gharlan** [comment]
Meine spontane gedankliche Reaktion auf das Issue war "Fürs Backend ist yrewrite eigentlich nicht zuständig".
Aber nach zwei Mal drüber schlafen würde ich jetzt sagen, ich fände das doch sinnvoll!

Wobei ich da gar nichts konfigurierbar machen würde, sondern automatisch so handeln würde:
Wenn Backend über eine bei yrewrite hinterlegte Domain aufgerufen wird, die Domain sich aber bzgl. www unterscheidet, dann Umleitung.

**Comment by iceman-fx** [comment]
Ja, sehe ich genauso.
Im Grunde kann die im yrewrite hinterlegte Domain 1:1 genutzt werden.

**Comment by alexplusde** [comment]
Bei Subdomains sollte dann auch `www.subdomain.example.org` grundsätzlich auf `subdomain.example.org` weiterleiten können, sofern der Hoster so einen Quatsch voreinstellt.

**Comment by gharlan** [comment]
Gerne testen: https://github.com/yakamara/redaxo_yrewrite/pull/338
