### ISSUE TITLE
Domains anlegen - check auf http://

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#33]
Werden Domains mit `http://` angelegt, kommt im Frontend dann http://http://ww.domain.de.

Entweder Domain vor dem speichern bearbeiten oder prüfen und Fehlermeldung ausgeben.

**Comment by Sioweb** [comment]
Das Problem hatte ich eben auch. Das lässt sich "Quick 'N Dirty" in Zeile 280 lösen:

```
$path = rtrim((strpos($i_domain,'http')===false?$www:'') . $i_domain . '/' . self::$paths['paths'][$i_domain][$id][$clang],'/');
```

Mit strpos auf http prüfen und mit rtrim das doppelte Slash am Ende entfernen. Hilft das?

lg Sascha

**Comment by gharlan** [comment]
Man darf nun explizit "http://" oder "https://" mit im Domainnamen angeben.

Grund: So kann man zum Beispiel steuern, dass eine Domain über https läuft, eine andere aber nicht.
