### ISSUE TITLE
Fehler bei SVGs nach setzen des .htaccess 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#332]
<img width="1190" alt="Bildschirmfoto 2020-02-15 um 22 08 02" src="https://user-images.githubusercontent.com/791247/74595277-ea29ef80-503f-11ea-9a38-a0f26f3cde08.png">

Die SVGs werden im Medienpool nicht mehr dargestellt.
Kein Hinweis in der Console 
Ohne .htaccess ist alles in bester Ordnung.

<details>
<summary>System report (REDAXO 5.9.0, PHP 7.2.27)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.9.0      |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.27     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.31 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/13.0.5 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages            |            |
| ------------------: | :--------- |
|        accessdenied | 1.0.6      |
|             adminer | 1.8.1      |
|              backup | 2.5.1      |
|            be_style | 2.9.0      |
| be_style/customizer | 2.9.0      |
|     be_style/redaxo | 2.9.0      |
|             bloecks | 2.1.1      |
|    bloecks/cutncopy | 2.1.1      |
|   bloecks/dragndrop | 2.1.1      |
|      bloecks/status | 2.1.1      |
|                cke5 | 3.7.1      |
|             cronjob | 2.6.0      |
|           developer | 3.8.0      |
|          focuspoint | 2.2.0      |
|     global_settings | 2.4.1      |
|            icecoder | 2.0.1      |
|             install | 2.6.0      |
|         maintenance | 2.2.0      |
|              mblock | 3.1.0      |
|       media_manager | 2.8.0      |
|        media_srcset | 2.0        |
|           mediapool | 2.7.0      |
|            metainfo | 2.6.0      |
|               mform | 5.3.1      |
|          mform/docs | 1.0        |
|             minibar | 2.0.1      |
|    navigation_array | 1.0.2      |
|           phpmailer | 2.7.0      |
|                plyr | 3.1.2      |
|             project | dev        |
|    quick_navigation | 3.7.1      |
|                sked | 1.10.0     |
|           structure | 2.9.0      |
|   structure/content | 2.9.0      |
|   structure/history | 2.9.0      |
|    uikit_collection | 2.0.0      |
|       uk-iconpicker | 0.0.1      |
|                undo | 2.1.3      |
|            uploader | 2.0.5      |
|               users | 2.6.0      |
|              watson | 2.2.0      |
|               yform | 3.3.1      |
|          yform/docs | 3.3.1      |
|         yform/email | 3.3.1      |
|       yform/manager | 3.3.1      |
|            yrewrite | 2.6        |
|     yrewrite_scheme | 3.1.1      |
|         zip_install | 1.1        |

</details>

**Comment by skerbis** [comment]
Der Aufruf führt auch zu einem direkten Download.
https://meindedomain.tld/media/sxyz.svg?buster=1581870996

?  👇
<img width="1193" alt="Bildschirmfoto 2020-02-16 um 17 47 21" src="https://user-images.githubusercontent.com/791247/74608824-9e7d5180-50e4-11ea-9089-ee92d97aa716.png">

**Comment by marcohanke** [comment]
Konkret liegt es hier ran:
RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]

**Comment by skerbis** [comment]
@marcohanke J/Ein .. die Umleitung wird ja benötigt. Es ist der Auslöser. Das Problem liegt aber viel mehr im Medienpool  oder Mediamanager. Mediamanager: Falsche Ausgabe, Medienpool ggf. falscher Medientyp (MIME) hinterlegt.

**Comment by marcohanke** [comment]
@skerbis Das hatte ich verstanden, ich wollte es nur etwas konkretisieren.

**Comment by gharlan** [comment]
Das wurde mit R5.9 oder 5.10 gelöst.
