### ISSUE TITLE
Cache enthält noch veraltete Domains

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#334]
Verändert man die Domains, zum Bsp. nach dem Einspielen eines Dumps von Prod auf Dev, sind in 
`self::$paths['paths']` noch ältere Domains enthalten. Man muss zwingend den Cache manuell löschen, damit die Neuen korrekt vorhanden sind.

Hier ist `$domain` dann meist `null` und wirft durch `->getUrl` ein Whoops.
https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/yrewrite/yrewrite.php#L412

**Comment by alexplusde** [comment]
das Verhalten kann ich bestätigen
