### ISSUE TITLE
301 Direct der Parameter URLs

### ISSUE THREAD

**Issue by Sreyness** [yakamara/redaxo_yrewrite#337]
Gibt es eine Möglichkeit die "alten" Parameter URL gleich per 301 redirect auf die schönen SEO tauglichen URLs umzuleiten?
z.B.: index.php?article_id=2&clang=0 auf /spezialitaeten/

Da sonst die Parameter URL den selben Canonical Text haben wie die "richtige" Seite.

**Comment by Sreyness** [comment]
Lösung gefunden, wo der Code anfängt mit: // call_by_article allowed
einfach die 301 Weiterleitung einbauen:
```
// call_by_article allowed
        if (self::$call_by_article_id == 'allowed' && rex_request('article_id', 'int') > 0) {
            $url = rex_getUrl(rex_request('article_id', 'int'));
            header('HTTP/1.1 301 Moved Permanently');
            header('Location: '. $url);
            exit;
        } else {
```

**Comment by tbaddade** [comment]
Wenn der Aufruf via `article_id` erlaubt ist, warum sollte genau dann eine Weiterleitung passieren?

**Comment by Sreyness** [comment]
> Wenn der Aufruf via `article_id` erlaubt ist, warum sollte genau dann eine Weiterleitung passieren?

Wenn der Aufruf deaktiviert ist, leitet er nur auf die Fehlerseite weiter. Deshalb hab ich die schon vorhandene Funktion umgebaut. Prinzipiell sind die Parameter URL nicht störend, nur aus SEO-Sicht mit dem selben canonical halt für Google verwirrend.

**Comment by alexplusde** [comment]
Der Aufruf geht evtl. ins leere, weil clang mit REDAXO 4 bei `0` begann, in REDAXO 5 müsste die URL mit clang `1` aufgerufen werden.

Funktioniert dann der Aufruf bei dir? @Sreyness

**Comment by Sreyness** [comment]
@alexplusde ja geht ohne Probleme auch mit clang=0

**Comment by alexplusde** [comment]
@Sreyness du kannst deinen Änderungsvorschlag direkt als Pull Request bei GitHub eintragen.

https://github.com/yakamara/redaxo_yrewrite/edit/master/lib/yrewrite/yrewrite.php aufrufen, die Änderung einfügen und dann den Instruktionen nach dem Code-Eingabefeld folgen.

**Comment by gharlan** [comment]
Ich verweise hier auf #98: Die Parameter-URLs sollten automatisch weitergeleitet werden.
