### ISSUE TITLE
Domain/Url-Format stimmt nicht bei Domain mit Umlaut

### ISSUE THREAD

**Issue by eaCe** [yakamara/redaxo_yrewrite#339]
Man kann die Einstellungen bei Domains mit Umlauten nicht speichern - Domain/Url-Format stimmt nicht.

Gibt es hier ein workaround?

**Comment by alexplusde** [comment]
#194 

hier kann geschlossen werden

**Comment by eaCe** [comment]
Oh übersehen, danke für die info
