### ISSUE TITLE
Startsprache automatisch nach Browsersprache

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yrewrite#340]
Ich schlage vor, dass man pro Domain bei den Spracheinstellungen zusätzlich auswählen kann, dass die Startsprache automatisch entsprechend der Browsersprache (`$_SERVER['HTTP_ACCEPT_LANGUAGE']`) gewählt wird.

<img width="702" alt="Screenshot 2020-03-11 10 12 29" src="https://user-images.githubusercontent.com/330436/76400574-d3e22b80-6380-11ea-934e-b3b891f30aff.png">

Wobei ich die Selectbox für die Startsprache dann trotzdem lassen würde, für die Fallbacksprache.

Aktuell ist es so, dass die Startseite der Startsprache die URL `/` hat, und die Startseiten aller anderen Sprache `/<code>/`.
Ich stelle es mir so vor, dass wenn man die neue Checkbox aktiviert, dass dann `/` nur die Umleitung macht, also auch die Startseite der Fallbacksprache hätte dann die URL `/<code>/`.

Wäre das so die richtige Vorgehensweise? Oder wäre das schlecht, wenn `/` keinen Content hätte und nur umleiten würde?

**Comment by Fanello** [comment]
Was wäre denn für den Fall, dass es nur 1 Sprache hat? Ist es dann auch `/<code>/`?
Nur `/` wäre dann schon besser, oder?

**Comment by alexplusde** [comment]
> Was wäre denn für den Fall, dass es nur 1 Sprache hat? Ist es dann auch /<code>/?
Nur / wäre dann schon besser, oder?

Dafür gibt's die Option drunter: Startsprache nicht in URL.

**Comment by alexplusde** [comment]
> Aktuell ist es so, dass die Startseite der Startsprache die URL / hat, und die Startseiten aller anderen Sprache /<code>/.

Man müsste erstmal validieren, dass in `code` wirklich genormte Codes stehen, die mit der accept-Language korrespondieren.

Außerdem ist unklar, wie das Verhalten ist, wenn mehrere Domains mehrere Sprachen bedienen. Ich denke eher, man müsste Die Kombination Domain + Sprache jeweils einer Browsersprache mappen können. Denkbar ist ja auch bspw., dass en_US auf en_GB leiten soll, ohne dass eine entspr. Sprache angelegt ist, oder fr_CH trotzdem auf de_CH geleitet wird.

**Comment by gharlan** [comment]
> Man müsste erstmal validieren, dass in `code` wirklich genormte Codes stehen, die mit der accept-Language korrespondieren.

Das ist für mich keine zwingende Voraussetzung, um das Feature hier in yrewrite umsetzen zu können.

> Außerdem ist unklar, wie das Verhalten ist, wenn mehrere Domains mehrere Sprachen bedienen.

An was denkst du da?

> Denkbar ist ja auch bspw., dass en_US auf en_GB leiten soll, ohne dass eine entspr. Sprache angelegt ist

Das würde ich versuchen, so sinnvoll wie möglich automatisch zu handhaben. Ich muss da nochmal drüber nachdenken, und bei Symfony noch mal nachschauen, wie die es genau machen, aber eigentlich denke ich, müsste man da schon recht brauchbare Fallbacks automatisch hinbekommen.
Schließe aber auch nicht aus, dass man dafür noch weitere Konfigurationsmöglichkeiten einbaut.

> oder fr_CH trotzdem auf de_CH geleitet wird.

möchte man fr_CH nicht eher auf fr oder fr_FR leiten, falls die vorhanden sind?

**Comment by alexplusde** [comment]
> An was denkst du da?

##Setup 

**Sprachen** deutsch, englisch, französisch, spanisch
**Root-Kategorien** Website DE, WEBSITE CH, WEBSITE FR, WEBSITE ES 
**Domains** example.de, example.ch, example.org

example.de ist die Website Deutsch/Deutschland (Website DE, Sprache DE)
example.org ist die Website Englisch/International (Website EN, Sprache EN)
example.ch/de ist die Website für die dt.sprachige Schweiz (Website CH, Sprache DE)
exemple.ch/fr ist die Website für die französischsprachige Schweiz (Website CH, Sprache FR)
example.org/es ist die Website für Spanien (Website ES)

Das ist das extremste Setup, aber in der Wildnis sieht man davon Mischformen, denn

* nicht jeder Kunde hat für jede Sprache eine eigene Domain
* nicht jede Sprache ist einem geografischen Land zuzuordnen
* nicht jede Website hat denselben Aufbau, sodass man versch. Root-Kategorien benötigt, um dies abzubilden.

**Comment by gharlan** [comment]
Zu deinem Setup:

> `example.de` ist die Website Deutsch/Deutschland (Website DE, Sprache DE)

Wenn jemand .de aufruft, dann würde ich niemals umleiten, da es ein expliziter Aufruf der deutschen Variante ist.
Dort würde ich die Checkbox also nicht aktivieren, bzw sie hätte sowieso keine Auswirkung, da es immer nur um eine Einstellung innerhalb einer Domain geht.
(Über https://www.vodafone.es lande ich zum Beispiel auch auf der spanischen Website, obwohl meine Browsersprache deutsch ist.)

> `example.ch/de` ist die Website für die dt.sprachige Schweiz (Website CH, Sprache DE)
> `example.ch/fr` ist die Website für die französischsprachige Schweiz (Website CH, Sprache FR)

Bei `example.ch` hingegen würde ich die Checkbox aktivieren, sodass dort `/` automatisch umleitet nach `.ch/de` oder `.ch/fr` (mit einem von beiden als Fallback für diese Domain).

> `example.org` ist die Website Englisch/International (Website EN, Sprache EN)
> `example.org/es` ist die Website für Spanien (Website ES)

Da die englische Variante ohne Sprache-Code in der URL laufen soll, würde ich hier die Checkbox wiederum nicht aktivieren. Wenn eine spanisch-sprechende Person die Startseite `/` aufruft, müsste sie also selbst die Sprache wechseln.
Ich würde nicht Session-basiert arbeiten wollen, daher wäre hier nichts anderes möglich (sonst könnte jemand mit spanischer Browsersprache die englische Startseite gar nicht aufrufen).

> Nein, man möchte jemandem in der Schweiz außerhalb der EU nicht das Impressum der französischen Niederlassung präsentieren :)

Umleiten würde ich ja sowieso nur auf der Startseite. Und zwar nach Sprache, nicht geobasiert.
Wenn es die Sprachen `de`, `de_CH` und `fr` gibt, und jemand mit Browsersprache `fr_CH` ruft die Startseite auf, würde ich tatsächlich auf `fr` leiten (so macht es Symfony auch).
Wenn es aber `fr` nicht gibt, aber `fr_FR` schon, dann bin ich mir auch unsicher, und würde ich vielleicht doch eher nicht dahin umleiten.

**Comment by alexplusde** [comment]
Domains sind halt von Natur aus geografisch/international, Sprachen eben davon unabhängig und eher abhängig vom Besucher.

Deswegen würde ich mir eine Oberfläche wünschen, in der ich kontrolliert nachvollziehen kann, was in welchem Fall passiert und auch direkt eingreifen kann, um flexibel zu bleiben.
