### ISSUE TITLE
Suffix bei Custom URL mit speichern

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#347]
Das Problem besteht weiterhin, aber leider wurde #101 nicht erneut geöffnet. Deswegen hier als neues Issue.

![image](https://user-images.githubusercontent.com/3855487/79027949-75ca8300-7b8e-11ea-8b7f-96204261b897.png)

Hier müsste automatisch der Slash erscheinen und die URL auch mit Slash genutzt werden.

**Comment by skerbis** [comment]
Verstehe ich nicht custom heißt custom und daher soll man dort auch ggf. xy.html eingeben können
