### ISSUE TITLE
https : REQUEST_SCHEME beachten

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#348]
Prüfen ob man auch `$_SERVER['REQUEST_SCHEME']` auf `https` prüfen kann.

**Comment by skerbis** [comment]
hab hier was gefunden: https://www.designcise.com/web/tutorial/how-to-check-for-https-request-in-php

**Comment by gharlan** [comment]
Erübrigt sich mit https://github.com/yakamara/redaxo_yrewrite/issues/441.
