### ISSUE TITLE
Lang Slug bitte nicht automatisch setzen, wenn keine Domain angelegt. 

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#351]
Norbert hatte darauf in Slack aufmerksam gemacht. 
Ich befürchte, es würden sich viele Leute nach einem Update wundern, die die Domain nicht in YRewrite definiert haben.

**Comment by tbaddade** [comment]
Ich wäre dafür, dass yrewrite die URL aus der Systemseite automatisch übernimmt und dort das Feld deaktiviert und einen Hinweis hinterlässt. Vielleicht lässt sich damit auch die immer wieder auftretende default-Domain verhindern.

**Comment by alexplusde** [comment]
Für Fälle, in denen man in den Safe Mode muss, ist das kein Problem? Oder beim Wechsel der Hauptdomain? Da stehen doch sonst veraltete Daten und U.U. werden ungültige URLs erzeugt, wenn es Artikel außerhalb der Mountpoints gibt bspw.
