### ISSUE TITLE
Header unset X-Powered-By

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yrewrite#356]
Aus https://friendsofredaxo.github.io/tricks/howto/sicherheitstipps

> X-Powered kann kann sensible Informationen über die verwendete PHP, APACHE oder nginx übermitteln. Die Ausgabe der Versionen sollte vermieden werden.
> Folgende Header Anweisung sollte hierbei helfen
> `Header unset X-Powered-By`

**Comment by skerbis** [comment]
Das sollte global auf dem Server eingestellt werden.

**Comment by alexplusde** [comment]
Die richtigen Mimetypes werden ja auch erst hier gesetzt, aber ich verstehe deinen Punkt. Neues Issue bei REDAXO?

**Comment by skerbis** [comment]
Wichtig. Es sollte optional sein, da wenn serverseitig festgelegt der Header evtl. doppelt gesetzt wird, was zu einer Ungültigkeit führen kann.

**Comment by alexplusde** [comment]
Gilt das nicht auch für andere Bereiche der htaccess?

**Comment by alexplusde** [comment]
(oder des Headers allgemein)

**Comment by skerbis** [comment]
Ja und es ist problematisch. Ich würde daher eher empfehlen dass das Setup oder die Systeminfo hier Empfehlungen gibt, so wie es zb Nextcloud macht

**Comment by alexplusde** [comment]
> das muss im gemacht werden

Im was?

**Comment by skerbis** [comment]
Hostingpaket

**Comment by alexplusde** [comment]
Nie gefunden, dass man das irgendwo beim Hoster konfigurieren kann. Wie groß ist der Performance-Impact?

**Comment by gharlan** [comment]
Die php.ini-Einstellung dazu heißt `expose_php`. 
Ich hab hier gerade mit einem Hetzner-Server zu tun, wo man es auch direkt in der Konsole einstellen kann:

<img width="866" alt="Screenshot 2020-07-10 17 01 48" src="https://user-images.githubusercontent.com/330436/87168762-46333000-c2cf-11ea-92d2-ddb3378cbd56.png">

**Comment by alexplusde** [comment]
Dann bin ich davon überzeugt, dass es hier nicht rein gehört und stattdessen der Trick geändert werden muss.
