### ISSUE TITLE
MP4 :: Errors in Safari: Protokollfehler

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#358]
```
RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]
```
sorgt dafür dass Videos in Safari Fehler werfen. Das weist auf Probleme mit **Accept-Ranges: bytes** hin. 

<img width="646" alt="Bildschirmfoto 2020-08-17 um 17 30 54" src="https://user-images.githubusercontent.com/791247/90413990-7f6d7580-e0af-11ea-9a78-af302759991e.png">

https://github.com/yakamara/redaxo_yrewrite/issues/229

Die header melden jedoch alles wäre in Ordnung. 

Sobald ich diese Rule wieder rausnehme ist alles in bester Ordnung im Safari.

**Comment by gharlan** [comment]
Ich kann das Problem nicht nachvollziehen.
Ich habe mir das Video von hier geladen und in den MP hochgeladen, und habe dann den HTML-Code von dort in ein Module gepackt: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video
Das Video wird bei mir dann korrekt abgespielt. 
Die htaccess ist die Originale von yrewrite ohne Änderungen.

**Comment by skerbis** [comment]
Kann es aktuell auf "meinen" Servern nicht reproduzieren. Weiß aktuell nicht wo es aufgetaucht ist. Schätze daher dass es mit einer bestimmten Server-Config zusammenhängt. 
Sollte es wieder auftreten öffne ich das Issue wieder.

**Comment by skerbis** [comment]
@gharlan @dergel ich Habe Jan den Link zur Seite geschickt.

**Comment by skerbis** [comment]
War wohl ein sich irgendwie reingemogelter Effekt default. 
https://github.com/yakamara/redaxo_yrewrite/issues/358

**Comment by skerbis** [comment]
Eben wieder in Slack. @danspringer  - Erst wenn die rewrite rule für default entfernt ist, funktiniert die Video-Ausgabe in Safari. / Webkit. 

https://github.com/yakamara/redaxo_yrewrite/blob/95d6267184a4da728ed9530af8ccc40efe416548/setup/.htaccess#L97

**Comment by gharlan** [comment]
Ich habe halt das Problem, dass ich es bisher nicht nachstellen konnte, siehe oben.
