### ISSUE TITLE
Weiterleitung - Sonderzeichen erlauben

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#359]
Folgende Url kann nicht hinterlegt werden

```
https://domain.de/dynasite.cfm?dsmid=16148
```

"Sonderzeichen" `?` und `=` sind nicht erlaubt

**Comment by dergel** [comment]
Es geht weniger um die Sonderzeichen, sondern, dass auch paramater mit verwendet werden sollten .. d.h. es können sich natürlich hiermit auch urls überschreiben. + dass ich es weiterhin wichtig finde, das die endslashes mit und ohne genauso betrachtet werden +, dass die parameterreihenfolge nicht wichtig sein sollte.

z.B.:
https://domain.de/dynasite.cfm?abc=4&dsmid=16148
https://domain.de/dynasite.cfm?dsmid=16148&abc=4
https://domain.de/dynasite.cfm/?abc=4&dsmid=16148
https://domain.de/dynasite.cfm/?dsmid=16148&abc=4

-> https://neuedomain.de/neueseite

"cool" fände ich es auch, wenn wir einfachste Platzhalter hätten

https://domain.de/dynasite.cfm?abc={0}&dsmid={1}

-> 

-> https://neuedomain.de/neueseite

oder

-> https://neuedomain.de/neueseite/{0}/{1}

aber der 2. Teil soll das Ganze nicht aufhalten wenn zu aufwändig.
