### ISSUE TITLE
canonical Url

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#36]
Bräuchten wir für ein aktuelles Projekt.

**Comment by dergel** [comment]
die urls sind ja eindeutig .. du meinst eine php methode um das in die metas direkt zu übernehmen ?

**Comment by tbaddade** [comment]
Genau. Ging damals um die Metas.

**Comment by dergel** [comment]
du meinst einerseits, dass die aktuelle URL von REDAXO automatisch eingesetzt wird (weil diese ja immer eindeutig ist) und dann auch, dass man eigene canonical-Urls eintragen kann, ja ? oder noch was ?

**Comment by tbaddade** [comment]
Genau. Einerseits das yrewrite die aktuelle Url liefert andererseits das man ggf. eine eigene via Textfeld besser sogar via Linkmap setzen kann. Hintergrund: Es geht nicht um die eindeutige Url sondern bei selben Inhalt der unter unterschiedliche Urls zu finden ist eine bestimmte Url festzulegen.

Bsp.
http://www.domain.de/en/company.html > en online
http://www.domain.de/de/company.html > de online, hat aber noch engl. Inhalt

Siehe auch:
https://support.google.com/webmasters/answer/139066?hl=de
