### ISSUE TITLE
Protokoll frei wählen können bei "Weiterleitungen"

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#362]
Es sollte möglich sein, Protokolle mit mailto: oder tel:-Links zu akzeptieren. Hierbei können auch beliebige Zeichen auftreten, z.B. das `subject`-GET-Parameter mit beliebigem Textinhalt einer Betreffzeile (Leerzeichen, url-kodierte Sonderzeichen, etc.).

![image](https://user-images.githubusercontent.com/3855487/93688028-0ce32180-fac3-11ea-8001-bb2726ec95f1.png)

**Comment by alexplusde** [comment]
Geht mit der Umleitung statt "Eigene URL". Vielleicht was für die Docs?
