### ISSUE TITLE
Fehler in 2.7 - Domainänderung / Hinzufügen erzeugt Whoops

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#364]
In der Cache-Datei unter `redaxo\cache\addons\yrewrite` wird ungültiges PHP erzeugt. (fehlendes irgendwas (nach `1,5,,`) fehlende clang_id (vorletzter Parameter))

```
<?php

rex_yrewrite::addDomain(new rex_yrewrite_domain("domain1", null, "/", null, 1, 5,, 1, "%T / %SN", "", "User-agent: *
Disallow:", true, 1, 0,, false));
rex_yrewrite::addDomain(new rex_yrewrite_domain("domain2", null, "/", null, 1, 5,, 1, "%T / %SN", "", "User-agent: *
Disallow:", true, 1, 0,, false));
```

**ParseError:** syntax error, unexpected ',', expecting ')'
**File:** redaxo\cache\addons\yrewrite\config.php
**Line:** 3

<details>
<summary>Stacktrace</summary>

| Function                     | File                                                 | Line     |
| ---------------------------- | ---------------------------------------------------- | -------- |
| rex_yrewrite::readConfig     | redaxo\src\addons\yrewrite\lib\yrewrite\yrewrite.php | 52       |
| rex_yrewrite::init           | redaxo\src\addons\yrewrite\boot.php                  | 26       |
| rex_package->{closure}       | redaxo\src\core\lib\extension.php                    | 49       |
| rex_extension::{closure}     | redaxo\src\core\lib\util\timer.php                   | 54       |
| rex_timer::measure           | redaxo\src\core\lib\extension.php                    | 56       |
| rex_extension::registerPoint | redaxo\src\core\packages.php                         | 31       |
| include_once                 | redaxo\src\core\backend.php                          | 200      |
| require                      | redaxo\src\core\boot.php                             | 137      |
| require                      | redaxo\index.php                                     | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.0, PHP 7.3.12, MariaDB 10.4.10)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.0     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.3.12                         |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird ohne HTTPS/Verschlüsselung durchgeführt. Es wird empfohlen jegliche Frontend und Backend aufrufe nur mittels HTTPS durchzuführen, um die Privatsphäre und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.10 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.41  |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/85.0.4183.102 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages                |             |
| ----------------------: | :---------- |
|            2factor_auth | 1.0.0       |
|            accessdenied | 1.0.6       |
|                  across | 3.0.0-dev24 |
|          across/backend | 3.0.0       |
|                 adminer | 1.8.1       |
|                  backup | 2.6.1       |
|                be_style | 2.11.0      |
|     be_style/customizer | 2.11.0      |
|         be_style/redaxo | 2.11.0      |
|                 bloecks | 3.0.0       |
|        bloecks/cutncopy | 3.0.0       |
|          bloecks/status | 3.0.0       |
|                    cke5 | 4.1.0       |
|                 cronjob | 2.7.1       |
|  cronjob/article_status | 2.7.1       |
| cronjob/optimize_tables | 2.7.1       |
|                   debug | 1.0.0       |
|               developer | 3.9.0       |
|                  events | 2.0.0-dev   |
|                   feeds | 3.1         |
|                 install | 2.8.0       |
|                    iwcc | 2.0.0-beta6 |
|                legalweb | 1.0-dev     |
|             maintenance | 2.4.1       |
|                  mblock | 3.1.0       |
|           media_manager | 2.10.0      |
|               mediapool | 2.9.0       |
|                metainfo | 2.7.2       |
|                   mform | 5.3.1       |
|              mform/docs | 1.0         |
|               phpmailer | 2.9.0       |
|                 project | dev         |
|               search_it | 6.7.2       |
|  search_it/autocomplete | 6.7.2       |
| search_it/documentation | 6.7.2       |
|     search_it/plaintext | 6.7.2       |
|         search_it/stats | 6.7.2       |
|                   sprog | 1.2.0       |
|               structure | 2.11.0      |
|       structure/content | 2.11.0      |
|                   theme | 1.2.0       |
|                uploader | 2.2.0       |
|                     url | 2.0.0-beta3 |
|                   users | 2.7.0       |
|                  watson | 2.2.0       |
|                    ycom | 4.0.3       |
|               ycom/auth | 4.0.3       |
|               ycom/docs | 4.0.3       |
|              ycom/group | 4.0.3       |
|                   yform | 3.4.1       |
|              yform/docs | 3.3.1       |
|             yform/email | 3.4.1       |
|           yform/manager | 3.4.1       |
|              yform/rest | 3.4.1       |
|             yform/tools | 3.4.1       |
|           yform_geo_osm | 1.2.3       |
|   yform_spam_protection | 1.0.5       |
|         yform_usability | 1.4         |
|                yrewrite | 2.7         |
|             zip_install | 1.1         |

</details>

**Comment by gharlan** [comment]
Schau bitte mal, ob in `rex_yrewrite_domain` bei dir die Spalte `auto_redirect_days` nullable ist, bzw. ob es Domains gibt, bei denen der Wert `null` ist?
Eigentlich ist die Spalte nicht nullable. Und wenn es null nicht gibt, sollte es eigentlich nicht zu dem Fehler kommen.

**Comment by alxndr-w** [comment]
![image](https://user-images.githubusercontent.com/3855487/94251925-89db2480-ff23-11ea-98ef-b37cc9c7ceec.png)
![image](https://user-images.githubusercontent.com/3855487/94252015-a2e3d580-ff23-11ea-8e29-acfc03754368.png)

**Comment by gharlan** [comment]
Hmm, wieso ist die Spalte be dir varchar?
https://github.com/yakamara/redaxo_yrewrite/blob/master/install.php#L46

**Comment by alxndr-w** [comment]
Richtige Frage!

Die Tabelle wurde zu YForm migriert.

Etwas, das bisher kein Problem war aber sicherlich damit zusammenhängt...

**Comment by alxndr-w** [comment]
Reinstall hat allerdings auch nicht geholfen.

**Comment by gharlan** [comment]
Ist der Typ denn nun int, und der Wert `0`?
Cache gelöscht?

**Comment by alxndr-w** [comment]
Werde ich ausprobieren und rückmelden.

**Comment by alxndr-w** [comment]
Ich schätze, man sollte/darf die Tabelle einfach nicht zu YForm migrieren. Das ist schade, weil das früher ging und teils auch nötig ist. Es ist blöd, dass in YForm standardmäßig auch das Tabellenschema überschrieben wird und immer mal wieder überschrieben werden kann. Aber dann wohl doch eher ein YForm-Problem, dass die Situation so ist.
