### ISSUE TITLE
Bug: 2.7 :: URL-Typ: Umleitung zu Artikel vs. Metadaten

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yrewrite#365]
Wenn in den Metadaten bereits ein REX_LINK_WIDGET eingesetzt ist, wird der gepickte Artikel dort eingesetzt. 
<img width="333" alt="Bildschirmfoto 2020-09-25 um 17 35 34" src="https://user-images.githubusercontent.com/791247/94286888-e5bea100-ff55-11ea-97e9-0bf69eca4509.png">

Mein Metafeld lautet art_redirect 

EDIT: Beide Felder erhalten die gleiche ID: 

REX_LINK_1_NAME

**Comment by tyrant88** [comment]
bestätigt

**Comment by skerbis** [comment]
Beide Felder erhalten die gleiche ID: 

REX_LINK_1_NAME

**Comment by shauste** [comment]
Fehler tritt auch bei mir auf, bestätigt.

**Comment by skerbis** [comment]
@dergel das passiert auch, wenn ein Block mit entsprechendem Link-Widget geöffnet ist.

**Comment by tyrant88** [comment]
Das liegt wohl daran wohin die Antwort des PopUp gesendet wird...
