### ISSUE TITLE
Problem mit 2.7: direkt URLs auf Dateien unter /media werden blockiert

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yrewrite#366]
Hallo

Mit yrewrite 2.7 (und der dazugehörigen htaccess) habe ich das Problem, das direkt Aufrufe auf Dateien unter /media nicht zugelassen werden. Es funktionieren nur Aufrufe über den Media Manager. 
Habe in diesem konkreten Fall versucht mp4s und JSON Dateien (SVG Animation) direkt aufzurufen, aber ohne Erfolg. 
Beispiel Aufruf: https://www.domain.ch/media/data.json

Hier die Regeln aus 2.7 (geht nicht)
```
RewriteRule ^mediatypes/([^/]*)/([^/]*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2
RewriteRule ^media/([^/]+)/(.*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]
RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]
```

Wenn ich die unterste Zeile auskommentiere geht's:
```
RewriteRule ^mediatypes/([^/]*)/([^/]*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2
RewriteRule ^media/([^/]+)/(.*) %{ENV:BASE}/index.php?rex_media_type=$1&rex_media_file=$2&%{QUERY_STRING} [B]
#RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]
```

Scheint mir auch klar wieso. Ist das so gewollt bzw. macht die letzte Zeile wirklich Sinn?

Möglicherweise verwandt:
https://github.com/yakamara/redaxo_yrewrite/issues/332
https://github.com/yakamara/redaxo_yrewrite/issues/358

**Comment by dergel** [comment]
das ist so gewollt. was nicht gewollt ist, dass es bei Dateien Probleme gibt. Das müssten wir dann im individuellen Fall nachschauen. Vor allem wegen media_auth ist das gewollt, also wenn man Rechte an Medien vergibt und einen direkten Aufruf unterbinden will.

der direkte Aufruf leitet auf einen media manager effekt um, der die datei ausgeben sollte.

was passiert bei dir ?

**Comment by ynamite** [comment]
@dergel Ach sooo, ja das macht Sinn. 

Dann gehe ich davon aus das wohl einfach der `default`-Effekt fehlt. Woher kommt denn der, wird der von yrewrite oder von Redaxo angelegt?

In meine Fall etwas doof, weil ich bereits einen Effekt mit dem Namen`default` verwende.

**Comment by skerbis** [comment]
Uuumpf ... damit ist https://github.com/yakamara/redaxo_yrewrite/issues/358 gelöst. 
Habe auch einen Effekt default.  - wobei ich mich gerade frage wo der her kommt. Dort ist ein download header vorgelegt.

**Comment by ynamite** [comment]
Yay!
Ich habe einen eigenen default-Effekt (von mir angelegt).

**Comment by dergel** [comment]
ich schliesse das issue hier.
