### ISSUE TITLE
Fehler beim anlegen von Sprachen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#37]
Notice: Undefined offset: 1 in /addons/yrewrite/classes/class.rex_yrewrite.inc.php on line 416

Catchable fatal error: Argument 2 passed to rex_yrewrite_scheme::getClang() must be an instance of rex_yrewrite_domain, null given, called in /addons/yrewrite/classes/class.rex_yrewrite.inc.php on line 417 and defined in /addons/yrewrite/classes/class.rex_yrewrite_scheme.inc.php on line 18

**Comment by tbaddade** [comment]
Bekomme noch immer eine Fehlermeldung

```
Notice: Undefined offset: 1 in /addons/yrewrite/classes/class.rex_yrewrite.inc.php on line 416

Catchable fatal error: Argument 2 passed to rex_yrewrite_scheme::getClang() must be an instance of rex_yrewrite_domain, null given, called in /addons/yrewrite/classes/class.rex_yrewrite.inc.php on line 417 and defined in /addons/yrewrite/classes/class.rex_yrewrite_scheme.inc.php on line 18
```

**Comment by gharlan** [comment]
Gerade in R5 getestet, kann ich so Anhieb jedenfalls nicht (mehr) nachvollziehen.
Wollen wir es erstmal wieder schließen, solange es nicht wieder auftritt?

**Comment by dergel** [comment]
wir schliessen erstmal .. wenn es wieder auftaucht gerne reoopen
