### ISSUE TITLE
https im Domain-Namen auf Domain ohne SSL: Backend nicht erreichbar

### ISSUE THREAD

**Issue by ynamite** [yakamara/redaxo_yrewrite#372]
Wenn man in yrewrite eine falsche Domain hinterlegt (zBsp. wegen Schreibfehler), dann kommt man niemals nie mehr ins Backend -> Umleitungsfehler, zu viele Redirects.

Das ist erst seit 2.7 so (glaube ich). 

Einziger weg zurück ins Backend war: in der DB die Domain korrekt eintragen und per FTP Cache Ordner löschen.

Vor 2.7 konnte man zwar das Frontend nicht erreichen, aber das Backend schon. Dort konnte man problemlos die Domain entsprechend anpassen. Nun geht das nicht mehr, was etwas misslich ist.

**Comment by gharlan** [comment]
Eigentlich leitet yrewrite im Backend nur von http zu https um, wenn die aufgerufene Domain so hinterlegt ist.
Wenn man aber über eine andere Domain kommt, sollte es keine Weiterleitung geben.

Was war das denn für ein Schreibfehler? Also mitten in der Domain ein anderer Buchstabe oder so?

**Comment by ynamite** [comment]
Ah OK, das wird dann der Grund gewesen sein. Mein Szenario:

Bei einer Redaxo-Instanz die Domain von http:/www.domain.com auf die Subdomain (neu mit SSL) https://dev.domain.com geändert. Wie üblich wollte ich die Domain nachträglich in yrewrite ändern.

IMO sollte yrewrite im Backend nie Weiterleiten, oder zumindest nicht für Admins.

**Comment by gharlan** [comment]
Was ich noch vergessen habe: es wird auch noch zwischen www und non-www umgeleitet, entsprechend wie die Domain hinterlegt ist.

Hintergrund des Ganzen: Es war ein Klassiker in Slack, dass Frontend und Backend unterschiedlich aufgerufen wurden, und dann die Backendsession im Frontend nicht verfügbar war. Und somit zum Beispiel developer im Frontend nicht aktualisiert hat, und ähnliches.
https://github.com/yakamara/redaxo_yrewrite/issues/325

Deine genaue Konstellation kapiere ich noch nicht, wie es dann zu der Endlosumleitung kam.

**Comment by ynamite** [comment]
Naja, einerseits wegen vorher ohne SSL zu SSL und die Subdomain die dazugekommen ist ...

Den Hintergund verstehe ich, aber wie gesagt, denke es macht Sinn dies für Admin-User auszuschliessen. Oder was meinst du?

**Comment by skerbis** [comment]
Dinge wie non-ssl zu SSL, non-www zu www etc.  sollten eher über das Hosting laufen. Weniger über die REDAXO eigene Lösung (meine Meinung) ich verstehe die Lösung in REDAXO eher als Hilfe. - @ynamite: Gut, es war ein Eingabefehler, der das Problem verursacht hat. Da kann REDAXO ja nichts dafür. ;-) ... ich habe mal versucht es zu reproduzieren. REDAXO war immer unter der default-Domain (hinterlegt in System) erreichbar.

**Comment by ynamite** [comment]
@skerbis nein war kein Eingabefehler! Das war nur ein Beispiel!

Ich habe Redaxo von Domain A (ohne SSL) zu Domain B (mit SSL) umgezogen. Danach war das Backend wegen Umleitungsfehler nicht mehr erreichbar.

Stimme dir aber zu, finde auch, dass das Sache des Hostings wäre (oder htaccess)-

**Comment by gharlan** [comment]
> Den Hintergund verstehe ich, aber wie gesagt, denke es macht Sinn dies für Admin-User auszuschliessen. Oder was meinst du?

Soweit ich mich erinnere, waren das gerade meist Adminsituation, die in Slack vorkamen, und die für uns der Grund waren, dieses Feature einzubauen.

**Comment by ynamite** [comment]
Hm, OK.

Ich finde es persönlich wichtiger, nicht komplett vom Backend ausgeschlossen zu werden, als von der Backend-Session. Aber ja.

**Comment by gharlan** [comment]
Ich stimme zu, vom Backend ausgeschlossen zu sein, ist sehr blöd.

Sollte aber auch mit dem neuen Feature eigentlich nicht vorkommen, und ich kann es mir halt leider auch immer noch nicht wirklich erklären, was da nun genau war. Und somit kann ich gerade auch nicht einschätzen, ob es lösbar ist, trotz des neuen Features.

**Comment by ynamite** [comment]
@gharlan ich kann's reproduzieren. Kann dir gerne Zugang geben, wenn du's selber versuchen möchtest.

**Comment by gharlan** [comment]
Ja, das wäre super!

**Comment by ynamite** [comment]
Soll ich dir auf Slack den Zugang senden oder lieber per Mail?

**Comment by dergel** [comment]
habt ihr das issue hier schon geklärt ?

**Comment by ynamite** [comment]
Ehrlich gesagt weiss gar nicht mehr ob wir das geklärt hatten.
Jedenfalls bin ich seither immer mal wieder darauf reingefallen; ist definitiv leicht zu reproduzieren. 

Beispiel: arbeite in einer DEV Umgebung, ohne SSL, ziehe das ganze dann samt DB in die Production-Umgebung um, mit SSL, und kann mich dann wegen den Redirects nicht mehr im Backend anmelden. Muss dann per PhpMyadmin die Domain in der yrewrite-Tabelle ändern, yrewrite-Cache per FTP o.ä. löschen, damit ich wieder ins Backend komme.
Klar, mann könnte die Domain vor dem Umzug ändern, aber dann hab ich dasselbe Problem in der DEV-Umgebung.

**Comment by alxndr-w** [comment]
Kann ich nicht nachvollziehen, ist mir auch schon passiert mit falschen Domainnamen.

Was ist denn als System-Domain hinterlegt?

**Comment by ynamite** [comment]
@alxndr-w es geht um's Protokoll im Zusammenhang mit forciertem SSL seitens Webhosting, nicht um die Domain. Sorry falls das unklar war. 

Wenn ein Webhosting eine forcierte Weiterleitung auf SSL eingestellt hat (was heutzutage häufig der Fall ist und imo auch sein sollte) und du in yrewrite die Domain (bzw. irgendeine Domain) ohne SSL einträgst, kommst du garantiert nicht mehr ins Backend. Macht ja auch Sinn, nur sollte imo yrewrite im Backend eben nicht das Protokoll erzwingen, dass sollte Sache des Webhostings sein. Ich verstehe was gharlan/dergel oben geschrieben haben, finde das aber wie gesagt eine Verschlimmbesserung.

Die System-Domain hat soweit ich weiss keinen Einfluss darauf.

**Comment by skerbis** [comment]
> Wenn ein Webhosting eine forcierte Weiterleitung auf SSL eingestellt hat und du in yrewrite die Domain (bzw. irgendeine Domain) ohne SSL einträgst, kommst du garantiert nicht mehr ins Backend.

Dann ist doch klar was du machen musst. Schalte es beim Hosting ab.

**Comment by ynamite** [comment]
@skerbis yform hat damit nun aber gar nichts zu tun ...

Ich weiss wie das Problem zu lösen ist, danke. Aber es sollte gar nicht erst soweit kommen ... ich erinnere dich daran das du oben geschrieben hattest: 
> Dinge wie non-ssl zu SSL, non-www zu www etc. sollten eher über das Hosting laufen. Weniger über die REDAXO eigene Lösung (meine Meinung)

Meine Rede!!!

**Comment by skerbis** [comment]
Stimmt ja auch soweit. Also korrigiere deine Hostingeinstellung und fertig.

**Comment by gharlan** [comment]
Für mich hat sich das Feature insgesamt bewährt. Vorher kamen wirklich regelmäßig in Slack Leute mit den entsprechenden Problemen, weil sie das Backend mit anderer Domainvariante aufgerufen haben als das Frontend (http/https und www/non-www).

Ich könnte mir aber vorstellen, dass yrewrite bei der Weiterleitung im Backend einen Parameter an die URL hängt, um Mehrfach-Weiterleitungen zu erkennen, und dann doch die falsche Domainvariante zuzulassen.
In dem Fall könnte yrewrite dann eine Warnung ins Log schreiben.

**Comment by ynamite** [comment]
@skerbis wieso sollte ich denn die Hosting Einstellung korrigieren, wenn die korrekt sind? 😂 Ich würde sie lieber dort korrigieren wo sie falsch sind, im Addon, welches ich aber nicht aufrufen kann, weil's mir den Zugang verwehrt 🤦🏻‍♂️

Nochmal (bitte aufmerksam mitlesen): ich kann mit dem status quo leben! War nur ne Anregung. Doof ist es zweifelsfrei trotzdem, auch wenn es das von gharlan angesprochene Problem löst. Das eine sollte das andere nicht ausschliessen. 

Sonst ist mein Standpunkt halt der: Entwickler sollten in der Lage sein konsequent eine URL über SSL (oder eben ohne SSL) aufzurufen und sonst sollen sie halt die URL anpassen (scheint mir weitaus einfacher als die Hosting einstellung falsch einzustellen, nur damit man wieder ins Backend gelangt).

**Comment by skerbis** [comment]
@gharlan eine andere Möglichkeit wäre einen Switch in der package.yml des AddOns zu hinterlegen um yrewrite die entsprechende Anweisung zu geben.

**Comment by ynamite** [comment]
PS. ich klink mich nun hier aus. So viel Text wegen nix.

**Comment by alxndr-w** [comment]
Also, wenn man etwas falsch macht, z.B. Schreibfehler, dann gibt es Aufwand, diesen zu korrigieren.

Wie soll YRewrite das abfangen?

**Comment by ynamite** [comment]
@alxndr-w
> Also, wenn man etwas falsch macht, z.B. **Schreibfehler**, dann gibt es Aufwand, diesen zu korrigieren.
> Wie soll YRewrite das abfangen?
🤦🏻‍♂️ 
Ich geb auf, so dicht kann man echt nicht sein. Viel Spass noch!

**Comment by alxndr-w** [comment]
Vielleicht gibt's auch ein Missverständnis. Wenn's nur daran scheitert, dass http erzwungen wird und nur https erreichbar ist, man's aber am Hostingpaket einschaltet, dann schreib in YRewrite 

nie `http://www.example.org` 
und auch nicht `https://www.example.org` sondern nur
`www.example.org` - mehr funkt YRewrite auch gar nicht rein.

**Comment by ynamite** [comment]
### Ein allerletzter Versuch das _Missverständnis_ aufzuklären.**
_Ganz unten Lösungsansätze_

Finde es inkosistent/unlogisch/benutzerunfreundlich dass
**A)** Schreibfehler in der Adresszeile des Browsers von yrewrite abgefangen werden (zbsp. www oder http**s** vergessen)
gharlan:
> Hintergrund des Ganzen: Es war ein Klassiker in Slack, dass Frontend und Backend unterschiedlich aufgerufen wurden, und dann die Backendsession im Frontend nicht verfügbar war. Und somit zum Beispiel developer im Frontend nicht aktualisiert hat, und ähnliches. https://github.com/yakamara/redaxo_yrewrite/issues/325

**B)** Schreibfehler im dafür vorgesehen yrewrite-Domain-Feld **nicht abgefangen** werden
Mögliche Folgen:
je nach Hosting-Einstellungen wird man vom Backend ausgeschlossen (zBsp. wenn Domain ohne https hinterlegt wird, beim Hosting aber eine fixe Weiterleitung von http zu https eingestellt ist.)


### Soweit klar?

Genau! **Beides sind ganz klar Anwenderfehler**. Nur sind die daraus resultierenden Folgen bei B) schwerwiegender – zumindest aus meiner Sicht:
Backend-Session nicht verfügbar < gar nicht mehr ins Backend kommen

### Was mich nervt

Erwähnt man hier Fall B) bzw. schlägt dafür eine Lösung vor, kriegt man so nützliche Antworten wie:
> Also, wenn man etwas falsch macht, z.B. Schreibfehler, dann gibt es Aufwand, diesen zu korrigieren. 
> Wie soll YRewrite das abfangen?

Aha. Danke Captain Obvious, sehr erleuchtend. Ironie **off** 

Merkt hier echt keiner das mit zweierlei Mass gemessen wird? Für B) gilt ganz salopp "mach keine Fehler und sonst korrigiere sie halt ey" während für A) gilt "diesen Fehler fängt yrewrite ab, weil sonst führt das zu bei bestimmten Nutzern zu Problemen".

Oder Antworten wie:
> Stimmt ja auch soweit. Also korrigiere deine Hostingeinstellung und fertig. 
> Bei mir ist auch eh alles https .. :-)

Äh, wieso gilt das dann nicht auch für A) ... ? 
Zudem Spoilter-Alert: nein, **stimmt eben nicht** – denn gemäss deiner eigenen Aussage sollte yrewrite weder bei A) noch bei B) dazwischen funken (mal ganz abgesehen davon, dass http längst **nicht** tot ist, aber das ist eine andere Diskussion. Nur so viel: du kannst von deiner Config NIE auf die Config anderer schliessen. Sonst können wir gleich aufhören mit Issues): 
> Dinge wie non-ssl zu SSL, non-www zu www etc. sollten eher über das Hosting laufen. Weniger über die REDAXO eigene Lösung (meine Meinung) ...

_Wir lassen jetzt einfach mal aussen vor, dass du mir damit eigentlich zustimmst ... Jedenfalls tut yrewrite **genau das Gegenteil davon** wofür du dich oben ausgesprochen hattest. Wie du das nicht erkennen magst, ist mir absolut schleierhaft. Aber hey, you do you und so.
Simpler geht's nicht: yrewrite korrigiert im Fall A) tut aber dasselbe nicht im Fall B) und das obwohl B) meiner Meinung nach deutlich mühsamer zu beheben ist._

### Ich stimme skerbis' ursprünglicher Aussage zu

domain.com zu www.domain.com, http zu https, sollte vom Hosting oder htaccess geregelt werden und nicht von yrewrite, dann geschehen nämlich weder A) noch B)! #winwin

Eigentlich sehr simpel zu verstehen finde ich. Wer's immer noch nicht begriffen hat, wird's nie begreifen (wollen). 

### Lösungsansätze

1. nichts machen – weil eigentlich ist's mir persönlich relativ egal (schreib ich nun übrigens gefühlt zum 5. mal)
2. das Ganze (gharlans fix) wieder entfernen weil (aus meiner Sicht) kontraproduktiv
3. Weiterleitung nicht ausführen wenn man als Admin angemeldet ist (ein Admin sollte in der Lage sein eine korrekte URL in die Browser-Adressleiste zu tippen bzw. zu korrigieren)
4. wenigstens beim yrewrite-Domain-Feld eine Warnung anzuzeigen, dass man durch falsche Eingaben, je nach Hosting-Einstellungen, Gefahr läuft vom Backend ausgeschlossen zu werden
5. Option einbauen damit man selber einstellen kann, ob man das Backend-Weiterleitungs-Gedöns haben möchte


### Habe fertig

ich diskutiere das Thema jetzt echt nicht weiter, weil nochmal, so wichtig ist's mir persönlich nicht und mir fehlt schlicht die Zeit. Ich fordere weder dass das gefixt noch sonst was. Wollte das Issue bloss erwähnt haben, weil ich's suboptimal und benutzerfeindlich finde. Wenn ihr das so im Addon haben wollt, bitteschön, ich komme damit klar. Denke ich habe meinen Standpunkt hiermit mehr als deutlich gemacht.  
Man kann übrigens auch völlig anderer Meinung sein, finde ich völlig legitim. gharlan hat das Problem von Anfang an verstanden und seine Meinung dazu geschrieben, mehr braucht's eigentlich gar nicht. 
Unproduktive Kommentare oder Kommentare die anderen Poster unfähigkeit unterstellen kann man sich aber echt sparen finde ich, die lenken nur vom eigentlichen Thema ab und führen am Ende zu viel Luft um nichts.
