### ISSUE TITLE
yRewrite: Keine Inhaltsausgabe bei Schema .html, wenn 2 Artikel den gleichen Namen haben

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yrewrite#383]
Bei einer Migration von Rex4 auf die aktuellste Rex5 ist folgender Fehler aufgefallen:

yRewrite generiert automatisch die gleiche URL für 2 Artikel, wenn beide Artikel den gleichen Namen besitzen.
Anschließend wird der Content der Artikel nicht mehr ausgegeben, weil vermutlich intern das Auslesen des Inhalts aufgrund der URL abbricht.

**Szenario:**
Root > Artikel mit Name "Test" > ergibt /test.html
Root > Kategorie mit Name "Test" = deren Artikelname ist auch "Test" > ergibt /test.html

yRewrite-Schema umgestellt auf .html
`rex_yrewrite::setScheme(new rex_yrewrite_scheme_html());`

Weder die Vorschau noch die Liveversion zeigt nun den gepflegten Content.
Nach Umbenennen einer der beiden Artikel klappt alles wieder.

<details>
<summary>System report (REDAXO 5.11.0, PHP 7.4.2, MySQL 5.7.29)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.2      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.29 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | FreeBSD    |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/86.0.4240.183 |
|      Protocol | HTTP/1.1             |
|         HTTPS | yes                  |

| Packages          |             |
| ----------------: | :---------- |
|           adminer | 1.8.1       |
|            backup | 2.6.1       |
|          be_style | 2.11.0      |
|   be_style/redaxo | 2.11.0      |
|          be_tools | 1.5.2       |
|           bloecks | 3.0.0       |
|  bloecks/cutncopy | 3.0.0       |
|    bloecks/status | 3.0.0       |
|      cameraslider | 1.2.5       |
|          ckeditor | 4.13.1      |
|           cronjob | 2.7.1       |
|           cropper | 1.1.0       |
|         developer | 3.9.0       |
|   emailobfuscator | 3.0.0       |
|        hp_seometa | 1.2         |
|           install | 2.8.0       |
|              iwcc | 2.0.0-beta8 |
|      jqlightboxes | 1.1         |
|     media_manager | 2.10.0      |
|         mediapool | 2.9.0       |
|          metainfo | 2.7.2       |
|         phpmailer | 2.9.0       |
|           project | dev         |
|  quick_navigation | 3.9.3       |
|         structure | 2.11.0      |
| structure/content | 2.11.0      |
| structure/version | 2.11.0      |
|          uploader | 2.2.0       |
|             users | 2.7.0       |
|             yform | 3.4.1       |
|        yform/docs | 3.3.1       |
|       yform/email | 3.4.1       |
|     yform/manager | 3.4.1       |
|          yrewrite | 2.7         |

</details>

**Comment by gharlan** [comment]
-> #129
