### ISSUE TITLE
Umlaute erlauben

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yrewrite#385]
https://github.com/yakamara/redaxo_yrewrite/blob/95d6267184a4da728ed9530af8ccc40efe416548/pages/forward.php#L41

In dieser Zeile müssten Umlaute ergänzt werden, um URLs mit Umlauten weiterleiten zu können.

**Comment by alxndr-w** [comment]
Hast du getestet, ob es dann funktioniert? An einigen Stellen ist YRewrite nicht unicodetauglich, man muss stattdessen punycode verwenden.

**Comment by DanielWeitenauer** [comment]
Ach, an die Domain habe ich nicht gedacht. Wir brauchen die Umlaute nur in den Pfaden, da klappt es.

**Comment by alxndr-w** [comment]
Ganz YRewrite punycodetauglich zu machen ist vermutlich zu viel des Guten für diesen PR, oder?

**Comment by marcohanke** [comment]
Ich hänge mich hier an und würde mir Umlaute und Sonderzeichen in den Weiterleitungen wünschen.
