### ISSUE TITLE
SEO Meta Image - og:image

### ISSUE THREAD

**Issue by VIEWSION** [yakamara/redaxo_yrewrite#391]
Das SEO Objekt hält ja u.A. Felder für Title / Description bereit. Würde da nicht auch ein optionales "Meta-Bild" Sinn machen? Ich denke da z.B. an Twitter oder  FB og. Klar - geht natürlich auch über die Metadaten... aber vielleicht wäre das da auch gut aufgehoben...

**Comment by tbaddade** [comment]
Wenn dieser PR https://github.com/yakamara/redaxo_yrewrite/pull/310 angenommen wird, könntest du das recht einfach selbst ergänzen.

**Comment by VIEWSION** [comment]
OK... ehrlich gesagt bin ich kein Fan davon ganze HTML-Tags auszugeben... da hab ich lieber nur die Values. Da ist man viel flexibler mit den Templates.

**Comment by alxndr-w** [comment]
siehe #319

**Comment by tbaddade** [comment]
Ob du die Tags in der boot.php oder im Template zusammenstellst ist eigentlich egal. Zum Schluss werden Tags benötigt.

**Comment by TobiasKrais** [comment]
Siehe https://github.com/yakamara/redaxo_yrewrite/pull/461

**Comment by gharlan** [comment]
#461 wurde gemerged.
