### ISSUE TITLE
Einstellungen an passendere Stellen verschieben

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#393]
![image](https://user-images.githubusercontent.com/3855487/102634476-2d6a5880-4152-11eb-82e9-f01107d6236f.png)

Die Unicode-Einstellung sollte man pro Domain vornehmen können, die SEO-Block und URL-Block-Einstellungen hingegen pro Benutzer/Rolle.

**Comment by skerbis** [comment]
Im yrewrite_scheme AddOn ist es bereits je Sprache realisiert was mehr Sinn macht als je Domain.

**Comment by DanielWeitenauer** [comment]
Für die Blöcke gibt es bereits die Rechte yrewrite[url] und yrewrite[seo] um sie pro Rolle zu aktivieren. Die Checkboxen in den Einstellungen sind für das generelle Deaktivieren, wenn die Felder z.B. über eigene Metadaten verwaltet werden. (Siehe https://github.com/yakamara/redaxo_yrewrite/pull/141)

**Comment by gharlan** [comment]
Und die Unicode-Einstellung sehe ich temporär. Langfristig soll es sowieso der einzige Modus werden.
Daher schließe ich hier.
