### ISSUE TITLE
Vorschlag: Robots-Tag im Debug-Modus automatisch auf "noindex,nofollow" setzen

### ISSUE THREAD

**Issue by dpf-dd** [yakamara/redaxo_yrewrite#395]
`$yrewrite = new rex_yrewrite_seo();
echo $yrewrite->getRobotsTag();
Ausgabe => <meta name="robots" content="index, follow">`

Es wäre toll, wenn die Ausgabe immer "noindex, nofollow" ist, wenn im Redaxo -Backend der Debug-Modus aktiviert ist.

Hintergrund: Beim Entwickeln einer Page möchte ich nichts indizieren lassen.
Ich finde das wäre eine sinnvolle Optimierung...!?

**Comment by alxndr-w** [comment]
Das ist meines Wissens bereits der Fall – kannst du das entsprechend überprüfen?

Ein echter Schutz ist das jedoch nicht. Dafür sorgt das Maintenance-Addon

**Comment by dpf-dd** [comment]
Ich habe das überprüft, sonst hätte ich das Issue nicht aufgemacht.
Redaxo 5.11.2 im Debug-Modus und mit einem yrewrite_seo-Objekt den Robots-Tag generiert. Ergebnis war index,follow...

**Comment by alxndr-w** [comment]
Im Header müsste dies anders sein, schon von REDAXO aus.

https://github.com/redaxo/redaxo/blob/594e4d061952508ad849b557e0275c5f1db5aab1/redaxo/src/core/frontend.php#L11-13

Jetzt wäre es wichtig zu wissen, welche Information die andere übertrumpft.

**Comment by dpf-dd** [comment]
Hmkay, ich hab zwar noch paar andere AddOns am laufen aber nichts was an der Stelle eingreifen dürfte. Ich teste das nochmal mit einem jungfräulichen Redaxo und nur yRewrite und gebe dann hier Rückmeldung...

**Comment by gharlan** [comment]
Was Alex meinte: REDAXO setzt einen Header, yrewrite setzt einen Meta-Tag.
Und die Frage ist, was davon höher gewichtet wird.

Und die Antwort ist: die restriktivere Angabe zählt.

https://developers.google.com/search/reference/robots_meta_tag?hl=de

> Miteinander in Konflikt stehende Robots-Anweisungen: Sollten Robots-Anweisungen miteinander in Konflikt stehen, wird die restriktivere Anweisung angewendet. Wenn eine Seite beispielsweise sowohl die max-snippet:50- als auch die nosnippet-Anweisung hat, wird die nosnippet-Anweisung angewendet.

**Comment by tbaddade** [comment]
> Hintergrund: Beim Entwickeln einer Page möchte ich nichts indizieren lassen.

BasicAuth ?

**Comment by dpf-dd** [comment]
Das muss ich erst googlen ^^
Aber wenn der Redaxo-Header das Meta-Tag übertrumpft, dann kann das Issue hier geclosed werden. Rein optisch und damit keine Verwirrung aufkommt fände ich das zwar trotzdem cool, wenn yRewrite auch auf den Debug-Modus reagiert und den Meta passend zum Header ausliefert - aber entscheidend ist das es funktioniert :)

Und ja, Maintenance-AddOn ist sicherlich auch ratsam, keine Frage. :)
Danke für das schnelle Feedback!

**Comment by gharlan** [comment]
Ich schließe hier dann mal.
Kann den Wunsch durchaus schon verstehen (dass es auch in den Metatags abgebildet wird), aber so wirklich notwendig ist es eben nicht. Eigentlich wäre es unnötige Logik hier im Addon. Und ich würde es zumindest nicht umsetzen.
