### ISSUE TITLE
Groß- und Kleinschreibung

### ISSUE THREAD

**Issue by CaptainMik** [yakamara/redaxo_yrewrite#397]
Das Modul sollte alle möglichen Schreibweisen unterstützen.
Im Moment kann man auch keine alternative Schreibweise in anderer GroßKleinschreibung eintragen.

**Comment by skerbis** [comment]
@CaptainMik wo wünschst Du dir GroßKleinschreibung? In Urls? Macht das wirklich Sinn?

**Comment by CaptainMik** [comment]
Welches Modul: Yrewrite - Weiterleitungen
Ja das wäre super. Ich weiß das Linux da anders reagiert als Windows. Aber für die Benutzer ist das tatsächlich ein Problem, das auch gerade in einem Projekt auftritt, weil da Weiterleitungen mit GroßKleinschreibung realisiert sind, die Benutzer aber alles nur kleinschreiben und dann auf die nicht richtige Seite kommen. Das kann man Menschen, die die Hintergründe nicht kennen, schwer vermitteln. Wahrscheinlich ist es ja nur ein anderer Regex, oder man könnte einfach alles vorher in Kleinbuchstaben umwandeln. Du könntest es ja auch wahlweise anbieten. Auf Windows Servern wäre der Eintrag halt obsolet.

**Comment by alxndr-w** [comment]
Unkonventioneller Ansatz: Im Template auf der Fehler 404-Seite prüfen, ob ein gleichnamiger Artikel in anderer Schreibweise existiert - falls ja, dorthin weiterleiten.

**Comment by gharlan** [comment]
Ich denke, das ist das gleiche wie #274.
