### ISSUE TITLE
rex_var REX_YREWRITE_DOMAIN_ID

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#398]
Als Shortcut analog zu REX_ARTICLE_ID

**Comment by skerbis** [comment]
zusätzlich REX_YREWRITE_DOMAIN

**Comment by gharlan** [comment]
Diese einfachen Vars ohne eckige Klammern `[]` lassen sich glaube ich nicht so gut ergänzen.
Denn die laufen nicht über die `rex_var`-Klasse, sondern als einfache Ersetzung: https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php#L522-L546

Bin mir nicht sicher, vielleicht gibt es auch einen geeigneten EP, wo man eigene ergänzen könnte. Vielleicht aber auch nicht.
Eine direkt dafür vorgesehene Erweiterungsmöglichkeit besteht aber nicht.

**Comment by skerbis** [comment]
Ich denke es ist schon mit [] gemeint 
Könnte ja auch nur eine var sein mit entsprechenden Parametern

**Comment by gharlan** [comment]
> analog zu REX_ARTICLE_ID

Deswegen bin ich drauf gekommen, denn das ist ja eine Var ohne eckige Klammern.
Es stimmt aber, man könnte das Problem umgehen, indem man hier die Vars eben doch mit Klammern macht (aber ohne Parameter, wenn nicht benötigt).
Man könnte es aber auch über eine Var lösen, etwa so in der Art:

```
REX_YREWRITE_DOMAIN[key=id]
REX_YREWRITE_DOMAIN[key=mountpoint]
```

**Comment by skerbis** [comment]
Das meine ich. Dürft mich gerne assignen

**Comment by alxndr-w** [comment]
Ich meinte das, was Gregor meint, bin aber mit dem Alternativvorschlag d'accord.

**Comment by skerbis** [comment]
@alxndr-w siehe https://github.com/FriendsOfREDAXO/global_settings/blob/master/lib/rex_var_global_var.php

**Comment by skerbis** [comment]
Ich frage mich gerade was es ausgeben soll, wenn's im Backend genutzt wird

**Comment by alxndr-w** [comment]
Die YRewrite-Domain ID des Artikels natürlich

**Comment by tbaddade** [comment]
> Ich frage mich gerade was es ausgeben soll, wenn's im Backend, z.B in einem Modul genutzt wird

Könntest du über den Param `output` steuern. Siehe [REX_LINK](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/structure/lib/linkmap/var_link.php#L38-L40) zum Beispiel

**Comment by skerbis** [comment]
@alxndr-w  na ja gut, je nachdem was ich abfrage ;-)

**Comment by dergel** [comment]
war gerade dabei und dachte das nehme ich gerade noch mit .. Hoffe du hattest nicht bereits angefangen
