### ISSUE TITLE
Anlegen doppelter Domains vermeiden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#402]
Folgende Variante kann man anlegen.

`https://www.domain-a.de/pfad`

**Comment by gharlan** [comment]
Das ist bewusst so, um Unterordner zu unterstützen.

**Comment by tbaddade** [comment]
Hmm … da läuft vermutlich dann noch etwas falsch

`https://www.domain-a.de`
Mountpoint: Rootebene

`https://www.domain-a.de/unterordner`
Mountpoint: Unterordner

Aufruf `https://www.domain-a.de`. Es erscheint die Startseite von `https://www.domain-a.de/unterordner`

**Comment by gharlan** [comment]
Dieselbe Domain mit unterschiedlichen Unterordnern innerhalb einer Instanz hatte ich damals glaube ich nicht bedacht.
Weiß auch nicht, ob das so gut möglich ist.
Eventuell sollte man es unterbinden. Also jede Domain nur einmal, aber sie darf in der Domain-Url Unterordner haben.

**Comment by tbaddade** [comment]
> Also jede Domain nur einmal

Habe den Titel des Issues angepasst.
