### ISSUE TITLE
Weiterleitungstyp "Intern" ermöglichen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#407]
Aktuell gibt es article (ID) oder extern (volle URL) - ein Intern, das die aktuell gewählte Domain/Domain-ID berücksichtigt aber nicht die Domain als Ziel beinhaltet, wäre nützlich.

**Comment by tbaddade** [comment]
Könntest du mit Beispielen aufzeigen, was genau erreicht werden soll? 

Für mich ist der Begriff Intern zumeist der Verweis auf einen andeen Artikel.

**Comment by alxndr-w** [comment]
Eingabe als realtive URL, nicht als absolute.
