### ISSUE TITLE
leere Artikelnamen verhindern

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#411]
Wir hatten hier den Fall, dass der Redakteur gleich mehrere Artikel einer Kategorie ohne Artikelnamen anlegte.

Eventuell wäre es sinnvoll, das YRewrite eine Meldung anzeigt, wenn Artikel via Url nicht erreichbar sind.

**Comment by alxndr-w** [comment]
Könnte ja mit einem eigenen Schema theoretisch erlaubt sein. Die Frage wäre, müsste YRewrite dann nicht _1 oder so dranhängen.

**Comment by gharlan** [comment]
REDAXO hat am Kategorienamen seit 5.14 das `required`-Attribut. 
Ich denke, dieses Ticket kann daher zu. 
(Zu dem Problem mit doppelten Namen gibt es andere Tickets.)
