### ISSUE TITLE
Liste der Weiterleitungen an article / extern - Feld mit Ziel-URL verlinken

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#414]
https://github.com/yakamara/redaxo_yrewrite/blob/38db4a7eb5ed9b2faf363a23539312ee5073dfcb/pages/forward.php#L167-L172

![image](https://user-images.githubusercontent.com/3855487/122735585-74f7ab80-d27f-11eb-811c-79fe07de3785.png)

Diesen Teil verlinken, um die Ziel-URL wenigsten per Mouseover einsehen zu können.

Andernfalls die Ausgabe der Quell-URL in der Liste erweitern um Ziel-URL (statt nur Quell-URL).

Was wäre euch denn lieber?

**Comment by gharlan** [comment]
Die Ziel-URL wird nun seit #487 angezeigt.
