### ISSUE TITLE
Default-Werte werden nicht korrekt gesetzt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#428]
Beispiel `content.yrewrite_seo.php`

In der Tabelle ist der Wert leer und wird so auch im Choice-Value ausgewertet und der Default-Wert wird nicht angewendet.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/choice.php#L26-L27

Abhilfe schafft die Tabellenfelder auf `null` zu setzen oder beim Anlegen der Artikel direkt den Default-Wert in die Tabelle zu schreiben.

**Comment by gharlan** [comment]
Ich muss gestehen, ich kapiere es noch nicht ganz. Um welche Default-Werte geht es genau?
