### ISSUE TITLE
1170 BLOB/TEXT column 'url' used in key specification without a key length

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yrewrite#448]
Problem entstand durch die Kombi dieser beiden Änderungen:

* https://github.com/yakamara/redaxo_yrewrite/pull/425
* https://github.com/yakamara/redaxo_yrewrite/pull/406

Fehler:

> AddOn yrewrite konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_yrewrite_forward` CHANGE `url` `url` text NOT NULL , CHANGE `extern` `extern` text NOT NULL , ADD UNIQUE `domain_id_url` (`domain_id`, `url`);": SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'url' used in key specification without a key length

https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1638742888090400

Mit mariadb bekomme ich die Meldung nicht. Aber mit mysql 8 kommt sie wohl.

@tbaddade @alxndr-w Bin mir unsicher, was wir hier machen. Den Unique-Key doch wieder entfernen?

**Comment by thorol** [comment]
Ich habe die Fehlermeldung auch mit MariaDB 10.2.41.
Es fehlt bei Spalte url, da es nun vom Type text ist, die Länge, bis wohin gecheckt wird, ob es Unique ist, z.B. so funktioniert es:
`ADD UNIQUE `domain_id_url` (`domain_id`, `url`(512))`
Ob 512 sinnvoll, habe ich mir keine Gedanken drüber gemacht,

**Comment by iceman-fx** [comment]
Das Gleiche bei MySQL 5.7.29.

**Comment by alxndr-w** [comment]
Das Feld auf 512 zu beschränken klingt für mich sinnvoller, als doppelte Einträge zuzulassen.

**Comment by gharlan** [comment]
Mein Problem: Ich weiß nicht genau, welche Beschränkungen wir brauchen, damit es überall zuverlässig funktioniert.
Mein Stand war, dass es dann auf 191 sein muss, um es zuverlässig mit Unique-Key und utf8mb4 verwenden zu können.
Und nur den Unique-Key zu beschränken, ist doch eher nicht sinnvoll, oder?
