### ISSUE TITLE
Invalid argument supplied for foreach() Zeile 252

### ISSUE THREAD

**Issue by chrisrex** [yakamara/redaxo_yrewrite#451]
Huhu. ich hab noch einen Fehler im log. Der war vorher nicht da.
Invalid argument supplied for foreach()
redaxo/src/addons/yrewrite/lib/yrewrite/path_resolver.php Zeile 252
Ich nutze noch das URL addon. Evtl. gibt es da Wechselwirkungen

**Comment by alxndr-w** [comment]
URL1 oder 2? @chrisrex

**Comment by chrisrex** [comment]
URL 2.0.0-beta3

**Comment by alxndr-w** [comment]
Die aktuelle GitHub-Version hat einige Korrekturen bekommen in der Zwischenzeit, kannst du diese testweise installieren?

**Comment by chrisrex** [comment]
Danke. Der Fehler bleibt leider

**Comment by rolandsee** [comment]
Mit URL 1.0.1 tritt die Warning ebenfalls auf.

**Comment by DanielWeitenauer** [comment]
Der Fehler tritt bei mir ohne das AddOn Url, aber mit einem eigenen Rewrite-Scheme auf. 
Ein Cast auf `(array)` in der Zeile behebt bei mir das Problem.

**Comment by DanielWeitenauer** [comment]
Es liegt wohl daran, dass die Domain als Array-Key erwartet wird, der aber nicht immer vorhanden ist. Hier z.B. kann er fehlen: https://github.com/yakamara/redaxo_yrewrite/blob/b81a724ee61b417eb3519ee334fb84d6ab44e230/lib/yrewrite/yrewrite.php#L236
