### ISSUE TITLE
.htaccess wird im Setup nicht gesetzt

### ISSUE THREAD

**Issue by claudihey** [yakamara/redaxo_yrewrite#454]
Im Setup wird die .htaccess weder neu gesetzt noch überschrieben, obwohl eine Erfolgsmeldung erscheint.

**Comment by eaCe** [comment]
Die .htaccess liegt nicht in der .zip die aus dem Installer kommt.

**Comment by bloep** [comment]
ich habe ein neues release mit dem fix erstellt.

@gharlan du müsstest dafür das release auf github einmal re-createn, damit der es neu ausführt und hochlädt.

**Comment by gharlan** [comment]
Danke euch fürs Rausfinden und Fixen!

Ich werde ein neues Release erstellen.
