### ISSUE TITLE
Title-Tag bei Multidomains fehlerhaft für %S

### ISSUE THREAD

**Issue by danspringer** [yakamara/redaxo_yrewrite#457]
Wenn man in einer Domain as Title-Schema z.B. `%T / %S ` nutzt, wird im Frontend nicht die Domain der aktuellen Domain für `%S` genommen, sondern der Name der 1.Domain (der Name der Rex-"Mutterinstallation" sozusagen).

Rex 5.13.1
PHP 8.0.14

yrewrite 2.8.3
yrewrite_scheme 3.6.1

**Comment by alxndr-w** [comment]
Das ist korrekt. Es gibt ja auch kein Feld für einen Namen. Deswegen statt %S (den Servernamen in System) einfach das eintragen, was du möchtest.

**Comment by gharlan** [comment]
Siehe Alex Erläuterung.
