### ISSUE TITLE
Warning, Undefined array key 1, redaxo/src/addons/yrewrite/lib/yrewrite/seo.php

### ISSUE THREAD

**Issue by martinm79** [yakamara/redaxo_yrewrite#462]
Hallo 

ich habe seit 2 Tagen immer den gleichen Fehler in der `redaxo/data/log/system.log` Datei

**Fehlermeldung**

```
2022-02-07 09:34:39 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-07 09:34:39 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-07 09:35:04 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-07 09:35:04 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-08 07:56:48 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-08 07:56:48 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-08 07:59:52 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-08 07:59:52 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-08 10:17:12 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
2022-02-08 10:17:12 | Warning | Undefined array key 1 | redaxo/src/addons/yrewrite/lib/yrewrite/seo.php | 250
```

Habe die Ursache ausfindig machen können.
Ein Kunde hat eine Unterseite auf "online" und zur Startseite umgelenkt. 
Daher kam der Fehler.

**Comment by alxndr-w** [comment]
Hallo @martinm79, was meinst du mit „umgelenkt“? Wird ein Eintrag im Log erzeugt, wenn der Artikel aufgerufen wurde oder die Startseite, auf die der Artikel zeigte?

**Comment by alxndr-w** [comment]
Und noch zwei Fragen: war das Mal eine alte REDAXO 4-Seite? Kannst du überprüfen, ob in System -> Sprachen nur eine ist und diese online ist?

**Comment by martinm79** [comment]
Eine "Unterseite" der Domain war auf online gestellt.
Und diese "Unterseite" hatte eine "Umleitung zur Artikel" und war zur Startseite umgelenkt. 
Das ist zwar Sinnfrei, war aber so eingestellt. 

Wann genau der Log erzeugt wurde, kann ich nicht sagen, kann ich ja kurz prüfen. 

Nein, es ist keine alte Redaxo4 Installation.
Ja, es ist nur eine Sprache vorhanden.

**Comment by martinm79** [comment]
Als ich den Artikel auf online stellte, konnte ich den Fehler leider nicht mehr reproduzieren. 

Was mir aber noch aufgefallen war.
Wo der Fehler auftrat, gab es in der sitemap.xml mehr als eine Startseite.

**Comment by alxndr-w** [comment]
"Umleitung zu Artikel" ist kein Feature von Yrewrite, sondern selbst programmiert. Ohne die genaue Umsetzung zu kennen ist es schwieriger nachzuvollziehen, warum der Fehler auftritt.

Hast du evtl noch Änderungen bei den in YRewrite eingetragenen Domains vorgenommen? 

Denn in der Zeile 250 der seo.php geht's in dem Array um die clang-id, also Sprachen, deswegen meine Nachfragen in eine andere Richtung als das Thema Weiterleitungen.

**Comment by martinm79** [comment]
Ich habe keine Änderungen vorgenommen, die diesen Fehler verursachen könnten. 
Habe nur die Funktionen von Redaxo verwendet.
Ja, Die Umleitung in der rechten Sidebar "Umleitung zu Artikel"

Ich hatte in der Zwischenzeit den Cache gelöscht. Vielleicht konnte ich deswegen den Fehler nicht reproduzieren.

**Comment by rolandsee** [comment]
Ich hatte dieses Warning auch massenweise in einem Projekt. Die Warnings sind immer dann entstanden, wenn die sitemap.xml aufgerufen wurde. Ich bin dann den Hinweis von Alex nachgegangen. In diesem Projekt gab es tatsächlich zwei Sprachen (DE mit id=1 / EN mit id=2), wobei die Sprache EN offline war. Da ich nur die Sprache DE benötigte, habe ich EN gelöscht. Danach sind auch die Warnings nicht mehr aufgetaucht.

**Comment by rolandsee** [comment]
Ok, meine Beobachtung vor ca. 3 Wochen ist nicht richtig. Aktuell habe ich ein Projekt mit zwei Sprachen (DE mit id=1 / EN mit id=2), wobei beide Sprachen online sind. Dennoch wird das Warning für die Zeile 250 gezeigt, sobald die Sitemap aufgerufen wird. Ich habe testweise eine Isset-Prüfung um den betroffenen Codebereich gelegt. Damit tritt die Warning nicht mehr auf.

 `                        if(isset($path[$clang_id])) {
                            $sitemap[] =
                            "\n".'<url>'.
                            "\n".'<loc>'.rex_yrewrite::getFullPath($path[$clang_id]).'</loc>'.
                            "\n".'<lastmod>'.date(DATE_W3C, $article->getUpdateDate()).'</lastmod>'. // serverzeitzone passt
                            "\n".'<changefreq>'.$changefreq.'</changefreq>'.
                            "\n".'<priority>'.$priority.'</priority>'.
                            "\n".'</url>';                            
                        }`

In der Sitemap selbst fällt mir nun auf, dass nach Einbau der Isset-Prüfung eine Zeile weniger angezeigt wird. Welche das ist, ist schwierig nachzuvollziehen. Ohne Prüfung hat die Sitemap in meinem Projekt 593 Zeilen, mit Prüfung 592 Zeilen.
