### ISSUE TITLE
Artikel-ID vor Weiterleitung auf Existenz prüften

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#498]
Wenn ein nicht existierender Artikel, wie z.B. https://design-to-use.de/index.php?article_id=72 aufgerufen wird, kommt eine Weiterleitungsschleife. Der Artikel sollte zuvor auf Existenz geprüft werden.

**Comment by tyrant88** [comment]
Hui, ich bekomme deswegen auch gerade vermehrt von google Post, wegen Weiterleitungsschleife...

Es ist dieser neue Code-Block:
https://github.com/yakamara/redaxo_yrewrite/blob/main/lib/yrewrite/yrewrite.php#L220

Wenn ich den auskommentiere, bekomme ich wieder die normale 404 Page.

**Comment by fietstouring** [comment]
Das ist mir auch gerade unangenehm aufgefallen!

**Comment by tyrant88** [comment]
Ja, heute kam wieder Post von google.

**Comment by fietstouring** [comment]
ohne den code block gehen weiterleitungen aber nur ohne clang param

**Comment by TobiasKrais** [comment]
Ich hab gerade einen PR dazu geschrieben: https://github.com/TobiasKrais/redaxo_yrewrite/commit/96385e429aa41ffb6a0c146f9cfea6a62e22e6db. Hat jemand Zeit den zu testen?

**Comment by fietstouring** [comment]
Hallo, bei mir existiert die Umleitungsschleife nach wie vor, YRewrite 2.9.1
