### ISSUE TITLE
EP YREWRITE_PREPARE - Clang 0 wird übergeben kommt aber nicht in CUR_CLANG an

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#50]
Ich habe diese Zeile[1] in einem aktuellen Projekt ändern müssen.

[1] https://github.com/yakamara/redaxo_yrewrite/blob/master/classes/class.rex_yrewrite.inc.php#L234

alt
```php
if (isset($params['clang']) && $params['clang'] > 0) {
```

neu
```php
if (isset($params['clang']) && $params['clang'] > -1) {
```

Warum vor dem Neusetzen von $REX['CUR_CLANG'] der Wert 1 ist und nicht 0 habe ich nicht weiter nachgeprüft.

Zumindest wurde die Clang-Id "0" richtig an den EP übergeben. yrewrite hat diesen aber wegen der obigen Zeile nicht beachtet.

**Comment by gharlan** [comment]
https://github.com/yakamara/redaxo_yrewrite/commit/a109eadce8f0c96ee7888862a62ef10044b4e180

Allerdings beginnen die Clangs in R5 mit der ID 1, weshalb ich es nun wieder rückgängig gemacht habe:
https://github.com/yakamara/redaxo_yrewrite/commit/e2adba637342ae58778ab411d1ba40de9acafaa6
