### ISSUE TITLE
`hreflang`-Attribut in `sitemap.xml` mit aufnehmen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#503]
https://developers.google.com/search/docs/advanced/crawling/localized-versions#sitemap

> Jedes <url>-Element muss ein untergeordnetes Element `<xhtml:link rel="alternate" hreflang="supported_language-code">` haben, in dem jede alternative Version der Seite, einschließlich der Seite selbst, aufgelistet ist. Die Reihenfolge dieser untergeordneten `<xhtml:link>`-Elemente spielt keine Rolle. Es ist allerdings sinnvoll, bei den Elementen dieselbe Reihenfolge einzuhalten, weil du sie so besser auf Fehler prüfen kannst.

**Comment by gharlan** [comment]
Welchen Vorteil versprichst du dir davon?
Laut der Seite gibt es ja die drei Methoden: Meta-Tags, Header, Sitemap. Und man soll sich eine aussuchen.
Und die Meta-Tags haben wir ja schon implementiert.

**Comment by alxndr-w** [comment]
Für mich gehört es dorthin, weil auch die Sitemap nach meinem Kenntnisstand häufiger gecrawlt wird und damit schneller Änderungen bei Google abgebildet werden oder indexiert werden.

**Comment by gharlan** [comment]
Ich vermute, dass Google die Infos trotzdem erst verwendet, wenn die jeweilige Seite auch neu/initial indexiert wird.

In dem Dokument oben liest sich das so, dass die 3 Methoden gleichwertig sind (Sitemap wird ja auch erst als dritte Methode genannt). 

> Die drei Methoden entsprechen der Perspektive von Google und du kannst die Methode auswählen, die für deine Website am besten geeignet ist. Du kannst zwar alle drei Methoden gleichzeitig verwenden, das hat aber keinen Vorteil in der Suche. Tatsächlich ist es eher schwieriger, drei Implementierungen zu verwalten, anstatt nur eine auszuwählen.

**Comment by alxndr-w** [comment]
Das stimmt. Leider habe ich nicht mehr im Kopf, warum ich im September darüber gestolpert bin, denn ich weiß, dass ich einen Grund hatte. Entweder aufgrund der Search Console, vielleicht aufgrund der fehlenden Implementierung im Template-Code eines Projekts. Ich sollte wieder klarer dazuschreiben, nicht nur was die Aufgabe ist, sondern welches Problem ich damit lösen möchte. Schon für meine eigene Vergesslichkeit.

Ich vermute, dass es was mit dem URL2-Addon zu tun hatte und der möglichen fehlenden Zuordnung zwischen News-Eintrag `de` zu `en`, aber dann hätte ich ja erst ein Issue bei URL2 aufgemacht.

**Comment by gharlan** [comment]
Aktuell sehe ich hier keinen Grund, die hreflangs in die sitemap zu duplizieren.
Daher schließe ich hier. Falls sich neue Aspekte ergeben, kann man erneut drüber nachdenken.
