### ISSUE TITLE
Sitemap getDescription

### ISSUE THREAD

**Issue by michael-kreatif** [yakamara/redaxo_yrewrite#507]
Hey.

Manche unserer Seo-Partner Agenturen haben den Wunsch, dass die meta description nicht länger als 180 Zeichen sein sollte und vom System aus automatisch alle Tags, die jemand per Copy + Paste unabsichtig einfügt, entfernt werden.
Könnte auch über nen EP gemacht werden.

Wäre dies eurer Meinung nach eine sinnvolle Erweiterung?

**Comment by alxndr-w** [comment]
Das ist ja kein technisches Problem, sondern ein redaktionelles. 

Wenn man in die Beschreibung als Redakteur entgegen jeder Empfehlung länger als 180 Zeichen tippt, dann löst "abschneiden" nicht das Problem. Selbst YRewrite bietet ja einen Zähler:

![image](https://user-images.githubusercontent.com/3855487/199055153-68ef8980-27c1-44bc-9043-1092031a6b11.png)

Dein Redakteur vermeidet ungewollten Code, indem er beim Einfügen von Text die Option / Tastenkombination für "Nur Text einfügen" wählt.

![image](https://user-images.githubusercontent.com/3855487/199055450-0b7f4041-1dfe-48f6-84bc-9ca90a7a855e.png)

**Comment by skerbis** [comment]
Wie können denn in der Description Tags landen? Ist doch ein einfaches Textfeld

**Comment by michael-kreatif** [comment]
@alxndr-w + @skerbis danke an euch beiden. Habe die Funktion nun nochmal genau angeschaut. Passt perfekt so wie sie ist.  Auch das waren leider noch Code-Relikte, die in unserem Fork von früher geblieben sind.
Sorry für den Aufwand.
