### ISSUE TITLE
Weiterleitungsart der Startseite auf 301 ändern

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yrewrite#511]
Die Startseite meiner Domain https://ingtec.ch/ wird per 302 auf https://ingtec.ch/de/ weitergeleitet. Da die Weiterleitung aber per 302 erfolgt, zeigt mir Google beide Seiten als Duplikat an. Andere große Seiten machen eine 301 Weiterleitung und verhindern damit die Duplikatmeldung. Könnte das angepasst werden?

**Comment by ynamite** [comment]
+1
Finde Tobias hat recht und ich stelle die gleiche Problematik bei https://www.vincafilm.ch fest.

**Comment by bitshiftersgmbh** [comment]
+1 unter Vorbehalt ...

Ich glaube, die Idee ist, dass der Bot nicht für EN, ES, DE Sprach-Header etc. jeweils das Signal bekommt, die Startseite `/` ist jetzt **immer** (301) `/en/`. Dann kommt der _spanische_ Bot und da sagt der Server, die Startseite `/` ist **immer** `/es/` etc. Diese wiedersprüchliche Zuweisung, die es eigentlich nur 1 x geben sollte, soll wohl durch das 302 verhindert werden.

Wenn mir aber Startseiten in wichtigen Sprachen aus dem Index fliegen, weil Google Duplicate Content erkennt und der Canonical nicht mehr mit dem Status-Code (302) vereinbar ist, dann hat man das Problem ja nur in eine andere Ecke verlagert.

Richtig knorke wär es also aus meiner Sicht, wenn man es einfach einstellen könnte. Zumindest bis irgendwer ein offizielles Statement seitens Google ausgräbt, wo das Best Practice für das Szenario beschrieben ist.

**Comment by TobiasKrais** [comment]
In der Praxis sieht es so aus: aufgrund der Sitemap werden der Suchmaschine alle zu indexierenden Seiten angezeigt. Es geht also keine Startseite verloren, weder `/es/` noch `/en/`,.... Eine 301 Weiterleitung ist die einzige Möglichkeit Google mitzuteilen, dass doppelter Inhalt vermieden wird. Wohin weitergeleitet wird ist zweitrangig. Warum? Ziel ist lediglich, die Hauptseite ohne lang slug (`/`)aus dem Index zu nehmen und statt dessen die Seiten mit lang slug in der jeweiligen Sprache zu positionieren. Ist der Vorbehalt unter praktischen Gesichtspunkten daher noch haltbar? So wie ich das verstehe: nein.

**Comment by bitshiftersgmbh** [comment]
> Ist der Vorbehalt unter praktischen Gesichtspunkten daher noch haltbar?

Wenn man davon ausgeht, dass deine Einschätzung, dass die 301-Widersprüche weniger relevant sind, stimmt, dann: nein

**Comment by gharlan** [comment]
> Andere große Seiten machen eine 301 Weiterleitung und verhindern damit die Duplikatmeldung.

302-Weiterleitungen:

* https://store.google.com
* https://www.microsoft.com
* https://www.mozilla.org

301-Weiterleitungen:

* https://www.samsung.com

Welche weiteren Seiten hattest du noch gefunden mit 301-Weiterleitung?

Mir kommt 302 eigentlich korrekter vor. Ich vermute, dass es für das Problem noch eine andere Lösung geben muss unter Beibehaltung des 302-Codes.

**Comment by TobiasKrais** [comment]
Schauen wir uns die Fakten nochmals an:

1. Fakt ist: 302 Weiterleitungen werden von Google als Duplicate Content angesehen.
2. Fakt ist: Duplicate Content wird von Google als Fehler, somit schädlich, angesehen.
3. Fakt ist: Duplicate Content ist zeitnah nur mit einer 301 Weiterleitung zu beseitigen.

Und dann die Vermutungen:

1. Vermutung ist: es gibt eine bessere Lösung. Fakt ist: wir kennen sie nicht.
2. Vermutung ist: 301 Weiterleitungen zu wechselnden Zielen ist schädlich. Fakt ist: Google reagiert positiv auf die 301 Weiterleitung.

Hier ist Pragmatismus angesagt. Dann bekommen wir die Duplicate Content Seiten aus der Search Console.

**Comment by ynamite** [comment]
> Richtig knorke wär es also aus meiner Sicht, wenn man es einfach einstellen könnte.
+1 
Wieso nicht dem Entwickler überlassen? Dann kann man selber entscheiden, wie man's möchte.

**Comment by alxndr-w** [comment]
<https://www.adobe.com> schaltet meines Wissens ein Popup zur Auswahl von Land/Sprache vor ohne Redirect.

1. Entwickler∗innen können den lang-slug für die Hauptsprache deaktivieren. Problem gelöst.
2. Entwickler∗innen können eigene Domains verwenden für eigene Sprachen. Problem gelöst.

Wer auf diese (m.E. nicht gute) Lösung einer Umleitung zurückgreifen muss, erzeugt ja auch Duplicate Content, dann sollte man ihn auch so behandeln. Denn die "Startseite" (der leere Artikel mit Browserweiche) ist ja unter unterschiedlichen Seiten zu finden. Über `canonical`- und `alternate href=""`-Linktags wird klar, welche Alternativen Seiten es gibt - keine davon ist die Root-Seite `example.org/` in diesem Beispiel.

Und demzufolge ist der 302er auch korrekt.

**Comment by gharlan** [comment]
> Google empfiehlt drei Szenarien. Eine davon ist eine 302, _wenn_ man automatisch weiterleiten möchte . Ich persönlich finde das jedoch extrem nervig, wenn mich jmd. zwingt eine bestimmte Sprache zu lesen.

Ob man die Weiterleitungsvariante nutzt, oder nicht, lässt sich in yrewrite ja konfigurieren. Aber wenn man sie nutzt, dann ist es eine 302-Weiterleitung (und nicht 301), so wie man es in der Anleitung bei Google findet, wie es für mich auch semantisch passt, und wie es die meisten Websites machen, die eine solche automatische Weiterleitung implementiert haben.

Das Duplicate-Content-Problem besteht vermutlich nur, wenn es unter der Domain-Startseite auch mal Content gab, und man nachträglich auf diese automatische Weiterleitung umstellt. Wenn man das bei einer neuen Domain macht, dürfte Google den Domain-Hauptpfad ja nicht im Index haben, da es von Anfang an eine Weiterleitung ist.
Wobei ich denke, dass auch bei der 302-Weiterleitung Google nach einer Weile den Index korrigiert, insbesondere wenn alles korrekt ausgeliefert wird bzgl. `canonical`-Tags, `alternate` etc., und eben neu dann auch mit dem `x-default`, siehe oben.

**Comment by gharlan** [comment]
Hier ist nun mein Vorschlag bzgl `x-default`: https://github.com/yakamara/redaxo_yrewrite/pull/524
Ihr könnt ja mal schauen, ob das so für euch Sinn macht.

**Comment by TobiasKrais** [comment]
Auch wenn wir das x-default Flag setzen denke ich nicht, dass wir die Fehlermeldung über doppelten Inhalt bei Google damit weg bekommen. Das `x-default` Flag zu setzen behebt den Logikfehler, aber überzeugt Google nicht. Hier bräuchten wir noch den PR  https://github.com/yakamara/redaxo_yrewrite/pull/517

**Comment by gharlan** [comment]
> Das `x-default` Flag zu setzen behebt den Logikfehler, aber überzeugt Google nicht.

Woher nimmst du diese Info? Meine Hoffnung ist schon, dass wir Google damit helfen, die Situation (schneller) zu verstehen.
Wir machen ja jetzt genau das, was Google bei Google zu lesen ist bzgl. einer solchen Sprachweiterleitung:

https://developers.google.com/search/blog/2014/05/creating-right-homepage-for-your

> Im dritten Szenario werden automatisch die passenden HTML-Inhalte für eure Nutzer je nach deren Standort- und Spracheinstellungen geschaltet. Dies geschieht entweder über eine serverseitige 302-Weiterleitung oder durch die dynamische Schaltung der richtigen HTML-Inhalte. Vergesst nicht, die Anmerkung "x-default rel-alternate-hreflang" auf der Startseite bzw. generischen Seite einzufügen, auch wenn es sich bei der generischen Seite um eine Weiterleitungsseite handelt, die nicht von Nutzern direkt aufgerufen werden kann.

**Comment by TobiasKrais** [comment]
Vor kurzem hatte ich eine Meldung von Google über doppelten Inhalt. Betroffen war eine Impressum Seite in Deutsch und Spanisch. Auf der Seite war nur die Überschrift unterschiedlich und natürlich der rel-alternate-hreflang Tag. Hier liegt ein ähnliches, aber nicht genau gleiches, Szenario vor: sowohl die x-default Seite als auch die Seite einer weiteren Sprache haben identischen Inhalt. Und ich vermute sehr, dass Google das auffällt.

Noch etwas: ein SEO Experte sagte mir vor kurzem, dass 301 Weiterleitungen der einzige Weg sind bestehende Warnungen zu doppeltem Inhalt bei Google zu lösen.

Die Zeit wird zeigen, ob Google die derzeitige Lösung ausreicht.

**Comment by TobiasKrais** [comment]
Noch ein Hinweis für die Nachwelt: Google meckert  auch nach der Änderung mit x-default, dass doppelter Inhalt existiert. Der Fehler lässt sich nur durch eine 301 Weiterleitung abstellen. Vielleicht könnte man das in die Einstellungen mit rein nehmen.
