### ISSUE TITLE
Link-Felder pro Domain für Impressum und Datenschutz

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#516]
Sowohl https://github.com/FriendsOfREDAXO/consent_manager als auch https://github.com/alexplusde/wenns_sein_muss müssen sich um eine eigene Domain-Auswahl mit Auswahl zum Datenschutz-Artikel und dem Impressums-Artikel in Mehrsprachen-Umgebungen kümmern.

M.E. gehört das Thema inzwischen in den Core und hier in YRewrite, WordPress macht das schon seit Jahren so.

Die Lösung ermöglicht bspw. auch einen schnellen Zugriff innerhalb von Templates.
Es gibt für mich kein Szenario, in dem man das NICHT an pro Domain haben will, deshalb wäre es gut, das in YRewrite aufzunehmen.

**Comment by alxndr-w** [comment]
[Siehe auch https://github.com/yakamara/redaxo_yrewrite/issues/516](https://github.com/redaxo/redaxo/issues/5413)

**Comment by skerbis** [comment]
Ich sehe das anders. Die Schweizer Kollegen würden diese Felder als lästig ansehen. 
Besser wäre hier eine variable Lösung die sich z.B. über den Table-Manager erweitern ließe und für die man bestimmte Sets zu passenden Szenarien bereitstellen könnte.

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/yrewrite_metainfo

**Comment by alxndr-w** [comment]
Wobei ich es schlimm finde, in REDAXO mittlerweile für jeden Standard-Fall ein Addon zu benötigen und 30 Tabellen im YForm Table Manager das System echt ausbremsen.
