### ISSUE TITLE
Feature-Wunsch: URL-Rewriting deaktivieren können

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_yrewrite#518]
In einem Szenario, in dem ich mir wie heute ratlos den Kopf kratze, was das Problem im Zusammenhang mit dem Rewriting sein könnte, wäre es hilfreich gewesen, nur das Rewriting deaktivieren zu können - sodass alle URLs wieder nach dem Schema `?article_id=#` generiert werden.

Das Addon YRewrite zu deaktivieren hingegen war keine Option, da davon abhängige Addons ebenfalls hätten deaktiviert werden müssen und das wiederum zum Whoops im Frontend geführt hätte.

**Comment by cukabeka** [comment]
Hatte ich auch schon 👍
