### ISSUE TITLE
Artikel: Option Umleitung zu URL funktioniert seit v2.9.1 nicht mehr

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_yrewrite#519]
Die Option Umleitung zu URL im Artikel funktioniert nicht mehr wie erwartet.
Beim Aufruf der ursprünglichen Artikel-URL wird statt einer Umleitung auf die angegebene Ziel-URL die 404-Seite aufgerufen.
In Version 2.9.0 wird noch wie erwartet auf die angegebene Ziel-URL umgeleitet.

**Comment by skerbis** [comment]
Kann ich nicht bestätigen? Url falsch eingegeben?

**Comment by skerbis** [comment]
Kann ich nicht bestätigen ... Hier ein Test: http://klxm.de/wp-admin/

**Comment by DanielWeitenauer** [comment]
Upsi. Nach erneutem Update klappt es bei mir auch.
