### ISSUE TITLE
Löschen von Kategorien/Artikel vermeiden

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#52]
Sind Artikel als
- Startpunkt der Domain
- Startartikel der Domain
- 404 Artikel

zugewiesen, dann sollte das löschen unterbunden werden.

**Comment by alxndr-w** [comment]
@tbaddade kann ich mir das irgendwo abschauen, wie das verhindert wird? Bereits jetzt wird ja schon geprüft, ob ein Artikel gelöscht werden kann/darf bei YRewrite Mountpoints o.ä. - Hast du mir einen Tipp, dann schaue ich, ob ich einen PR machen kann.

**Comment by tbaddade** [comment]
> kann ich mir das irgendwo abschauen, wie das verhindert wird?

Das Url Addon löst es so:
https://github.com/tbaddade/redaxo_url/blob/master/boot.php#L64-L73
