### ISSUE TITLE
Mehrere Sprachen mit gleichem Namen

### ISSUE THREAD

**Issue by marcohanke** [yakamara/redaxo_yrewrite#526]
Ich habe gerade eine Instanz mit 5 Domains und insgesamt 13 Sprachen. Einige davon sind mehrfach vorhanden (DE-de AT-de, DE-en, AT-en, FR-en ....). Im System lege ich die Sprachen mit unterschiedlichen Codes, aber identischen Namen an. Leider kann ich die Sprachen in yrewrite so nicht auswähen. Es würde Sinn machen im Select neben der Sprache den Code in Klammern mit anzuzeigen
- Deutsch (DE-de)
- Deutsch (AT-de)
...
Im Moment packe ich das Kürzel im Namen mit dran und trimme es bei der Ausgabe wieder. Das geht, ist aber nicht schön.

**Comment by gharlan** [comment]
Gemäß https://github.com/redaxo/redaxo/issues/5531 schließe ich auch hier.
