### ISSUE TITLE
Domain Tabelle über XForm Tablemanager verwalten

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#54]
Vorteil wäre, dass man spezielle Domainabhängigkeiten direkt nachrüsten kann.

Bspl. 
- Logo
- Suchausgabeartikel
- Linklist Button für Footernavi
- ...

**Abrufbar über**

`rex_yrewrite::getDomainByArticleId($article_id)->getValue('label')`

**Comment by dergel** [comment]
Im Moment sehe ich das nicht beim Rewriter .. Aber natürlich bringt eine Multidomainfähigkeit solche Dinge mit sich.. Nur, dass kann man schlecht allgemein festzurren, aber vielleicht schon über einen EP ergänzen ? Würde dir das reichen ?

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/45

**Comment by alexplusde** [comment]
Würde auch globale Meta-Infos ermöglichen. 
+1

**Comment by dergel** [comment]
gibt ein anderes issue dazu was ich für Version 2.x angedacht habe.. ich schliesse das hier.
