### ISSUE TITLE
Medienpool, Dateilöschung - Prüfung

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#55]
Werden Dateiverknüpfungen beim Medienpool Dateilöschen geprüft

**Comment by alexplusde** [comment]
Wo ist denn in YRewrite was mit Medien verknüpft?

**Comment by dergel** [comment]
keine ahnung .. ein Irrläufer ?

**Comment by tbaddade** [comment]
falsches Repo? Für YForm wäre das was.
https://github.com/yakamara/redaxo_yform/issues/450
