### ISSUE TITLE
Error bei Abruf von rex_yrewrite::getCurrentDomain()->getName(); in aktuellen Versionen, wenn keine Domain angelegt ist

### ISSUE THREAD

**Issue by iceman-fx** [yakamara/redaxo_yrewrite#561]
Wenn ein Modul oder Addon folgenden Abruf versucht:
`rex_yrewrite::getCurrentDomain()->getName();`

und im yRewrite keine Domain hinterlegt ist, dann kommt immer dieser Fehler:
`Call to a member function getId() on null`

Dies sollte man evtl. abfangen und keinen Fehler liefern.

**Comment by tbaddade** [comment]
> Dies sollte man evtl. abfangen und keinen Fehler liefern.

Das solltest du selbst machen.

```
$domain = rex_yrewrite::getCurrentDomain();
if ($domain) {
    echo $domain->getName();
}
```
