### ISSUE TITLE
Htaccess Expires anpassen

### ISSUE THREAD

**Issue by RexDude** [yakamara/redaxo_yrewrite#58]
Hi Jan :)
Freut mich das du dich an der SEO42 . htaccess bedient hast :D ...siehe https://github.com/yakamara/redaxo_yrewrite/commit/5052235a1952337e7f505fe31483c6fdd3e23d65
Hat mich viel Zeit und Recherchen gekostet das Baby so aufzubauen ;)
Du musst aber acht geben, weil eine sehr hohe Cachingdauer für CSS und JS angegeben wurde, weil SEO42 hier einen Versionsmechanismus hat so dass automatisch immer die aktuellen Dateien ausgeliefert werden. Also entweder Cachingdauer reduzieren oder Versionsmechanismus einbauen würde ich vorschlagen.

Mehr hier: https://github.com/RexDude/seo42#hinweis-zur-mitgelieferten-htaccess-datei
Und hier: https://github.com/RexDude/seo42/blob/master/FAQ.md#warum-soll-man-mit-seo42getcssfile-und-seo42getjsfile-seine-cssjs-dateien-ausgeben-lassen

**Comment by dergel** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/92

hab ich mal als neues issue reingenommen.-
