### ISSUE TITLE
"komisches" verhalten wenn keine domain definiert ist

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yrewrite#59]
Direkt nach Installation in die Struktur/Content Verwaltung wechseln und dort folgende Tabs aufmachen:
- Reiter "URL" in einem Startartikel-> `Dies ist der Startartikel der Domain "undefined" und kann nicht verändert werden. Die URL ist hier immer "/"`
- Reiter "URL" in einem normalen Artikel -> `http[s]://undefined/system.html`

**Comment by staabm** [comment]
hier steht 2x "undefined"

**Comment by dergel** [comment]
genau .. weil noch nichts definiert ist .. gerade auch weil es multidomainfaehig ist, 404 Artikel hat, die vielleicht noch gar nicht existieren etc. ist das schwierig. Eventuell könnte man direkt die aktuelle Domain, falls nichts vorhanden ist, bei der Installtion verwenden..

**Comment by gharlan** [comment]
-> #13
