### ISSUE TITLE
"Artikel anzeigen" link funktioniert nicht wenn redaxo in Unterordner installiert

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yrewrite#60]
Der Link zeigt immer in den Domain-Root.

Ohne yrewrite funktioniert es mit dem "default-core-rewriter" richtig

**Comment by tbaddade** [comment]
Die Info ist ein wenig versteckt aber yrewrite ist nicht für Unterordner gedacht.

https://github.com/yakamara/redaxo_yrewrite/blob/master/lang/de_de.lang#L93

**Comment by staabm** [comment]
Sollte man ggf beim installieren dann schon nen fehler bringen?

**Comment by tbaddade** [comment]
Wäre eine Möglichkeit. @dergel was hälst du davon?

**Comment by gharlan** [comment]
Unterordner werden nun unterstützt
