### ISSUE TITLE
R5: Domain /deutsch/ in /de/

### ISSUE THREAD

**Issue by Sioweb** [yakamara/redaxo_yrewrite#62]
Wäre super, wenn man wählen könnte dass die Domain /de/ statt /deutsch/ nutzt bzw. die Sprache für die Default-Sprache nicht in die Domain eingefügt werden würde.

**Comment by gharlan** [comment]
> Wäre super, wenn man wählen könnte dass die Domain /de/ statt /deutsch/ nutzt

Meiner Meinung nach sollten wir allgemein den Sprachcode nehmen statt des Namens.

> bzw. die Sprache für die Default-Sprache nicht in die Domain eingefügt werden würde.

Soweit ich weiß, ist das zurzeit nur programmatisch erreichbar (eigene Schema-Klasse), falls die Sprachen trotzdem alle über eine Domain laufen sollen.
Was aber schon einstellbar wäre, ohne eigene Klasse: deutsch über .de-Domain (ohne `/de/`), alle anderen Sprachen über eine andere Domain mit Sprache im Pfad.

**Comment by tbaddade** [comment]
> Meiner Meinung nach sollten wir allgemein den Sprachcode nehmen statt des Namens.

Du meinst mit Code "de-de" oder "de"?

Jedenfalls sollte man es selbst festlegen können. Wir brauchten vor kurzem diese Schreibweise "en-br, pt-br, es-br"

**Comment by gharlan** [comment]
Ich meine den unter System angegeben Code, was auch immer dort eingetragen wurde.

**Comment by tbaddade** [comment]
Dann sind wir bei R5 und nicht mehr bei R4 :).

**Comment by Sioweb** [comment]
Hab den Titel mal angepasst. Ich würde auch einfach den Code nehmen der eingetragen ist. Wenn man de_de braucht erstellt man die Sprache einfach.

**Comment by gharlan** [comment]
Es wird nun der Sprachcode verwendet.

**Comment by dergel** [comment]
das hier ist noch offen .. des rest steht ja

https://github.com/yakamara/redaxo_yrewrite/issues/85
