### ISSUE TITLE
Metadaten unklar / Darstellungsfehler

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#63]
Bei den SEO Metadaten ist die Bezeichnung "URL aktualisieren" recht unklar finde ich.

In der Box für die URL sollte es einen eigenen Button geben.

Dann gibt es noch einen Darstellungsfehler (siehe Bild).

![unbenannt-2](https://cloud.githubusercontent.com/assets/330516/11779184/cb26cf92-a259-11e5-93ec-dd400eac16a6.png)

**Comment by staabm** [comment]
Wg "undefined" siehe https://github.com/yakamara/redaxo_yrewrite/issues/59

**Comment by olien** [comment]
Das meinte ich nicht. Ich meinte, dass der Text aus dem Conatiner läuft und das Eingabefeld so klein ist ... :.-)

**Comment by dergel** [comment]
Sollte bereits beides seit einiger Zeit passen:

![bildschirmfoto 2016-01-26 um 00 07 27](https://cloud.githubusercontent.com/assets/322951/12567680/d1310bcc-c3c0-11e5-95f1-8535da871966.png)
![bildschirmfoto 2016-01-26 um 00 07 32](https://cloud.githubusercontent.com/assets/322951/12567682/d2c8f80a-c3c0-11e5-9343-15d2a222447e.png)

wenn nicht .. bitte aktueller entwickler version prüfen und bei fehler browser/version angeben..
