### ISSUE TITLE
URL-Parameter wird abgeschnitten, wenn param nicht mit ? anfaengt

### ISSUE THREAD

**Issue by tzfrs** [yakamara/redaxo_yrewrite#64]
Hallo,

ich baue mir eine URL wie folgt:

`rex_getUrl($articleId, '', 'id=1')`

Das Problem hierbei ist, dass - wie ich glaube - durch diese Zeile hier

`$urlparams = $urlparams == '' ? '' : '?' . substr($urlparams, 1, strlen($urlparams));`

der erste Buchstabe vom String weggenommen wird. Heisst, man muss URLs entweder so

`rex_getUrl($articleId, '', '?id=1')`

angeben, was meiner Meinung nach keinen Sinn macht, da der oben genannte Code, das Fragezeichen ja wieder loescht und selbst eins hinzufügt, *ODER* man macht es per Array

`rex_getUrl($articleId, '', ['id' => 1])`

mMn. sollte der erste Buchstabe nicht einfach weggenommen werden, denn entweder ist es - wie in meinem Fall - ein Buchstabe, oder, wenn es ein Fragezeichen ist, dann wird es eh entfernt und wieder hinzugefügt. 

Aber vielleicht kannst du mir sagen, aus welchem Grund die Funktionalitaet so ist? Vllt. übersehe ich auch etwas.

**Comment by gharlan** [comment]
Es werden in R5 grundsätzlich nur noch Arrays akzeptiert. Somit hat sich das Problem erübrigt
