### ISSUE TITLE
Artikel (URLs) einer Domain zuweisen

### ISSUE THREAD

**Issue by tzfrs** [yakamara/redaxo_yrewrite#65]
Hi,

ich habe in den Einstellungen von YRewrite eine Domain eingetragen. Wie kann ich nun dafür sorgen, dass meine URLs der Domain angehoeren? Bei allen URLs steht weiterhin "undefined" als Domain, anstatt die, die ich eingetragen habe. Wie kann ich alle meine URLs der Domain zuweisen?

Dies ist besonders nervig, da die Variable `$REX['SERVER']` dadurch komplett nutzlos gemacht wird, da dort dann überall `undefined` drin steht.

**Comment by tbaddade** [comment]
> Wie kann ich nun dafür sorgen, dass meine URLs der Domain angehoeren?
das passiert automatisch

undefined sollte eigentlich nicht mehr vorkommen. Hast du mal den Cache gelöscht?
Bei dir geht es um die Redaxo 4 Version?

**Comment by tzfrs** [comment]
Hey,

Cache loesche ich ziemlich oft (paar mal am Tag), weil ich noch in der Entwicklungsphase der Seite bin. Und ja, bei mir geht es um Redaxo Version 4.6.1

**Comment by dergel** [comment]
seltsam .. mount point einfach mal leer lassen.. vielleicht ist das noch ein einstellungsproblem. 
in yrewrite muss die domain eingetragen werden.. und ja. die allgemeine server wird dadurch nutzlos.. es werden nur die domains von yrewrite verwendet .. dort kann man auch mehrere domains in verschiedenen ebenen zuweisen (falls nötig) .. ich schliesse das mal - kann im moment keinen fehler entdecken
