### ISSUE TITLE
Custom replacements für Chars

### ISSUE THREAD

**Issue by tzfrs** [yakamara/redaxo_yrewrite#66]
Hi,

in der Klasse `rex_yrewrite_scheme` gibt es ja folgenden Code

    array('Ä', 'Ö', 'Ü', 'ä', 'ö', 'ü', 'ß'),
    array('Ae', 'Oe', 'Ue', 'ae', 'oe', 'ue', 'ss')

Damit werden ja Umlaute in ein "Url-friendly" format gebracht. Ist es irgendwie moeglich, dass man auch eigene replacements hinzufügt?

Z.b. haben wir Artikel, in deren namen ein `&` ist. Dort würde ich gerne - je nach Sprache - das `&` durch `and`/`und` ersetzen.

Ich hab das jetzt haendisch in die Klasse eingetragen

    $andReplacement = $clang === 0 ? 'and' : 'und';
    $string = str_replace(
        array('Ä', 'Ö', 'Ü', 'ä', 'ö', 'ü', 'ß', '&'),
        array('Ae', 'Oe', 'Ue', 'ae', 'oe', 'ue', 'ss', $andReplacement),
        $string
    );

Aber das Problem ist ja:

1. Das ist ne richtige quick-and-dirty-Loesung
2. Wenn ich das Plugin jemals update, sind meine Aenderungen wieder weg. Gibt's dazu eine Moeglichkeit?

**Comment by gharlan** [comment]
Eigenes Addon oder Plugin schreiben, dort eine eigene Schema-Klasse erstellen, die von der Basisklasse erbt. Die entsprechende Methode überschreiben.
Und Scheme-Klasse setzen:

```php
rex_yrewrite::setScheme(rex_my_scheme());
```

**Comment by tzfrs** [comment]
Alles klar, hab ich so gemacht. Danke!
