### ISSUE TITLE
Wunsch / Anregung: URLs für "andere" Sprache

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#68]
Hallo Zusammen,

vielleicht geht es ja schon.

Ich hatte jetzt den Fall (und es ist anscheinend nicht unüblich), dass für die kyrillische Version einer Webseite die englischen URLs gewünscht sind...

Vielleicht kommt das ja öfter vor.

LG
Oliver

**Comment by tbaddade** [comment]
Kannst du am besten mit einem eigenen Scheme lösen.
https://github.com/yakamara/redaxo_yrewrite/wiki/Eigenes-Scheme-verwenden-und-registrieren

**Comment by olien** [comment]
Danke!
