### ISSUE TITLE
URL in der Pathlist aktualisieren, wenn man eine Custom URL auswaehlt

### ISSUE THREAD

**Issue by tzfrs** [yakamara/redaxo_yrewrite#69]
Hallo,

wenn ich einen Artikel habe, und dann diesem Artikel eine Custom URL über das "URL"-Tab gebe, dann muss ich erst einmal den Cache loeschen, bevor diese URL-Aenderung aktiv wird (? denk ich zumindest).

Ist das Verhalten so gewollt? Sollte nicht beim Eintragen der URL die URL in der Pathlist aktualisiert werden? Ich würd auch'n PR machen, falls ihr das nicht so gewollt habt, dass sich die URL erst nach dem Cache loeschen aktualisiert, oder ihr sagt mir, ob ich was falsch mache. :p

**Comment by dergel** [comment]
der cache sollte sich eigentlich von selbst löschen.. gerne nachsehen und als PR :)

**Comment by gharlan** [comment]
@tzfrs R4 oder R5?
Zumindest in R5 kann ich es nicht nachvollziehen

**Comment by tzfrs** [comment]
Hallo,

es geht um R4.
