### ISSUE TITLE
Urls bei Installation im Unterordner funktionieren nicht

### ISSUE THREAD

**Issue by wexstorm** [yakamara/redaxo_yrewrite#71]
Wird Redaxo in einem Unterordner
z.B. http://www.domain.de/cms/
betrieben, so funktionieren alle Aufrufe der Urls nicht. Auch ein Setzen der RewriteBase in der .htaccess-Datei führt nicht zum Ziel.

<?php 
$art = rex_article::get(2); 
echo $art->getUrl(); 
?>

Urls werden dann z.B. zu
http://www.domain.de/seite.html
und nicht
http://www.domain.de/cms/seite.html
konvertiert.

**Comment by tbaddade** [comment]
Wenn du die Setupseite von yrewrite aufrufst, dann findest du folgenden Text: https://github.com/yakamara/redaxo_yrewrite/blob/master/lang/de_de.lang#L93
