### ISSUE TITLE
Unterverzeichnisse

### ISSUE THREAD

**Issue by polarpixel** [yakamara/redaxo_yrewrite#72]
Im Forum hört man häufiger, dass Leute Redaxo auch mal gern in einem Unterverzeichnis installieren. 
Es wäre daher also nicht schlecht zu prüfen, ob man Yrewrite so ändern kann, dass dies möglich ist.

**Comment by phoebusryan** [comment]
+1 dafür; wir haben dies mehrmals bei R4 so umsetzen müssen, wenn wir zum Beispiel ein Shop und R4 gekoppelt haben.
