### ISSUE TITLE
yform abkoppeln

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_yrewrite#73]
Warum benötigt das AddOn yform? Ich persönlich finde es sehr unschön wenn man für alles mögliche Abhängigkeiten hat.

Insbesondere yform ist aus meiner Sicht nur da sinnvoll wo man die Formulare bearbeiten kann. Das ist ja soviel ich weiss in yrewrite nicht möglich.

**Comment by ex-q** [comment]
Sehe ich genauso! :)

**Comment by dergel** [comment]
haben das hier auch diskutiert. Wohl eher meine persönliche Vorliebe.. Nehmen wir gerne als Pull request an..

**Comment by ex-q** [comment]
Das wär natürlich cool, vllt. find ich die Zeit!
Soweit ich das sehe kommt yform nur bei den Pages zum Einsatz. D.h. yform auf rex_form umbauen und es würde passen, richtig?

**Comment by dergel** [comment]
genau .. alles auch rex_forn und gut ist .. plus die entsprechenden validierungeb durchgehen

**Comment by dergel** [comment]
im moment für mich nicht relevant und auch unwahrscheinlich, dass das passieren wird. (da relativ aufwändig) ..
