### ISSUE TITLE
Alte URLs als Redirect übernehmen ?

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#78]
z.B. wenn man eine URL eines Artikels ändert, als Option die alte URL direkt in die redirect liste mit Weiterleitung übernehmen ?

**Comment by alexwenz** [comment]
Jajajajajaja! Bittebitte!

**Comment by TobiasKrais** [comment]
Der Issue ist obsolet. Das kann die aktuelle Version. Bitte schließen.
