### ISSUE TITLE
yrewrite_index default auf 1 setzen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#79]
Dann könnte man diese Zeile verkürzen und es gebe weniger Verwirrungen

https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/seo.php#L51

Wir hatten schon den Fall das Artikel online sein mussten (offline Artikel wurden weitergeleitet) aber nicht indexiert werden durften.

**Comment by dergel** [comment]
im moment ist es ja so:

alle artikel sind default 0 und daher werden nur die online artikel indiziert
aber manuell kann man die indizierung auf index oder noindex setzen..

wie wäre es dir lieber ? im moemnt klingt für mich das vorhandene sinnvoll

**Comment by dergel** [comment]
vorhandenes lassen wir
