### ISSUE TITLE
Bei Installation automatisch die erste Url (Systempage) anlegen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#80]

**Comment by gharlan** [comment]
Weiß nicht. Eigentlich muss man ja gar keine Domain anlegen, solange man nur eine verwendet.

**Comment by tbaddade** [comment]
> Eigentlich muss man ja gar keine Domain anlegen, solange man nur eine verwendet.

Eben doch, deshalb dieses Issue.

**Comment by gharlan** [comment]
Warum muss man das?

**Comment by tbaddade** [comment]
undefined Probleme

**Comment by gharlan** [comment]
Konkret? 
Eigentlich habe ich es ohne Domain durchgetestet, und es schien mir zu passen.

**Comment by tbaddade** [comment]
Bei Aufruf eines Artikel erfolgt
```
"ErrorException" thrown in /addons/yrewrite/lib/yrewrite.php on line 310
Fatal error: Call to a member function getUrl() on a non-object
```

**Comment by gharlan** [comment]
Hast du mal den Cache gelöscht?

Das mit undefined habe ich gelöst.

**Comment by olien** [comment]
Hm. Wenn ich keine Domain angebe wird die Sitemap nicht richtig erzeugt.

**Comment by gharlan** [comment]
> Bei Installation automatisch die erste Url (Systempage) anlegen

yrewrite soll auch funktionieren, wenn keine URL angelegt ist. Daher schließe ich hier.

Eventuell noch bestehende Probleme mit der Default-Domain bitte als Einzelissues anlegen.
(Für die Sitemap hat Oli das schon getan.)
