### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#82]
Wenn keine Domain angeben ist wird die Sitemap nicht erzeug.
Ist eine Domain angegeben wird die Sitemap nur so erzeugt:

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>http://abc.de/</loc>
<lastmod>2016-02-03T09:03:35+01:00</lastmod>
<changefreq>weekly</changefreq>
<priority>1.0</priority>
</url>
</urlset>

Sämtliche Kategorien fehlen.

**Comment by olien** [comment]
War ein Fehler in den Einstellungen. Sorry

**Comment by gharlan** [comment]
Inwiefern?
Kann das hier nachvollziehen. Wenn keine Domain angelegt, ist die Sitemap leer.

**Comment by skerbis** [comment]
a) muss ich eine Sitemap anlegen?
b) Wenn ich eine Domain anlege ist die Sitemap bei mir auch leer

**Comment by gharlan** [comment]
a) Gedacht ist es so, dass man keine anlegen muss
b) Dann ist es bei dir genau andersrum als bei mir und Oli

**Comment by gharlan** [comment]
Zu b) habs glaube ich falsch verstanden, also bei dir ist sie immer leer, mit und ohne Domain?

**Comment by skerbis** [comment]
Mit Domain: 

```
urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>http://www.grund-gruppe.de/</loc>
<lastmod>2016-02-09T15:22:09+01:00</lastmod>
<changefreq>weekly</changefreq>
<priority>1.0</priority>
</url>
</urlset>
```

ohne Domain:

`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>`

**Comment by skerbis** [comment]
ah… wenn ich denStartpunkt leer lasse klappt es. Dachte der wäre Pflicht
