### ISSUE TITLE
Immer 404 bei allen Unterseiten

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#83]
Sofern ich eine Domain angebe und eine Seite aufrufe wird die 404er Seite ausgeben (trotz richtiger URL Angabe).

**Comment by gharlan** [comment]
Die htaccess hast du installiert/kopiert?

**Comment by gharlan** [comment]
Wie hast du die Domain genau angegeben? (mit http?, mit www?, mit slash hinten? etc..)

**Comment by olien** [comment]
.htacces installiert (auf button geklickt)

URL 

http://hallo.de/

**Comment by gharlan** [comment]
und du rufst auch ohne www auf?

**Comment by olien** [comment]
Ähm. Sorry. Richtig ist hier:

http://2016.hallo.de

also eine Subdomain...

**Comment by olien** [comment]
Hat sicher erledigt. Bei der Verwendung von nur einer Domain muss das Feld 'Startpunkt der Domain' leer bleiben / Danke an gharlan
