### ISSUE TITLE
Setup Erklärung

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#84]
Hier fehlt (mir) die Erklärung wie jetzt mit den Angaben unter System umzugehen ist. Das finde ich verwirrend.

URL, Start- bzw. Fehlerartikel

**Comment by dergel** [comment]
dastimmt.. könnte man gut als notiz unterhalb ds texteingabefeldes machen ? Textideen die du gut fändest ?

**Comment by olien** [comment]
ich kann geren was schreiben wenn ich wüsste was. :-)
ich weiß ja nicht wie ich mit den Feldern dort umzugeben habe

**Comment by dergel** [comment]
ach so .. habe ich falsch gelesen.. dachte du kämst mit den eingaben der domain innerhalb von yrewrite nicht klar.. die eintragung unter system werden komplett ignoriert

**Comment by olien** [comment]
ok. danke
