### ISSUE TITLE
Default-Sprach-Code nicht in die URL als Option aufnehmen ?

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#85]
weiss nicht ob das unbedingt nötig ist .. 
Ich denke, dass der Sprachcode ruhig immer in der URL drin sein kann.

**Comment by dergel** [comment]
würde z.B. heissen

Default Sprache = deutsch .. URL: /impressum
oder
Default Sprache = deutsch .. URL: /de/impressum
nebensprach englisch URL: /en/imprint
nebensprache franz. URL: /fr/legal

@tbaddade @tbaddade

**Comment by tbaddade** [comment]
Ich denke schon, dass man optional pro Domain einen Slug verstecken könnte.

**Comment by dergel** [comment]
Quasi als Option aufnehmen ?
Ich stehe nicht so auf viele Einstellmöglichen, deswegen würde ich das gerne abwägen wollen - ob wirklich nochwendig.

**Comment by tbaddade** [comment]
> Quasi als Option aufnehmen ?

Genau. Ich wäre dafür. Ob als Einstellungsmöglichkeit oder man setzt es im Scheme irgendwie, wäre mir egal.

**Comment by gharlan** [comment]
Im Scheme kann man es jetzt schon erreichen.

**Comment by tbaddade** [comment]
> Im Scheme kann man es jetzt schon erreichen.

Ich meinte eher eine $var anpassen und schon passt es.

**Comment by gharlan** [comment]
Bin auch für Aufnehmen als Option

**Comment by staabm** [comment]
Würde im Falle der neuen Option dann ein /de/impressum auf /impressum weiterleiten oder würden urls die explizit die default locale erwähnen nen 404 liefern?

**Comment by gharlan** [comment]
Beides denkbar. Was würdest du sagen?

Ich bin übrigens nicht für's Aufnehmen, weil ich es nutzen wollen würde, sondern weil öfters nach der Funktion gefragt wird. Aktuelles Beispiel: http://www.redaxo.org/de/forum/post118871.html

**Comment by staabm** [comment]
einfacher wäre vermutlich ohne Umleitung. Beide Lösungen sind denkbar, man muss nur schauen dass man duplicate content vermeidet.

**Comment by dergel** [comment]
wegen mir können wir das aufnehmen. Bin kein Fan davon, aber mein Gott ;) ..

**Comment by polarpixel** [comment]
Mir würdet Ihr auch eine Freude machen damit ... daher: Danke!
