### ISSUE TITLE
Error 500 auf Unterseiten

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#91]
Hi,

wenn ich yrewrite nutze (aktulle GitHub Version) bekomme ich auf allen Seiten (ausser Startseite folgende Fehlermeldung:

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
> More information about this error may be available in the server error log.
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Dabei ist es egal ob ich eine Domain angebe (ohne Startpunkt) oder unter "Domains" nichts eintrage.

LG
Oliver

**Comment by dergel** [comment]
Cache gelöscht ? .. Leider schwer mit der Meldung was anzufangen - das kann so ziemlich alles sein . Andere AddOns mal deaktiviert ? Ansonsten gib mir mal den Zugang (wenn online), dann kann ich mir das anschauen

**Comment by olien** [comment]
Gregor war schneller :-) ist schon in Arbeit bzw. fast geklärt :-)

**Comment by dergel** [comment]
top :)

**Comment by gharlan** [comment]
Liegt an der `RewriteBase`-Geschichte.
