### ISSUE TITLE
htaccess Cachingmechanismen mit aufnehmen ?

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#92]
bin mir unsicher ob das für mich hier reingehört.

**Comment by dergel** [comment]
@tbaddade @gharlan was meint ihr ?

**Comment by gharlan** [comment]
Bin mir auch unsicher. Tendiere zu "nein".

**Comment by staabm** [comment]
vllt sollte man es ermöglichen dass man eigene regeln für die .htaccess via addon editieren/ablegen kann?

**Comment by tbaddade** [comment]
Einerseits wäre es schon gut andererseits gehört das weniger in das AddOn. Da aber yrewrite die htaccess bereits setzt, tendiere ich eher Richtung "ja".

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues

**Comment by alexplusde** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/113

**Comment by dergel** [comment]
in die htaccess reinhaengen können

https://github.com/yakamara/redaxo_yrewrite/issues/122
