### ISSUE TITLE
sitemap.xml -> geschütze Seiten ignorieren

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yrewrite#93]
Abhängig vom Community Addon...

**Comment by dergel** [comment]
Ich glaube, soweit ich das von R4 noch im Kopf habe, dass sich das Community Addon dort reinhängt.

**Comment by olien** [comment]
Ok. Mal sehen wie es für Rex5 wird ;-)

**Comment by dergel** [comment]
iat bereits drin..

**Comment by skerbis** [comment]
Ist leider nicht der Fall: https://github.com/yakamara/redaxo_yrewrite/issues/166

**Comment by isospin** [comment]
bin da auch gerade drüber gestolpert...
die internen urls sind in der sitemap, wenn ich als user in ycom eingeloggt bin
nachdem ich mich ausgeloggt habe sind die internen urls nicht drin...
@skerbis & @olien könnt ihr das bestätigen? dann könnte @dergel das issue schliessen
