### ISSUE TITLE
Infotexte

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#94]
Mountpoint scheint unklar zu sein und auch die diversen anderen Werte sollte man über eine Notiz genauer erklären.

Gerne hier Vorschläge für Infotexte (1-2 Sätze) pro Eintrag posten. @olien Hast Du Ideen ?

**Comment by olien** [comment]
Ich weiß gar nicht ob ich das richtig verstanden habe :-)) Ich verusche es mal so:

---

Unter Tipps ergänzen:

Wird mehr als eine Domain benutzt kann (muss?) für jede Domain ein Startpunkt der jeweiligen Domain sowie der Startartikel angegeben werden. Bitte darauf achten, dass auch unterschiedliche 404er Seiten angegeben werden sollte.

**Comment by tbaddade** [comment]
**Domain:**
Läuft REDAXO in einem Unterordner, muss dieser mit notiert werden.
Beispiel: `http://domain.de/unterordner/`
[Via Forum](http://www.redaxo.org/de/forum/templates-navigationen-f45/breadcrumb-eigene-klassen-t20906.html#p117771)

**Mountpoint**
Startpunkt der Domain. Der Startpunkt kann in jeder Tiefe der Struktur vergeben werden. Die oben angegebene Domain gilt ab dort für alle weiteren Kategorien/Artikel. Zum Beispiel kann eine zweite Domain innerhalb der Struktur einer anderen Domain einen Startpunkt bekommen. Freilassen, wenn Root-Kategorien als Url benötigt werden.

**Startartikel**
Artikel angeben der als Startartikel der Domain aufgerufen wird. Kann via `rex_article::getSiteStartArticle()` geholt werden.

**404 Fehler**
Artikel angeben der als 404 der Domain aufgerufen wird. Kann via `rex_article:: getNotfoundArticleId()` geholt werden.

**Sprache**
Sprachen auswählen, die unter der Domain zu erreichen sind.

**Startsprache**
Welche Sprache soll beim Aufruf der Domain ausgegeben werden.

**Comment by olien** [comment]
besser! :+1:

**Comment by gharlan** [comment]
Ich finde den Begriff "Startpunkt" eher ungünstig. Verwechselt man zu schnell mit "Startseite". Würde eventuell direkt den englischen Begriff Mountpoint verwenden, oder "Einhängepunkt", oder "Wurzelkategorie" oder irgendwas in der Richtung.

Des Weiteren fände ich es gut, wenn man explizit per Checkbox auswählen könnte, dass die Domain für alles gilt. Das ist glaube ich weniger fehleranfällig, als wenn man das Feld leer lassen muss.

**Comment by gharlan** [comment]
Man könnte auch überlegen, ob man das Feld "Domain" umbenennt, da man eben nicht mehr immer nur eine Domain einträgt. Zum Beispiel "Basis-URL".

**Comment by tbaddade** [comment]
Bei "Startsprache" müssten alle Sprachen disabled sein, die vorher bei "Sprachen" nicht selektiert wurden.

**Comment by tbaddade** [comment]
Domain: wichtig wäre noch der Hinweis, ob `http`, ob Slash am Ende, was passiert mit www etc.

**Comment by gharlan** [comment]
> Domain: wichtig wäre noch der Hinweis, ob http, ob Slash am Ende, was passiert mit www etc.

Dazu schon mal als Erklärung:

* http/https ist optional. Wenn man es angibt, leiten alle Links immer auf das angegebene Protokoll. Lässt man es weg, wird das jeweils aktuelle verwendet. Kommt also drauf an, was man denn erreichen möchte.
* Slash am Ende oder nicht ist egal, das wird vom addon normalisiert
* www muss angegeben werden, wenn denn die Domain mit "www" genutzt wird. Für yrewrite ist es eine normale Subdomain.

**Comment by dergel** [comment]
ich habe diese texte mal so übernommen, weil ich sie fast durchweg gut fand und vor allem die nötigen Informationen beinhalten

**Comment by dergel** [comment]
die texte sind drin .. tauchen aber nur ab yform beta4 auf, da notices bei be_link erst ab dann vorhanden sind..

**Comment by dergel** [comment]
will das jemand mal anschauen und sagen ob das so inhaltlich funktioniert.. Mir würde es so reichen ..

**Comment by dergel** [comment]
wenn jemand was besseres weiss - gerne her damit .. ich schliesse dieses issue

**Comment by cukabeka** [comment]
> Ich finde den Begriff "Startpunkt" eher ungünstig. Verwechselt man zu schnell mit "Startseite". Würde eventuell direkt den englischen Begriff Mountpoint verwenden, oder "Einhängepunkt", oder "Wurzelkategorie" oder irgendwas in der Richtung.
> 
> Des Weiteren fände ich es gut, wenn man explizit per Checkbox auswählen könnte, dass die Domain für alles gilt. Das ist glaube ich weniger fehleranfällig, als wenn man das Feld leer lassen muss.

Bei Slack hatten wir wieder eine Diskussion darüber, weil ich tatsächlich auch in die Mountpoint-Falle getappt bin. (Konnte bei einer Single-Domain-Installation auf keine Artikel mehr zugreifen, sobald der Mountpoint gesetzt war, alles führte auf die Startseite, die auch als MP eingetragen war.) Dachte bei MP an Filesystem und hab nicht kapiert, was es in Redaxo tut. Ich finde _Wurzelkategorie_ deutlich besser, aber auch noch nicht ideal.  Vielleicht "Root-Kategorie für die Domain"?
Was genau macht der Mountpoint denn im Unterschied zum Startartikel? Bei Multidomain-Installs ist mir das klarer als bei Singledomain-Installs. 
Möglicher Text dazu: "Die Wurzelkategorie bestimmt, welche Page ID zurückgegeben wird bei getRootCategory() zurückgegeben wird. Alle Artikel und Kategorien oberhalb bleiben "unsichtbar" für getParentCategory etc." – falls man das überhaupt so sagen kann?

Wichtig fände ich folgende Ergänzung: `"Kann bei Installationen mit nur einer Domain zu Problemen führen und sollte dann leergelassen werden."` Ich fände gut, wenn auch markiert ist, welche Felder ich ausfüllen muss und welche nicht.
Evtl hilft hier die Idee von @gharlan mit der Checkbox. Wobei ich _"dass die Domain für alles gilt"_ noch etwas unklar finde: Was genau gilt für was alles? Also die Startpunkte und

**Comment by tyrant88** [comment]
Den Vorschlag mit "Root-Kategorie" finde ich fast optimal. Beschreibt was es tut und es wird klar, dass eine Kategorie auszuwählen ist.

**Comment by alxndr-w** [comment]
Leider lassen sich keine Kategorien in dem Dialog auswählen und es ist zulässig, dass auch ein Artikel ausgewählt wird, der nicht der Startartikel ist sowie Kategorien unterhalb von anderen Kategorien, nicht nur Root, weshalb Root-Kategorie auch schon wieder missverständlich sein könnte.

**Comment by cukabeka** [comment]
Hm, vielleicht so: "Startebene durch Artikel der entsprechenden Kategorie auswählen. Die Startebene bestimmt, ab welcher hierarchischen Kategorie der Kategorie Baum aufgebaut wird"? 
Aber auch wenn ich einen Artikel einer Sublevel Kategorie auswähle, der nicht Startartikel ist, mache ich das ja nur, um die Kategorie festlegen, oder? Der tatsächliche Artikel hat ja keinen Einfluss auf das Ergebnis, sondern bestimmt die Kategorie, richtig?

Wichtig ist mir allerdings vor allem der Hinweis für die Single Domain Fälle mit den nicht zugreifbaren Artikeln.

**Comment by tyrant88** [comment]
@alxndr-w das der DIalog nicht passt, okay. Aber es geht darum ein "root" festzulegen und nicht auszuwählen, deshalb kann das natürlich in anderen enthalten sein....
@cukabeka mir ist gerade wichtig, dass es NICHTS mit single oder Multi-domain zu tun hat. Hättest du in deinem Projekt mehrere domains gehabt und hättest denen als mountpoint einen Artikel zugewiesen, wäre genau dasselbe passiert.

> Aber auch wenn ich einen Artikel einer Sublevel Kategorie auswähle, der nicht Startartikel ist, mache ich das ja nur, um die Kategorie festlegen, oder? Der tatsächliche Artikel hat ja keinen Einfluss auf das Ergebnis, sondern bestimmt die Kategorie, richtig?
Genau das ist der Punkt und eben nicht der Fall.

In der readme steht:
"Mountpoint auswählen (optional). Das ist der Startartikel einer Kategorie, in der sich YRewrite einklinken soll. Alle Artikel unterhalb des Mount-Artikels sind dann über die Domain aufrufbar. Wird kein Artikel ausgewählt, sind alle Ebenen dieser Domain zugeordnet (Standard)"

Hier würde ich nur "auswählen" gegen "festlegen" austauschen.

**Comment by cukabeka** [comment]
Hi @tyrant88, 
danke dir. Dann verstehe ich das allerdings immer noch nicht, was der Mountpoint nun genau macht. Das Zitat aus der Readme finde ich hilfreich:
`Alle Artikel unterhalb des Mount-Artikels sind dann über die Domain aufrufbar.`- Aber ist denn nun relevant, welcher Artikel in einer Kategorie gewählt wird oder nicht? Wenn ich den Mount-Artikel festlege, ist es dann egal ob das ein Startartikel ist oder ein normaler Artikel? 

Die Änderung im Commit mit (optional) hilft glaube ich schon mal voll. 

Und ich verstehe, dass single- und multidomain egal ist. Allerdings ist das Szenario mit dem Mountpoint vermutlich in einem Großteil der Multi-Fälle und in verschwindend wenigen Single-Fällen relevant. Vielleicht gibt es da noch eine Möglichkeit, darauf hinzuweisen, z.B. so:
"Mount-Artikel festlegen (meist bei mehreren Domains benötigt)"

**Comment by tyrant88** [comment]
>Alle Artikel unterhalb des Mount-Artikels sind dann über die Domain aufrufbar
Das ist wörtlich zu nehmen. D.h. wenn es kein Start-Artikel ist, gibt es keine Artikel "darunter". Dann ist eben nur dieser Artikel aufrufbar.

**Comment by cukabeka** [comment]
Aha! Das finde ich essentiell: 

> Das ist wörtlich zu nehmen. D.h. wenn es kein Start-Artikel ist, gibt es keine Artikel "darunter". Dann ist eben nur dieser Artikel aufrufbar.

Das steht noch nirgendwo in der Doku, soweit ich das sehe. Diese Passage wäre nützlich für die Notice darunter, finde ich.
