### ISSUE TITLE
Methode getMountpointId() fehlt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#95]
Damit man die Root Kategorien der Domain einfach abholen kann

**Vorher**
```php
$currentPath = rex_article::getCurrent()->getPathAsArray();
$domainStartId = $currentPath[0];
$domainRootCategories = rex_category::get($rootId)->getChildren(true);
```

**Idee 1**
```php
$domainRootCategories = rex_category::get(rex_yrewrite::getMountpointId())->getChildren(true);
```

**Idee 2**
```php
$domainRootCategories = rex_yrewrite::getRootCategories();
```

oder man hängt sich in `rex_category::getRootCategories()` rein. Dann fehlt aber ein Zugriff auf die tatsächlichen Roots.

**Comment by gharlan** [comment]
Ich würde vermeiden, die Unterkategorien des Mountpoints als "RootCategories" zu bezeichnen, denn nach meinem Verständnis ist der Mountpoint selbst die "RootCategory". Jede Domain hat also genau einen Root-Kategorie.

**Comment by tbaddade** [comment]
Mir ist es gleich, wie man die Unterkategorien eines Mountpoints bezeichnet. Wichtig wäre nur, dass man sinnvoll an die Mountpoint Id herankommt um eben besser an die "Hauptnavi" heranzukommen.

Sobald ich eine Domain innerhalb einer anderen Domain anlege, wüsste ich jetzt nicht wie man sauber an deren Kategorien bekommt.

**Comment by gharlan** [comment]
So ganz allgemein kommt man an die MountId über die Domain.

```php
$domain->getMountId()
```

Domains kann man so abfragen:

```
rex_yrewrite::getDomainByName()
rex_yrewrite::getDomainByArticleId()
```

Was vor allem fehlt, ist eine Methode, um die aktuelle Domain zu erhalten.

**Comment by dergel** [comment]
rex_yrewrite::getCurrentDomain()->getMountId();

**Comment by tbaddade** [comment]
Unterschiedliche Ergebnisse

```php
echo rex_yrewrite::getDomainByArticleId(rex_article::getCurrentId());
echo rex_yrewrite::getCurrentDomain();

// default --> falsch
// www.domain.de
```

**Comment by tbaddade** [comment]
https://github.com/yakamara/redaxo_yrewrite/issues/96
