### ISSUE TITLE
Normalisierung der Artikelnamen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yrewrite#97]
Aktuell in einem Projekt:
`Artikel®`wird zu `artikelr`. Schöner wäre die Url ohne das ®.

**Comment by dergel** [comment]
eigentlich sollte das ® auch in der url auftauchen... das mit den replacements haben wir in der schemata klasse gelöst, man kann also selbst entscheiden welche man gerne wie ersetzt hätte.

**Comment by gharlan** [comment]
Ich hab das mit Thomas per Skype besprochen. Wir würden dafür plädieren, [hier](https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/scheme.php#L127-L131) noch die Zeichen ®, © und ™ aufzunehmen, und sie jeweils mit einem leeren String zu ersetzen.

Meiner Meinung nach sollten die Zeichen auch nicht in der URL auftauchen, solange wir nichts Grundlegendes ändern, und allgemein UTF-8-Urls zulassen (wofür ich plädiere).
