### ISSUE TITLE
Weiterleitung von index.php?article_id=XX&clang=XX immer eintragen

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yrewrite#98]
da der Rewriter diese überschreibt, können diese auch immer weiterleiten.. Zwar nur relevant, wenn man diese vorher genutzt hatte, aber schadet auch nicht ..

**Comment by alexplusde** [comment]
Hierbei ist zu beachten, dass URLs aus REDAXO4 die clang_id um 1 niedriger haben. Also stimmt evtl. die Zuordnung nicht mehr, wenn sich die clang_id ändert oder von R4 auf R5 konvertiert wurde.
