### ISSUE TITLE
Rewrite von Bild-URLs

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_yrewrite#99]
Gibt es aktuell schon die Möglichkeit Bild-Urls zu schönen URLs zu rewriten? Aktuell sind die Urls ja so:
index.php?rex_media_type=ImgTypeName&rex_media_file=ImageFileName

Ich glaube, im rex_radio mal gelesen zu haben, dass dies via htaccess gelöst wird, man aber die Urls im Quelltext selbst entsprechend umschreiben muss. Ist das korrekt so? Wenn ja, fände ich das recht unschön und würde stattdessen die Nutzung des OUTPUT_FILTER EPs vorschlagen.

**Comment by tbaddade** [comment]
> Ich glaube, im rex_radio mal gelesen zu haben, dass dies via htaccess gelöst wird

richtig.

Der Pfad dazu muss so heißen
`/images/mein_media_type/mein_bild.jpg`

Was ich gut finden würde, wenn yrewrite eine Methode dafür bereitstellt.

**Comment by phoebusryan** [comment]
eben. Quasi ein Plugin oder eine Einstellung, welches die Urls via Regex + OUTPUT_FILTER ersetzt. Das ist ja grundsätzlich absolut easy aber aus meiner Sicht sinnvoll.

**Comment by alexwenz** [comment]
*1

**Comment by ebro** [comment]
Dies kann man ganz einfach in der htaccess lösen:

Einfach nach Rewrite On folgendes hinzufügen:

RewriteRule ^img\/([^\/]+)\/(.*) index.php?rex_media_type=$1&rex_media_file=$2

Mein Beispiel ist mit img statt images... kann natürlich umgeschrieben werden.

Danach können alles Bilder aus dem Medienpool wie folgt aufgerufen werden: 
/img/mein_media_type/mein_bild.jpg

**Comment by alexplusde** [comment]
Das geht auch vollkommen ohne Rewrite. Im Modul kannst du die Pfade ja selbst anpassen.

@phoebusryan Wenn du da noch was mit regex machen willst, verstehe ich den Ansatz nicht.

**Comment by tbaddade** [comment]
> verstehe ich den Ansatz nicht.

geht vermutlich um die Editoren, die beim Einfügen eines Bildes den normalen Pfad verwenden.

PS: Es gibt den EP `MEDIA_URL_REWRITE`

**Comment by phoebusryan** [comment]
Genau darum gehts. Zudem wäre man dann theoretisch abhängig von yrewrite (weil die htaccess von yrewrite kommt), was man sonst nicht ist. Wie immer in Redaxo gibt es mehrere Wege..

**Comment by alexplusde** [comment]
Ah, danke, das ergibt dann schon Sinn. :)

**Comment by alexplusde** [comment]
Hier gibt's doch jetzt ein Addon dazu - wie ist da der Stand?

**Comment by ebro** [comment]
Dank für Ihre E-Mail. 

Ich bin bis am 27. Februar 2017 abwesend.
Die E-Mails werden während dieser Zeit nicht regelmässig gelesen. 

Gerne melde ich mich nach meiner Rückkehr bei Ihnen. 
Vielen Dank für Ihr Verständnis. 

Freundliche Grüsse
Diego Brauchbar


--
ebro - Web Development
Diego Brauchbar, Feldgütliweg 2, 8004 Zürich 
Mobile: +41 79 219 99 32 - Phone:  +41 44 586 20 02 - www.ebro.ch

**Comment by dergel** [comment]
Bauen wir ein .. Ist sinnvoll, vor allem wegen der EPs.. 

/images/mein_media_type/mein_bild.jpg

**Comment by dergel** [comment]
/media/mein_media_type/mein_bild.jpg
/media/mein_bild.jpg -> mediatype default - da normal nicht vorhanden -> einfach ausgabe des bildes/der datei

**Comment by alexplusde** [comment]
Keine so tolle Idee, wenn SVGs nicht richtig durchgeschleift werden. Das Bild wird dann nicht korrekt ausgegeben, weil es den falschen Header bekommt. Damit werden auch alle anderen Einstellungen der .htaccess zum Thema Caching unbrauchbar.

soll:
```
HTTP/1.1 200 OK
Date: Mon, 19 Feb 2018 09:43:27 GMT
Server: Apache
Last-Modified: Mon, 19 Feb 2018 09:35:32 GMT
ETag: "1150-5658d6a5a0d25-gzip"
Accept-Ranges: bytes
Cache-Control: max-age=2419200
Expires: Mon, 19 Mar 2018 09:43:27 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 1843
Keep-Alive: timeout=15, max=99
Connection: Keep-Alive
Content-Type: image/svg+xml
```
ist:
```
HTTP/1.1 200 OK
Date: Mon, 19 Feb 2018 09:42:19 GMT
Server: Apache
Content-Disposition: inline; filename="logo.svg";
Last-Modified: Mon, 19 Feb 2018 09:36:00 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Cache-Control: max-age=0
Expires: Mon, 19 Feb 2018 09:42:19 GMT
Content-Length: 1843
Keep-Alive: timeout=15, max=99
Connection: Keep-Alive
Content-Type: text/html;charset=utf-8
```

**Comment by isospin** [comment]
die rewriterule 
```^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]``` 
führt dazu, das die datei durch die file.php geschleift wird, anstatt direkt vom server ausgeliefert zu werden.
das kann bei großen dateien (z.b. film mp4) zu fehlermeldungen führen, wenn der zulässige speicher überschritten wird:

```ErrorException (E_ERROR): Allowed memory size of 268435456 bytes exhausted ```

**Comment by DonLoron** [comment]
@dergel  
Kann das Fehlverhalten das @isospin beschreibt auch nachvollziehen, hatte Probleme mit Videos die in Safari nicht abgespielt werden können. Würde diese Rule auf Bilder beschränken.

**Comment by mschnieder** [comment]
`RewriteRule ^media/(.*) %{ENV:BASE}/index.php?rex_media_type=default&rex_media_file=$1&%{QUERY_STRING} [B]`

Wie @alexplusde schon geschrieben hat führt es bei svg Dateien zu dem Problem, das ein falscher Header übergeben wird.

Ist das aber ein Fehler vom yrewrite oder vielleicht doch vom MediaManager dass der falsche header übergeben wird?

**Comment by alexplusde** [comment]
Wichtigere Frage: führt der indirekte Aufruf nicht auch noch zu Verzögerungen beim Laden der Seite?

**Comment by mschnieder** [comment]
Eigentlich dürfte dies nicht so sein, Bilder sind, sofern nicht via http2 und Push übergeben, weitere Roundtrips die erst nach dem Parsen des HTMLS vom Browser angefordert werden.
Oder meinst du den jeweiligen Bildaufruf? Der dauert natürlich länger als wenn die Datei direkt vom Webserver zurückgegeben wird.

**Comment by alexplusde** [comment]
Das meinte ich. In bestimmten Fällen will man das schließlich gar nicht, wenn man nicht eh über ein Medienprofil geht.

**Comment by alexwenz** [comment]
Aktuell wieder den Grund gesucht (-> Hirn wie Sieb) warum nach dem erneuten setzen der htaccess-Datei über yrwrite SVG-Dateien nicht mehr angezeigt werden. Gibt es hier eine Idee, wie man das sinnvoll lösen kann?

**Comment by tbaddade** [comment]
@alexwenz 

Lege das mal in die boot.php vom project-AddOn

```php
rex_extension::register('MEDIA_URL_REWRITE', function (rex_extension_point $ep) {
    $media = $ep->getParam('media');
    if ($media->getExtension() == 'svg') {
        return \rex_url::media($media->getFileName());
    }
    return null;
}, rex_extension::EARLY);
```

**Comment by gharlan** [comment]
Das Problem ist mittlerweile behoben, oder?

**Comment by alxndr-w** [comment]
ja
